#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the cnpg-image-catalog workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns="$(kurly::namespace_unique kurly-cnpg-image-catalog-cluster)"
kurly::boot workloads/cnpg-image-catalog/cluster.libsonnet "$ns" "" ""
ns="$(kurly::namespace_unique kurly-cnpg-image-catalog-namespaced)"
kurly::boot workloads/cnpg-image-catalog/namespaced.libsonnet "$ns" "" ""
