#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the sglang workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

echo 'skip: SGLang requires an NVIDIA GPU — the image is built on CUDA with NVIDIA'\''s entrypoint and the pod requests nvidia.com/gpu, so on a node without the device plugin it stays Pending. The image is also 14 GB compressed, which is more than the disk a throwaway test node has. Deployable on a GPU node and not verifiable here.'
exit 0
ns="$(kurly::namespace_unique kurly-sglang)"
kurly::boot workloads/sglang/server.libsonnet "$ns" "" ""
