#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the gravity workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

echo 'skip: Gravity runs on the node'\''s network — DNS, DHCP and TFTP are the point, so the ports it opens ARE the node'\''s ports — and its embedded etcd binds :2380 there. A Kubernetes control-plane node already has etcd on that port, so on a single-node test cluster the two collide and gravity exits with '\''address already in use'\''. That is a collision with where the test runs rather than a defect in the stage: a real deployment puts it on a node that is not a control plane.'
exit 0
ns="$(kurly::namespace_unique kurly-gravity)"
kurly::boot workloads/gravity/server.libsonnet "$ns" "" ""
