#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the netbox workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns=kurly-netbox
kurly::namespace "$ns"

kurly::postgres "$ns" netbox-db-rw netbox netbox
kurly::cache "$ns" netbox-cache

kurly::secret "$ns" netbox workloads/netbox/server.libsonnet
kurly::boot workloads/netbox/server.libsonnet "$ns"
kurly::secret "$ns" netbox workloads/netbox/worker.libsonnet
kurly::boot workloads/netbox/worker.libsonnet "$ns"
