#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the scraparr workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

echo 'skip: Scraparr is an exporter for Sonarr, Radarr, Prowlarr and the rest, and it exits when its configuration names none of them — an exporter with no target has nothing to scrape, so there is no default render that boots. A scenario would have to stand up one of those applications first, which is a fixture for somebody else'\''s workload rather than a check of this one.'
exit 0
ns="$(kurly::namespace_unique kurly-scraparr)"
kurly::boot workloads/scraparr/server.libsonnet "$ns" "" ""
