#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the neo4j workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

kurly::namespace kurly-neo4j
kurly::secret kurly-neo4j neo4j workloads/neo4j/server.libsonnet
kurly::boot workloads/neo4j/server.libsonnet kurly-neo4j "" ""
