#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the mailu workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns=kurly-mailu
kurly::namespace "$ns"

kurly::cache "$ns" mailu-cache-headless

kurly::secret "$ns" mailu workloads/mailu/admin.libsonnet
kurly::boot workloads/mailu/admin.libsonnet "$ns"
kurly::secret "$ns" mailu workloads/mailu/antispam.libsonnet
kurly::boot workloads/mailu/antispam.libsonnet "$ns"
kurly::secret "$ns" mailu workloads/mailu/front.libsonnet
kurly::boot workloads/mailu/front.libsonnet "$ns"
kurly::secret "$ns" mailu workloads/mailu/imap.libsonnet
kurly::boot workloads/mailu/imap.libsonnet "$ns"
kurly::secret "$ns" mailu workloads/mailu/smtp.libsonnet
kurly::boot workloads/mailu/smtp.libsonnet "$ns"
kurly::secret "$ns" mailu workloads/mailu/webmail.libsonnet
kurly::boot workloads/mailu/webmail.libsonnet "$ns"
