#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the harbor workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns="$(kurly::namespace_unique kurly-harbor)"
kurly::namespace "$ns"

kurly::postgres "$ns" harbor-db-rw registry harbor
kurly::cache "$ns" harbor-cache ""

kurly::secret "$ns" harbor workloads/harbor/core.libsonnet
kurly::boot workloads/harbor/core.libsonnet "$ns" "" ""
kurly::secret "$ns" harbor workloads/harbor/jobservice.libsonnet
kurly::boot workloads/harbor/jobservice.libsonnet "$ns" "" ""
kurly::secret "$ns" harbor workloads/harbor/portal.libsonnet
kurly::boot workloads/harbor/portal.libsonnet "$ns" "" ""
kurly::secret "$ns" harbor workloads/harbor/registry.libsonnet
kurly::boot workloads/harbor/registry.libsonnet "$ns" "" ""
