#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the lemmy workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns=kurly-lemmy
kurly::namespace "$ns"

kurly::postgres "$ns" lemmy-db-rw lemmy lemmy

kurly::secret "$ns" lemmy workloads/lemmy/backend.libsonnet
kurly::boot workloads/lemmy/backend.libsonnet "$ns"
kurly::secret "$ns" lemmy-pictrs workloads/lemmy/pictrs.libsonnet
kurly::boot workloads/lemmy/pictrs.libsonnet "$ns"
kurly::secret "$ns" lemmy workloads/lemmy/ui.libsonnet
kurly::boot workloads/lemmy/ui.libsonnet "$ns"
