#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the youtube-dl-nas workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

kurly::namespace kurly-youtube-dl-nas
kurly::secret kurly-youtube-dl-nas youtube-dl-nas workloads/youtube-dl-nas/server.libsonnet
kurly::boot workloads/youtube-dl-nas/server.libsonnet kurly-youtube-dl-nas "" ""
