#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the oxicloud workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns="$(kurly::namespace_unique kurly-oxicloud)"
kurly::namespace "$ns"

kurly::postgres "$ns" oxicloud-db-rw oxicloud oxicloud

echo 'skip: The published image binds 127.0.0.1: OxiCloud starts, migrates its database and then listens on loopback, where nothing outside the pod can reach it. The binary carries no bind-address option and ignores HOST, SERVER_HOST and OXICLOUD_HOST, all three measured on a live cluster. No manifest can fix a server that will not listen on an address its Service can route to.'
exit 0
kurly::secret "$ns" oxicloud workloads/oxicloud/server.libsonnet
kurly::boot workloads/oxicloud/server.libsonnet "$ns" "" ""
