#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the kubetail workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns="$(kurly::namespace_unique kurly-kubetail-cluster-agent)"
kurly::boot workloads/kubetail/cluster-agent.libsonnet "$ns" "" ""
ns="$(kurly::namespace_unique kurly-kubetail-cluster-api)"
kurly::boot workloads/kubetail/cluster-api.libsonnet "$ns" "" ""
ns="$(kurly::namespace_unique kurly-kubetail-dashboard)"
kurly::boot workloads/kubetail/dashboard.libsonnet "$ns" "" ""
