#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the bigcapital workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns=kurly-bigcapital
kurly::namespace "$ns"

kurly::postgres "$ns" bigcapital-db-rw bigcapital bigcapital
kurly::cache "$ns" bigcapital-cache-headless

kurly::secret "$ns" bigcapital workloads/bigcapital/gateway.libsonnet
kurly::boot workloads/bigcapital/gateway.libsonnet "$ns"
kurly::secret "$ns" bigcapital workloads/bigcapital/server.libsonnet
kurly::boot workloads/bigcapital/server.libsonnet "$ns"
kurly::secret "$ns" bigcapital workloads/bigcapital/webapp.libsonnet
kurly::boot workloads/bigcapital/webapp.libsonnet "$ns"
