#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the peertube workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns=kurly-peertube
kurly::namespace "$ns"

kurly::postgres "$ns" peertube-db-rw peertube peertube
kurly::objectstorage "$ns" peertube
kurly::cache "$ns" peertube-cache ""

kurly::secret "$ns" peertube workloads/peertube/server.libsonnet
kurly::boot workloads/peertube/server.libsonnet "$ns" "+ k.env({ PEERTUBE_WEBSERVER_HOSTNAME: 'peertube.example.com' })"
