#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the roundup-issue-tracker workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

kurly::namespace kurly-roundup-issue-tracker
kurly::secret kurly-roundup-issue-tracker roundup-issue-tracker workloads/roundup-issue-tracker/server.libsonnet
kurly::boot workloads/roundup-issue-tracker/server.libsonnet kurly-roundup-issue-tracker "" ""
