#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the tube-archivist workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns=kurly-tube-archivist
kurly::namespace "$ns"

kurly::elasticsearch "$ns" tube-archivist-es
kurly::cache "$ns" tube-archivist-cache-headless ""

kurly::secret "$ns" tube-archivist workloads/tube-archivist/server.libsonnet
kurly::boot workloads/tube-archivist/server.libsonnet "$ns" "+ k.env({ TA_HOST: 'http://tube-archivist:8000' })" ""
