#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the speedtest-tracker workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

kurly::namespace kurly-speedtest-tracker
kurly::secret kurly-speedtest-tracker speedtest-tracker workloads/speedtest-tracker/server.libsonnet
kurly::boot workloads/speedtest-tracker/server.libsonnet kurly-speedtest-tracker "+ k.env({ APP_URL: 'http://speedtest-tracker' })" ""
