#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the matrix-alertmanager-receiver workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

kurly::namespace kurly-matrix-alertmanager-receiver
kurly::secret kurly-matrix-alertmanager-receiver matrix-alertmanager-receiver workloads/matrix-alertmanager-receiver/server.libsonnet
kurly::boot workloads/matrix-alertmanager-receiver/server.libsonnet kurly-matrix-alertmanager-receiver "" "homeserverUrl='https://matrix.example.com', userId='@alerts:matrix.example.com'"
