#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the sosse workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns=kurly-sosse
kurly::namespace "$ns"

kurly::postgres "$ns" sosse-db-rw sosse sosse

kurly::secret "$ns" sosse workloads/sosse/server.libsonnet
kurly::boot workloads/sosse/server.libsonnet "$ns" "" ""
