#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the your-spotify workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns="$(kurly::namespace_unique kurly-your-spotify)"
kurly::namespace "$ns"

kurly::mongodb "$ns" your-spotify-db

kurly::secret "$ns" your-spotify workloads/your-spotify/server.libsonnet
kurly::boot workloads/your-spotify/server.libsonnet "$ns" "+ k.env({ API_ENDPOINT: 'http://your-spotify:8080', CLIENT_ENDPOINT: 'http://your-spotify:3000' })" ""
