#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the librephotos workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns="$(kurly::namespace_unique kurly-librephotos)"
kurly::namespace "$ns"

kurly::postgres "$ns" librephotos-db-rw librephotos librephotos

kurly::secret "$ns" librephotos workloads/librephotos/backend.libsonnet
kurly::boot workloads/librephotos/backend.libsonnet "$ns" "" ""
kurly::secret "$ns" librephotos workloads/librephotos/frontend.libsonnet
kurly::boot workloads/librephotos/frontend.libsonnet "$ns" "" ""
kurly::secret "$ns" librephotos workloads/librephotos/proxy.libsonnet
kurly::boot workloads/librephotos/proxy.libsonnet "$ns" "" ""
