#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the penpot workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns=kurly-penpot
kurly::namespace "$ns"

kurly::postgres "$ns" penpot-db-rw penpot penpot
kurly::cache "$ns" penpot-cache-headless

kurly::secret "$ns" penpot workloads/penpot/backend.libsonnet
kurly::boot workloads/penpot/backend.libsonnet "$ns"
kurly::secret "$ns" penpot workloads/penpot/exporter.libsonnet
kurly::boot workloads/penpot/exporter.libsonnet "$ns"
kurly::secret "$ns" penpot workloads/penpot/frontend.libsonnet
kurly::boot workloads/penpot/frontend.libsonnet "$ns"
