#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the versity-s3-gateway workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns="$(kurly::namespace_unique kurly-versity-s3-gateway)"
kurly::secret "$ns" versity-s3-gateway workloads/versity-s3-gateway/gateway.libsonnet
kurly::boot workloads/versity-s3-gateway/gateway.libsonnet "$ns" "" ""
