#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the aastro workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns="$(kurly::namespace_unique kurly-aastro)"
kurly::boot workloads/aastro/server.libsonnet "$ns" "" "flows=[{ path: '/smoke', method: 'GET', aggregation: { strategy: 'array', best_effort: false }, upstreams: [{ name: 'admin', hosts: 'http://127.0.0.1:7806', path: '/health', method: 'GET', timeout: '3s' }] }]"
