#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the mastodon workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns=kurly-mastodon
kurly::namespace "$ns"

kurly::postgres "$ns" mastodon-db-rw mastodon mastodon
kurly::cache "$ns" mastodon-cache-headless

kurly::secret "$ns" mastodon workloads/mastodon/sidekiq.libsonnet
kurly::boot workloads/mastodon/sidekiq.libsonnet "$ns"
kurly::secret "$ns" mastodon workloads/mastodon/streaming.libsonnet
kurly::boot workloads/mastodon/streaming.libsonnet "$ns"
kurly::secret "$ns" mastodon workloads/mastodon/web.libsonnet
kurly::boot workloads/mastodon/web.libsonnet "$ns"
