#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the thanos workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns=kurly-thanos
kurly::namespace "$ns"

kurly::cache "$ns" thanos-cache-headless

kurly::secret "$ns" thanos workloads/thanos/compact.libsonnet
kurly::boot workloads/thanos/compact.libsonnet "$ns"
kurly::secret "$ns" thanos workloads/thanos/query.libsonnet
kurly::boot workloads/thanos/query.libsonnet "$ns"
kurly::secret "$ns" thanos workloads/thanos/query-frontend.libsonnet
kurly::boot workloads/thanos/query-frontend.libsonnet "$ns"
kurly::secret "$ns" thanos workloads/thanos/receive.libsonnet
kurly::boot workloads/thanos/receive.libsonnet "$ns"
kurly::secret "$ns" thanos workloads/thanos/ruler.libsonnet
kurly::boot workloads/thanos/ruler.libsonnet "$ns"
kurly::secret "$ns" thanos workloads/thanos/store.libsonnet
kurly::boot workloads/thanos/store.libsonnet "$ns"
