#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the superset workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns="$(kurly::namespace_unique kurly-superset)"
kurly::namespace "$ns"

kurly::postgres "$ns" superset-db-rw superset superset
kurly::cache "$ns" superset-cache ""

kurly::secret "$ns" superset workloads/superset/server.libsonnet
kurly::boot workloads/superset/server.libsonnet "$ns" "" ""
kurly::secret "$ns" superset workloads/superset/worker.libsonnet
kurly::boot workloads/superset/worker.libsonnet "$ns" "" ""
