#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the docs workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns="$(kurly::namespace_unique kurly-docs)"
kurly::namespace "$ns"

kurly::postgres "$ns" docs-db-rw docs docs
kurly::objectstorage "$ns" docs
kurly::cache "$ns" docs-cache ""

kurly::secret "$ns" docs workloads/docs/backend.libsonnet
kurly::boot workloads/docs/backend.libsonnet "$ns" "" ""
kurly::secret "$ns" docs workloads/docs/frontend.libsonnet
kurly::boot workloads/docs/frontend.libsonnet "$ns" "" ""
kurly::secret "$ns" docs workloads/docs/y-provider.libsonnet
kurly::boot workloads/docs/y-provider.libsonnet "$ns" "" ""
