#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the cloudflare-tunnel-ingress-controller workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

echo 'skip: The controller reads CLOUDFLARE_API_TOKEN from a Secret and needs a real token, issued in a real Cloudflare account, against a zone somebody owns — it dials Cloudflare on its first reconcile and exits when the account or the token is not there. Nothing can generate that, so a scenario would either fail on a missing Secret or fail authenticating with a made-up one. What it renders is checked by the render gates.'
exit 0
ns="$(kurly::namespace_unique kurly-cloudflare-tunnel-ingress-controller)"
kurly::boot workloads/cloudflare-tunnel-ingress-controller/controller.libsonnet "$ns" "" ""
