#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the screego workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

kurly::namespace kurly-screego
kurly::secret kurly-screego screego workloads/screego/server.libsonnet
kurly::boot workloads/screego/server.libsonnet kurly-screego "+ k.env({ SCREEGO_EXTERNAL_IP: '127.0.0.1' })"
