#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the solectrus workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns=kurly-solectrus
kurly::namespace "$ns"

kurly::postgres "$ns" solectrus-db-rw solectrus solectrus
kurly::cache "$ns" solectrus-cache-headless

kurly::secret "$ns" solectrus workloads/solectrus/server.libsonnet
kurly::boot workloads/solectrus/server.libsonnet "$ns" "" ""
