#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the redash workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns="$(kurly::namespace_unique kurly-redash)"
kurly::namespace "$ns"

kurly::postgres "$ns" redash-db-rw redash redash
kurly::cache "$ns" redash-cache-headless

kurly::secret "$ns" redash workloads/redash/scheduler.libsonnet
kurly::boot workloads/redash/scheduler.libsonnet "$ns" "" ""
kurly::secret "$ns" redash workloads/redash/server.libsonnet
kurly::boot workloads/redash/server.libsonnet "$ns" "" ""
kurly::secret "$ns" redash workloads/redash/worker.libsonnet
kurly::boot workloads/redash/worker.libsonnet "$ns" "" ""
