#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the libredesk workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns=kurly-libredesk
kurly::namespace "$ns"

kurly::postgres "$ns" libredesk-db-rw libredesk libredesk

kurly::secret "$ns" libredesk workloads/libredesk/server.libsonnet
kurly::boot workloads/libredesk/server.libsonnet "$ns" "+ k.env({ LIBREDESK_APP__ROOT_URL: 'http://libredesk:9000' })"
