#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the hatsu workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

echo 'skip: Hatsu fetches https://<primaryAccount>/ at start-up to discover the site'\''s JSON feed and exits when it cannot, so it needs a real site already published on the public internet — an in-cluster feed over plain HTTP clears the discovery error and then fails the HTTPS fetch.'
exit 0
ns="$(kurly::namespace_unique kurly-hatsu)"
kurly::secret "$ns" hatsu workloads/hatsu/server.libsonnet
kurly::boot workloads/hatsu/server.libsonnet "$ns" "+ k.env({ HATSU_DOMAIN: 'hatsu.example.com', HATSU_PRIMARY_ACCOUNT: 'example.com' })" ""
