#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the triton-inference-server workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

echo 'skip: The image is eight gigabytes compressed — more disk than a throwaway test node has — and it is NVIDIA'\''s CUDA base whether or not a GPU is requested. The stage boots with an empty model repository by design, so what a scenario would prove is that a very large image starts, at the cost of the node'\''s disk.'
exit 0
ns="$(kurly::namespace_unique kurly-triton-inference-server)"
kurly::boot workloads/triton-inference-server/server.libsonnet "$ns" "" ""
