#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the immich workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns="$(kurly::namespace_unique kurly-immich)"
kurly::namespace "$ns"

kurly::postgres "$ns" immich-db-rw immich immich ghcr.io/immich-app/postgres:17-vectorchord0.4.3-pgvector0.8.1-pgvectors0.3.0 '"-c", "shared_preload_libraries=vchord.so"'
kurly::cache "$ns" immich-cache-headless ""

kurly::secret "$ns" immich workloads/immich/machine-learning.libsonnet
kurly::boot workloads/immich/machine-learning.libsonnet "$ns" "" ""
kurly::secret "$ns" immich workloads/immich/server.libsonnet
kurly::boot workloads/immich/server.libsonnet "$ns" "" ""
