#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the sync-in workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns=kurly-sync-in
kurly::namespace "$ns"

kurly::mysql "$ns" sync-in-db sync-in sync-in

kurly::secret "$ns" sync-in workloads/sync-in/server.libsonnet
kurly::boot workloads/sync-in/server.libsonnet "$ns"
