#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the chibisafe workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

kurly::boot workloads/chibisafe/frontend.libsonnet kurly-chibisafe-frontend
kurly::boot workloads/chibisafe/proxy.libsonnet kurly-chibisafe-proxy
kurly::namespace kurly-chibisafe-server
kurly::secret kurly-chibisafe-server chibisafe workloads/chibisafe/server.libsonnet
kurly::boot workloads/chibisafe/server.libsonnet kurly-chibisafe-server
