#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the remark42 workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

kurly::namespace kurly-remark42
kurly::secret kurly-remark42 remark42 workloads/remark42/server.libsonnet
kurly::boot workloads/remark42/server.libsonnet kurly-remark42 "+ k.env({ REMARK_URL: 'http://remark42:8080' })"
