#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the k8up workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns="$(kurly::namespace_unique kurly-k8up-backup)"
kurly::secret "$ns" k8up workloads/k8up/backup.libsonnet
kurly::boot workloads/k8up/backup.libsonnet "$ns" "" ""
ns="$(kurly::namespace_unique kurly-k8up-restore)"
kurly::secret "$ns" k8up workloads/k8up/restore.libsonnet
kurly::boot workloads/k8up/restore.libsonnet "$ns" "" ""
ns="$(kurly::namespace_unique kurly-k8up-schedule)"
kurly::secret "$ns" k8up workloads/k8up/schedule.libsonnet
kurly::boot workloads/k8up/schedule.libsonnet "$ns" "" ""
