#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the kubetail workload: boot every stage on a live kind cluster from its
# own published image and wait for it to become healthy. No external dependency.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

echo 'skip: kubetail'\''s cluster-api REQUIRES TLS material and validates it before doing anything else: it exits naming five fields at once — its own certificate and key, and the certificate, key and CA it presents to the cluster-agent. Configuring the sections with tls disabled does not satisfy that validation, and kurly mints no key material, so there is no default render that boots. The cluster-agent and the dashboard start; the api is what a scenario cannot bring up without certificates somebody issued.'
exit 0
ns="$(kurly::namespace_unique kurly-kubetail-cluster-agent)"
kurly::boot workloads/kubetail/cluster-agent.libsonnet "$ns" "" ""
ns="$(kurly::namespace_unique kurly-kubetail-cluster-api)"
kurly::boot workloads/kubetail/cluster-api.libsonnet "$ns" "" ""
ns="$(kurly::namespace_unique kurly-kubetail-dashboard)"
kurly::boot workloads/kubetail/dashboard.libsonnet "$ns" "" ""
