#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the outline workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns=kurly-outline
kurly::namespace "$ns"

kurly::postgres "$ns" outline-db-rw outline outline
kurly::cache "$ns" outline-cache-headless

kurly::secret "$ns" outline workloads/outline/server.libsonnet
kurly::boot workloads/outline/server.libsonnet "$ns" "+ k.env({ URL: 'http://outline:3000', COLLABORATION_URL: 'ws://outline:3000' })"
