#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the wekan workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns="$(kurly::namespace_unique kurly-wekan)"
kurly::namespace "$ns"

kurly::mongodb "$ns" wekan-db

kurly::secret "$ns" wekan workloads/wekan/server.libsonnet
kurly::boot workloads/wekan/server.libsonnet "$ns" "" "rootUrl='http://wekan:8080'"
