#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the ente workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns=kurly-ente
kurly::namespace "$ns"

kurly::postgres "$ns" ente-db-rw ente ente

kurly::secret "$ns" ente workloads/ente/server.libsonnet
kurly::boot workloads/ente/server.libsonnet "$ns"
kurly::secret "$ns" ente workloads/ente/web.libsonnet
kurly::boot workloads/ente/web.libsonnet "$ns"
