#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke
# e2e for the apache-airflow workload: provision its declared dependencies (a throwaway
# postgres/valkey at the service names it defaults to), mint the Secret it reads
# from the catalog secretKeys, then boot every stage and wait for health.
cd "$(dirname "$0")/../.."
# shellcheck source=hack/smoke/lib.sh
source hack/smoke/lib.sh
kurly::vendor

ns=kurly-apache-airflow
kurly::namespace "$ns"

kurly::postgres "$ns" apache-airflow-db-rw apache-airflow apache-airflow

kurly::secret "$ns" apache-airflow workloads/apache-airflow/server.libsonnet
kurly::boot workloads/apache-airflow/server.libsonnet "$ns" "" ""
