// SPDX-FileCopyrightText: The kurly Authors
// SPDX-License-Identifier: 0BSD
//
// Generated by hack/smoke/deep/cr-bsi.sh — DO NOT EDIT. What the pods an
// OPERATOR creates violate, for the stages whose own manifest no policy selects.
//
// A stage that renders only a custom resource is out of scope for bollwerk —
// nothing it writes is a pod, a workload or any other kind the policies match.
// But `pods` IS in scope, so what the operator eventually creates is judged at
// admission like anything else, and on a cluster with bollwerk enforcing these
// pods are REJECTED. The catalogue's applicable:false says the manifest cannot
// be judged; this says what happens anyway.
//
// Measured by applying the stage against a real operator, taking the pod the
// operator produced, and submitting it again as a dry-run create so the
// admission warnings come back to us rather than to the operator.
//
// ABSENT means not measured — an operator that would not install here, or a
// schedule-driven CR that creates no pod until it fires. Never read as clean.
{
  'alertmanager/server': { pods: 1, violates: ['disallow-default-serviceaccount', 'require-non-root-groups', 'require-probes', 'require-run-as-non-root-user', 'restrict-sa-automount-sa-token'] },
  'cnpg-cluster/cluster': { pods: 1, violates: ['require-non-root-groups', 'require-probes', 'require-request-limits', 'require-run-as-non-root-user', 'restrict-sa-automount-sa-token'] },
  'k8up/restore': { pods: 1, violates: ['disallow-default-serviceaccount', 'disallow-privilege-escalation', 'disallow-unwanted-capabilities', 'require-probes', 'require-request-limits', 'require-ro-rootfs', 'require-run-as-nonroot', 'restrict-sa-automount-sa-token'] },
  'mysql-cluster/cluster': { pods: 3, violates: ['require-non-root-groups', 'require-probes', 'require-request-limits', 'require-run-as-non-root-user', 'require-run-as-nonroot', 'restrict-image-registries', 'restrict-sa-automount-sa-token'] },
  'prometheus/server': { pods: 1, violates: ['require-non-root-groups', 'require-probes', 'require-run-as-non-root-user', 'restrict-sa-automount-sa-token'] },
  'thanos/ruler': { pods: 1, violates: ['disallow-default-serviceaccount', 'require-non-root-groups', 'require-probes', 'require-request-limits', 'require-run-as-non-root-user', 'restrict-sa-automount-sa-token'] },
}
