// SPDX-FileCopyrightText: The kurly Authors
// SPDX-License-Identifier: 0BSD

// Generated by scripts/gen-forge.sh from each upstream repository —
// do not edit; regenerate with: gen-forge
//
// What the project's own forge says about it: the licence it detected in the
// repository, the name the repository carries, and whether it is archived. A
// workload's annotation overrides anything here; see catalog/annotations.libsonnet.
{
  '2fauth': {
    license: 'AGPL-3.0',
    name: '2FAuth',
    homepage: 'https://docs.2fauth.app/',
  },
  accent: {
    license: 'BSD-3-Clause',
    name: 'accent',
    homepage: 'https://www.accent.reviews',
  },
  activepieces: {
    name: 'activepieces',
    homepage: 'https://www.activepieces.com',
  },
  actualbudget: {
    license: 'MIT',
    name: 'actual',
    homepage: 'https://actualbudget.org',
  },
  adguardhome: {
    license: 'GPL-3.0',
    name: 'AdGuardHome',
    homepage: 'https://adguard.com/adguard-home/overview.html',
  },
  admidio: {
    license: 'GPL-2.0',
    name: 'admidio',
    homepage: 'https://www.admidio.org',
  },
  adminer: {
    name: 'adminer',
    homepage: 'https://www.adminer.org/',
  },
  adventurelog: {
    name: 'AdventureLog',
    homepage: 'https://adventurelog.app',
  },
  'airsonic-advanced': {
    license: 'GPL-3.0',
    name: 'airsonic-advanced',
  },
  airtrail: {
    license: 'GPL-3.0',
    name: 'AirTrail',
    homepage: 'http://airtrail.johan.ohly.dk/',
  },
  alertmanager: {
    license: 'Apache-2.0',
    name: 'alertmanager',
    homepage: 'https://prometheus.io',
  },
  algernon: {
    license: 'BSD-3-Clause',
    name: 'algernon',
    homepage: 'https://algernon.roboticoverlords.org',
  },
  alist: {
    license: 'AGPL-3.0',
    name: 'alist',
    homepage: 'https://alistgo.com',
  },
  answer: {
    license: 'Apache-2.0',
    name: 'answer',
    homepage: 'https://answer.apache.org',
  },
  anubis: {
    license: 'MIT',
    name: 'anubis',
    homepage: 'https://anubis.techaro.lol/',
  },
  'apache-solr': {
    license: 'Apache-2.0',
    name: 'solr',
    homepage: 'https://solr.apache.org/',
  },
  apprise: {
    license: 'BSD-2-Clause',
    name: 'apprise',
    homepage: 'https://hub.docker.com/r/caronc/apprise',
  },
  archivebox: {
    license: 'MIT',
    name: 'ArchiveBox',
    homepage: 'https://archivebox.io',
  },
  artalk: {
    license: 'MIT',
    name: 'Artalk',
    homepage: 'https://artalk.js.org',
  },
  atheos: {
    name: 'Atheos',
    homepage: 'https://www.atheos.io/',
  },
  'atomic-server': {
    name: 'atomic-server',
    homepage: 'https://atomicserver.eu',
  },
  atsumeru: {
    license: 'MIT',
    name: 'Atsumeru',
    homepage: 'https://atsumeru.xyz',
  },
  audiobookshelf: {
    license: 'GPL-3.0',
    name: 'audiobookshelf',
    homepage: 'https://audiobookshelf.org',
  },
  authelia: {
    license: 'Apache-2.0',
    name: 'authelia',
    homepage: 'https://www.authelia.com',
  },
  authentik: {
    name: 'authentik',
    homepage: 'https://goauthentik.io',
  },
  automatisch: {
    name: 'automatisch',
    homepage: 'https://automatisch.io',
  },
  azuracast: {
    license: 'AGPL-3.0',
    name: 'AzuraCast',
    homepage: 'https://www.azuracast.com/',
  },
  baikal: {
    license: 'GPL-3.0',
    name: 'Baikal',
    homepage: 'https://sabre.io/baikal/',
  },
  bazarr: {
    license: 'GPL-3.0',
    name: 'bazarr',
    homepage: 'https://www.bazarr.media',
  },
  beszel: {
    license: 'MIT',
    name: 'beszel',
    homepage: 'https://beszel.dev',
  },
  bitcart: {
    license: 'MIT',
    name: 'bitcart',
    homepage: 'https://bitcart.ai',
  },
  'blackbox-exporter': {
    license: 'Apache-2.0',
    name: 'blackbox_exporter',
    homepage: 'https://prometheus.io',
  },
  blinko: {
    license: 'GPL-3.0',
    name: 'blinko',
    homepage: 'https://blinko.space',
  },
  blocky: {
    license: 'Apache-2.0',
    name: 'blocky',
    homepage: 'https://0xERR0R.github.io/blocky/',
  },
  bookstack: {
    license: 'MIT',
    name: 'BookStack',
    homepage: 'https://codeberg.org/bookstack/bookstack',
  },
  bracket: {
    license: 'AGPL-3.0',
    name: 'bracket',
    homepage: 'https://docs.bracketapp.nl',
  },
  'budget-board': {
    license: 'AGPL-3.0',
    name: 'budget-board',
    homepage: 'https://budgetboard.net',
  },
  caddy: {
    license: 'Apache-2.0',
    name: 'caddy',
    homepage: 'https://caddyserver.com',
  },
  calagopus: {
    license: 'MIT',
    name: 'panel',
    homepage: 'https://calagopus.com',
  },
  calibre: {
    license: 'GPL-3.0',
    name: 'calibre',
    homepage: 'https://calibre-ebook.com',
  },
  'calibre-web': {
    license: 'GPL-3.0',
    name: 'calibre-web',
  },
  'calibre-web-automated': {
    license: 'GPL-3.0',
    name: 'Calibre-Web-Automated',
    homepage: 'https://github.com/crocodilestick/Calibre-Web-Automated',
  },
  'cassandra-cluster': {
    license: 'Apache-2.0',
    name: 'cassandra',
    homepage: 'https://cassandra.apache.org/',
  },
  centrifugo: {
    license: 'Apache-2.0',
    name: 'centrifugo',
    homepage: 'https://centrifugal.dev',
  },
  changedetection: {
    license: 'Apache-2.0',
    name: 'changedetection.io',
    homepage: 'https://changedetection.io',
  },
  chatpad: {
    license: 'AGPL-3.0',
    name: 'chatpad',
    homepage: 'https://chatpad.ai',
  },
  'chhoto-url': {
    license: 'MIT',
    name: 'chhoto-url',
    homepage: 'https://chhoto.link',
  },
  chibisafe: {
    license: 'MIT',
    name: 'chibisafe',
    homepage: 'https://chibisafe.app',
  },
  chronoframe: {
    license: 'MIT',
    name: 'chronoframe',
    homepage: 'https://chronoframe.bh8.ga/',
  },
  cloudbeaver: {
    license: 'Apache-2.0',
    name: 'cloudbeaver',
    homepage: 'https://dbeaver.com/',
  },
  cloudreve: {
    license: 'GPL-3.0',
    name: 'cloudreve',
    homepage: 'https://cloudreve.org',
  },
  'cnpg-cluster': {
    name: 'postgres',
    homepage: 'https://www.postgresql.org/',
  },
  'cnpg-image-catalog': {
    name: 'postgres',
    homepage: 'https://www.postgresql.org/',
  },
  cobalt: {
    license: 'AGPL-3.0',
    name: 'cobalt',
    homepage: 'https://cobalt.tools',
  },
  'code-server': {
    license: 'MIT',
    name: 'code-server',
    homepage: 'https://coder.com',
  },
  commafeed: {
    license: 'Apache-2.0',
    name: 'commafeed',
    homepage: 'https://www.commafeed.com',
  },
  convertx: {
    license: 'AGPL-3.0',
    name: 'ConvertX',
  },
  couchdb: {
    license: 'Apache-2.0',
    name: 'couchdb',
    homepage: 'https://couchdb.apache.org/',
  },
  'crafty-controller': {
    license: 'gpl-3.0+',
    name: 'Crafty 4',
  },
  cryptpad: {
    license: 'AGPL-3.0',
    name: 'cryptpad',
    homepage: 'https://cryptpad.org',
  },
  cyberchef: {
    license: 'Apache-2.0',
    name: 'CyberChef',
    homepage: 'https://gchq.github.io/CyberChef',
  },
  damselfly: {
    license: 'GPL-3.0',
    name: 'Damselfly',
  },
  dashy: {
    license: 'MIT',
    name: 'dashy',
    homepage: 'https://dashy.to',
  },
  davis: {
    license: 'MIT',
    name: 'davis',
    homepage: 'https://github.com/users/tchapi/projects/1/views/1',
  },
  davos: {
    license: 'MIT',
    name: 'davos',
  },
  deluge: {
    name: 'deluge',
    homepage: 'https://www.deluge-torrent.org',
  },
  dex: {
    license: 'Apache-2.0',
    name: 'dex',
    homepage: 'https://dexidp.io',
  },
  'directory-lister': {
    license: 'MIT',
    name: 'DirectoryLister',
    homepage: 'https://www.directorylister.com',
  },
  'discount-bandit': {
    name: 'Discount-Bandit',
    homepage: 'https://discount-bandit.cybrarist.com',
  },
  docassemble: {
    license: 'MIT',
    name: 'docassemble',
    homepage: 'https://docassemble.org',
  },
  'docker-registry-ui': {
    license: 'AGPL-3.0',
    name: 'docker-registry-ui',
    homepage: 'https://joxit.dev/docker-registry-ui/',
  },
  docmost: {
    license: 'AGPL-3.0',
    name: 'docmost',
    homepage: 'https://docmost.com',
  },
  docspell: {
    license: 'AGPL-3.0',
    name: 'docspell',
    homepage: 'https://docspell.org',
  },
  docuseal: {
    license: 'AGPL-3.0',
    name: 'docuseal',
    homepage: 'https://www.docuseal.com',
  },
  dokuwiki: {
    license: 'GPL-2.0',
    name: 'dokuwiki',
    homepage: 'http://www.dokuwiki.org',
  },
  domoticz: {
    license: 'GPL-3.0',
    name: 'domoticz',
    homepage: 'https://www.domoticz.com',
  },
  downtify: {
    license: 'GPL-3.0',
    name: 'downtify',
    homepage: 'https://downtify.henriquesebastiao.com',
  },
  'draw-io': {
    license: 'Apache-2.0',
    name: 'drawio',
    homepage: 'https://www.drawio.com',
  },
  drawio: {
    license: 'Apache-2.0',
    name: 'drawio',
    homepage: 'https://www.drawio.com',
  },
  drop: {
    name: 'drop',
    homepage: 'https://droposs.org',
  },
  drupal: {
    name: 'drupal',
    homepage: 'https://drupal.org/project/drupal',
  },
  duplicati: {
    name: 'duplicati',
  },
  ech0: {
    license: 'AGPL-3.0',
    name: 'Ech0',
    homepage: 'https://Ech0.app',
  },
  ejabberd: {
    name: 'ejabberd',
    homepage: 'https://www.process-one.net/ejabberd/',
  },
  'element-web': {
    license: 'AGPL-3.0',
    name: 'element-web',
    homepage: 'https://element.io',
  },
  endurain: {
    license: 'AGPL-3.0',
    name: 'endurain',
    homepage: 'https://endurain.com',
  },
  'enigma-12-bbs': {
    license: 'BSD-2-Clause',
    name: 'enigma-bbs',
    homepage: 'https://nuskooler.github.io/enigma-bbs/',
  },
  ente: {
    license: 'AGPL-3.0',
    name: 'ente',
    homepage: 'https://ente.com',
  },
  ergo: {
    license: 'MIT',
    name: 'ergo',
    homepage: 'https://ergo.chat/',
  },
  esphome: {
    name: 'esphome',
    homepage: 'https://esphome.io/',
  },
  etherpad: {
    license: 'Apache-2.0',
    name: 'etherpad',
    homepage: 'https://etherpad.org',
  },
  evcc: {
    license: 'MIT',
    name: 'evcc',
    homepage: 'https://evcc.io',
  },
  evershop: {
    license: 'GPL-3.0',
    name: 'evershop',
    homepage: 'https://evershop.io/',
  },
  excalidraw: {
    license: 'MIT',
    name: 'excalidraw',
    homepage: 'https://excalidraw.com',
  },
  expenseowl: {
    license: 'MIT',
    name: 'ExpenseOwl',
  },
  ezbookkeeping: {
    license: 'MIT',
    name: 'ezbookkeeping',
    homepage: 'https://ezbookkeeping.mayswind.net',
  },
  ferretdb: {
    license: 'Apache-2.0',
    name: 'FerretDB',
    homepage: 'https://www.ferretdb.com',
  },
  ferron: {
    license: 'MIT',
    name: 'ferron',
    homepage: 'https://ferron.sh',
  },
  fider: {
    license: 'AGPL-3.0',
    name: 'fider',
    homepage: 'https://fider.io',
  },
  filebrowser: {
    license: 'Apache-2.0',
    name: 'filebrowser',
  },
  filestash: {
    license: 'AGPL-3.0',
    name: 'filestash',
    homepage: 'https://www.filestash.app/',
  },
  'firefly-iii': {
    license: 'AGPL-3.0',
    name: 'firefly-iii',
    homepage: 'https://firefly-iii.org/',
  },
  fittrackee: {
    license: 'AGPL-3.0',
    name: 'FitTrackee',
    homepage: 'https://docs.fittrackee.org',
  },
  flame: {
    license: 'MIT',
    name: 'flame',
  },
  flaresolverr: {
    license: 'MIT',
    name: 'FlareSolverr',
  },
  flatnotes: {
    license: 'MIT',
    name: 'flatnotes',
  },
  flowctl: {
    license: 'Apache-2.0',
    name: 'flowctl',
    homepage: 'https://flowctl.net',
  },
  fluidd: {
    license: 'GPL-3.0',
    name: 'fluidd',
    homepage: 'https://docs.fluidd.xyz',
  },
  focalboard: {
    name: 'focalboard',
    homepage: 'https://www.focalboard.com',
  },
  foldingathome: {
    license: 'GPL-3.0',
    name: 'fah-client-bastet',
  },
  fossbilling: {
    license: 'Apache-2.0',
    name: 'FOSSBilling',
    homepage: 'https://fossbilling.org',
  },
  freshrss: {
    license: 'AGPL-3.0',
    name: 'FreshRSS',
    homepage: 'https://freshrss.org',
  },
  frigate: {
    license: 'MIT',
    name: 'frigate',
    homepage: 'https://frigate.video',
  },
  fusio: {
    license: 'Apache-2.0',
    name: 'fusio',
    homepage: 'https://www.fusio-project.org',
  },
  gameyfin: {
    license: 'AGPL-3.0',
    name: 'gameyfin',
  },
  gatus: {
    license: 'Apache-2.0',
    name: 'gatus',
    homepage: 'https://gatus.io',
  },
  gerbera: {
    name: 'gerbera',
    homepage: 'https://gerbera.io',
  },
  gerrit: {
    license: 'Apache-2.0',
    name: 'gerrit',
  },
  ghostfolio: {
    license: 'AGPL-3.0',
    name: 'ghostfolio',
    homepage: 'https://Ghostfol.io',
  },
  gitproxy: {
    license: 'Apache-2.0',
    name: 'git-proxy',
    homepage: 'https://git-proxy.finos.org',
  },
  glance: {
    license: 'AGPL-3.0',
    name: 'glance',
  },
  gogs: {
    license: 'MIT',
    name: 'gogs',
    homepage: 'https://gogs.io',
  },
  gokapi: {
    license: 'AGPL-3.0',
    name: 'Gokapi',
  },
  gonic: {
    license: 'GPL-3.0',
    name: 'gonic',
    homepage: 'https://web.libera.chat/?channels=#gonic',
  },
  gotenberg: {
    license: 'MIT',
    name: 'gotenberg',
    homepage: 'https://gotenberg.dev',
  },
  gotify: {
    name: 'server',
    homepage: 'https://gotify.net',
  },
  grav: {
    license: 'MIT',
    name: 'grav',
    homepage: 'https://getgrav.org',
  },
  greenlight: {
    license: 'LGPL-3.0',
    name: 'greenlight',
  },
  grocy: {
    license: 'MIT',
    name: 'grocy',
    homepage: 'https://grocy.info',
  },
  guacamole: {
    license: 'Apache-2.0',
    name: 'guacamole-server',
    homepage: 'https://guacamole.apache.org/',
  },
  habitat: {
    license: 'AGPL-3.0',
    name: 'habitat',
    homepage: 'https://gethabitat.org',
  },
  halo: {
    license: 'GPL-3.0',
    name: 'halo',
    homepage: 'https://www.halo.run',
  },
  hatsu: {
    license: 'AGPL-3.0',
    name: 'hatsu',
    homepage: 'https://hatsu.cli.rs',
  },
  hedgedoc: {
    license: 'AGPL-3.0',
    name: 'hedgedoc',
    homepage: 'https://hedgedoc.org',
  },
  heimdall: {
    license: 'MIT',
    name: 'Heimdall',
  },
  hister: {
    license: 'AGPL-3.0',
    name: 'hister',
    homepage: 'https://hister.org/',
  },
  hollama: {
    license: 'MIT',
    name: 'hollama',
    homepage: 'https://hollama.fernando.is',
  },
  homarr: {
    license: 'Apache-2.0',
    name: 'homarr',
    homepage: 'https://homarr.dev',
  },
  'home-assistant': {
    license: 'Apache-2.0',
    name: 'core',
    homepage: 'https://www.home-assistant.io',
  },
  homebox: {
    license: 'AGPL-3.0',
    name: 'homebox',
    homepage: 'https://homebox.software',
  },
  homegallery: {
    license: 'MIT',
    name: 'home-gallery',
    homepage: 'https://home-gallery.org',
  },
  homepage: {
    license: 'GPL-3.0',
    name: 'homepage',
    homepage: 'https://gethomepage.dev',
  },
  homer: {
    license: 'Apache-2.0',
    name: 'homer',
    homepage: 'https://homer-demo.netlify.app/',
  },
  hortusfox: {
    license: 'MIT',
    name: 'hortusfox-web',
    homepage: 'https://www.hortusfox.com',
  },
  imgcompress: {
    license: 'GPL-3.0',
    name: 'imgcompress',
    homepage: 'https://imgcompress.karimzouine.com',
  },
  immich: {
    license: 'AGPL-3.0',
    name: 'immich',
    homepage: 'https://immich.app',
  },
  inspircd: {
    name: 'inspircd',
    homepage: 'https://www.inspircd.org',
  },
  invidious: {
    license: 'AGPL-3.0',
    name: 'invidious',
    homepage: 'https://invidious.io',
  },
  invoiceshelf: {
    license: 'AGPL-3.0',
    name: 'InvoiceShelf',
    homepage: 'https://invoiceshelf.com',
  },
  isso: {
    license: 'MIT',
    name: 'isso',
    homepage: 'https://isso-comments.de',
  },
  'it-tools': {
    license: 'GPL-3.0',
    name: 'it-tools',
    homepage: 'https://it-tools.tech',
  },
  jackett: {
    license: 'GPL-2.0',
    name: 'Jackett',
  },
  jellyfin: {
    license: 'GPL-2.0',
    name: 'jellyfin',
    homepage: 'https://jellyfin.org',
  },
  jellyseerr: {
    license: 'MIT',
    name: 'seerr',
    homepage: 'https://docs.seerr.dev',
  },
  jelu: {
    license: 'MIT',
    name: 'jelu',
  },
  jenkins: {
    license: 'MIT',
    name: 'jenkins',
    homepage: 'https://www.jenkins.io',
  },
  joomla: {
    license: 'GPL-2.0',
    name: 'joomla-cms',
    homepage: 'https://www.joomla.org',
  },
  joplin: {
    name: 'joplin',
    homepage: 'https://joplinapp.org',
  },
  jotty: {
    license: 'AGPL-3.0',
    name: 'jotty',
    homepage: 'https://jotty.page',
  },
  jupyterlab: {
    license: 'BSD-3-Clause',
    name: 'jupyterlab',
    homepage: 'https://jupyterlab.readthedocs.io/',
  },
  k8up: {
    license: 'Apache-2.0',
    name: 'k8up',
    homepage: 'https://k8up.io',
  },
  kanboard: {
    license: 'MIT',
    name: 'kanboard',
    homepage: 'https://kanboard.org',
  },
  kapowarr: {
    license: 'GPL-3.0',
    name: 'Kapowarr',
    homepage: 'https://casvt.github.io/Kapowarr/',
  },
  karakeep: {
    license: 'AGPL-3.0',
    name: 'karakeep',
    homepage: 'https://karakeep.app',
  },
  'karaoke-eternal': {
    license: 'ISC',
    name: 'KaraokeEternal',
    homepage: 'https://www.karaoke-eternal.com',
  },
  kavita: {
    license: 'GPL-3.0',
    name: 'Kavita',
    homepage: 'http://www.kavitareader.com',
  },
  keycloak: {
    license: 'Apache-2.0',
    name: 'keycloak',
    homepage: 'https://www.keycloak.org',
  },
  kimai: {
    license: 'AGPL-3.0',
    name: 'kimai',
    homepage: 'https://www.kimai.org',
  },
  koillection: {
    license: 'MIT',
    name: 'koillection',
    homepage: 'https://github.com/koillection/koillection/wiki',
  },
  komga: {
    license: 'MIT',
    name: 'komga',
    homepage: 'https://komga.org',
  },
  kresus: {
    license: 'AGPL-3.0',
    name: 'kresus',
    homepage: 'https://kresus.org',
  },
  kutt: {
    license: 'MIT',
    name: 'kutt',
    homepage: 'https://kutt.to',
  },
  kyoo: {
    license: 'GPL-3.0',
    name: 'Kyoo',
    homepage: 'https://kyoo.zoriya.dev',
  },
  lancache: {
    name: 'monolithic',
    homepage: 'https://hub.docker.com/r/lancachenet/monolithic',
  },
  leantime: {
    license: 'AGPL-3.0',
    name: 'leantime',
    homepage: 'https://leantime.io',
  },
  ledgersmb: {
    name: 'LedgerSMB',
    homepage: 'https://ledgersmb.org',
  },
  lemmy: {
    license: 'AGPL-3.0',
    name: 'lemmy',
    homepage: 'https://join-lemmy.org',
  },
  librebooking: {
    license: 'GPL-3.0',
    name: 'librebooking',
    homepage: 'https://librebooking.readthedocs.io/',
  },
  librechat: {
    license: 'MIT',
    name: 'LibreChat',
    homepage: 'https://librechat.ai/',
  },
  'libredb-studio': {
    license: 'MIT',
    name: 'libredb-studio',
    homepage: 'https://libredb.org',
  },
  libredesk: {
    license: 'AGPL-3.0',
    name: 'libredesk',
    homepage: 'https://libredesk.io',
  },
  librephotos: {
    license: 'MIT',
    name: 'librephotos',
    homepage: 'https://docs.librephotos.com/',
  },
  librespeed: {
    license: 'LGPL-3.0',
    name: 'speedtest',
    homepage: 'https://librespeed.org',
  },
  libretime: {
    license: 'AGPL-3.0',
    name: 'libretime',
    homepage: 'http://libretime.org',
  },
  lidarr: {
    license: 'GPL-3.0',
    name: 'Lidarr',
    homepage: 'http://lidarr.audio/',
  },
  linkding: {
    license: 'MIT',
    name: 'linkding',
    homepage: 'https://linkding.link/',
  },
  linkstack: {
    license: 'AGPL-3.0',
    name: 'LinkStack',
    homepage: 'https://linkstack.org',
  },
  listmonk: {
    license: 'AGPL-3.0',
    name: 'listmonk',
    homepage: 'https://listmonk.app',
  },
  livebook: {
    license: 'Apache-2.0',
    name: 'livebook',
    homepage: 'https://livebook.dev',
  },
  liwan: {
    license: 'Apache-2.0',
    name: 'liwan',
    homepage: 'https://liwan.dev',
  },
  lldap: {
    license: 'GPL-3.0',
    name: 'lldap',
  },
  llmkube: {
    license: 'Apache-2.0',
    name: 'LLMKube',
    homepage: 'https://llmkube.com',
  },
  'lobe-chat': {
    name: 'lobehub',
    homepage: 'https://lobehub.com',
  },
  loki: {
    license: 'AGPL-3.0',
    name: 'loki',
    homepage: 'https://grafana.com/oss/loki',
  },
  lubelogger: {
    license: 'MIT',
    name: 'lubelog',
    homepage: 'https://lubelogger.com',
  },
  lychee: {
    license: 'MIT',
    name: 'Lychee',
    homepage: 'https://lycheeorg.dev',
  },
  mafl: {
    license: 'MIT',
    name: 'mafl',
    homepage: 'https://mafl.hywax.space',
  },
  mailhog: {
    license: 'MIT',
    name: 'MailHog',
  },
  mailpit: {
    license: 'MIT',
    name: 'mailpit',
    homepage: 'https://mailpit.axllent.org',
  },
  mailu: {
    name: 'Mailu',
    homepage: 'https://mailu.io',
  },
  mainsail: {
    license: 'GPL-3.0',
    name: 'mainsail',
    homepage: 'https://docs.mainsail.xyz',
  },
  maloja: {
    license: 'GPL-3.0',
    name: 'maloja',
    homepage: 'https://maloja.krateng.ch',
  },
  'manage-my-damn-life': {
    license: 'GPL-3.0',
    name: 'manage-my-damn-life-nextjs',
    homepage: 'https://intri.in/manage-my-damn-life/',
  },
  manticore: {
    license: 'GPL-3.0',
    name: 'manticoresearch',
    homepage: 'https://manticoresearch.com',
  },
  mastodon: {
    license: 'AGPL-3.0',
    name: 'mastodon',
    homepage: 'https://joinmastodon.org',
  },
  matchering: {
    license: 'GPL-3.0',
    name: 'matchering',
    homepage: 'https://pypi.org/project/matchering/',
  },
  'matrix-conduit': {
    license: 'apache-2.0',
    name: 'Conduit',
  },
  mautic: {
    name: 'mautic',
    homepage: 'https://www.mautic.org',
  },
  'mayan-edms': {
    license: 'LICENSE',
    name: 'Mayan EDMS',
  },
  mazanoke: {
    license: 'GPL-3.0',
    name: 'mazanoke',
    homepage: 'https://MAZANOKE.com',
  },
  mealie: {
    license: 'AGPL-3.0',
    name: 'mealie',
    homepage: 'https://docs.mealie.io',
  },
  'medama-analytics': {
    name: 'medama',
    homepage: 'https://oss.medama.io',
  },
  mediawiki: {
    name: 'mediawiki',
    homepage: 'https://www.mediawiki.org',
  },
  memcached: {
    license: 'BSD-3-Clause',
    name: 'memcached',
    homepage: 'https://memcached.org',
  },
  memos: {
    license: 'MIT',
    name: 'memos',
    homepage: 'https://usememos.com',
  },
  memtly: {
    license: 'GPL-3.0',
    name: 'Memtly.Community',
    homepage: 'https://memtly.com',
  },
  'mermaid-live-editor': {
    license: 'MIT',
    name: 'mermaid-live-editor',
    homepage: 'https://mermaid.live',
  },
  'metrics-server': {
    license: 'Apache-2.0',
    name: 'metrics-server',
    homepage: 'https://kubernetes.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/',
  },
  metube: {
    license: 'AGPL-3.0',
    name: 'metube',
  },
  microbin: {
    license: 'BSD-3-Clause',
    name: 'microbin',
    homepage: 'https://microbin.eu',
  },
  mindwendel: {
    license: 'AGPL-3.0',
    name: 'mindwendel',
    homepage: 'https://www.mindwendel.com',
  },
  misskey: {
    license: 'AGPL-3.0',
    name: 'misskey',
    homepage: 'https://misskey-hub.net/',
  },
  'mongo-express': {
    license: 'MIT',
    name: 'mongo-express',
  },
  monica: {
    license: 'AGPL-3.0',
    name: 'monica',
    homepage: 'https://beta.monicahq.com',
  },
  mosquitto: {
    name: 'mosquitto',
    homepage: 'https://mosquitto.org',
  },
  'multi-scrobbler': {
    license: 'MIT',
    name: 'multi-scrobbler',
    homepage: 'https://docs.multi-scrobbler.app',
  },
  mumble: {
    name: 'mumble',
    homepage: 'https://www.mumble.info',
  },
  'myfin-budget': {
    license: 'GPL-3.0',
    name: 'myfin',
    homepage: 'https://myfinbudget.com',
  },
  mylar3: {
    license: 'GPL-3.0',
    name: 'mylar3',
  },
  myspeed: {
    license: 'MIT',
    name: 'MySpeed',
    homepage: 'https://myspeed.dev',
  },
  'mysql-cluster': {
    name: 'mysql-server',
    homepage: 'http://www.mysql.com/',
  },
  nats: {
    license: 'Apache-2.0',
    name: 'nats-server',
    homepage: 'https://nats.io',
  },
  navidrome: {
    license: 'GPL-3.0',
    name: 'navidrome',
    homepage: 'https://www.navidrome.org',
  },
  neko: {
    license: 'Apache-2.0',
    name: 'neko',
    homepage: 'https://neko.m1k1o.net/',
  },
  neo4j: {
    license: 'GPL-3.0',
    name: 'neo4j',
    homepage: 'http://neo4j.com',
  },
  netalertx: {
    license: 'GPL-3.0',
    name: 'NetAlertX',
    homepage: 'https://netalertx.com',
  },
  netbootxyz: {
    license: 'Apache-2.0',
    name: 'netboot.xyz',
    homepage: 'https://netboot.xyz',
  },
  netbox: {
    license: 'Apache-2.0',
    name: 'netbox',
    homepage: 'https://netboxlabs.com/products/netbox/',
  },
  nextcloud: {
    license: 'AGPL-3.0',
    name: 'server',
    homepage: 'https://nextcloud.com',
  },
  'nginx-proxy-manager': {
    license: 'MIT',
    name: 'nginx-proxy-manager',
    homepage: 'https://nginxproxymanager.com',
  },
  nocobase: {
    name: 'nocobase',
    homepage: 'https://www.nocobase.com',
  },
  'node-red': {
    license: 'Apache-2.0',
    name: 'node-red',
    homepage: 'http://nodered.org',
  },
  'note-mark': {
    license: 'AGPL-3.0',
    name: 'note-mark',
    homepage: 'https://notemark.docs.enchantedcode.co.uk/',
  },
  numa: {
    license: 'MIT',
    name: 'numa',
  },
  nzbget: {
    license: 'GPL-2.0',
    name: 'nzbget',
    homepage: 'https://nzbget.com',
  },
  nzbhydra2: {
    license: 'GPL-3.0',
    name: 'nzbhydra2',
  },
  'oauth2-proxy': {
    license: 'MIT',
    name: 'oauth2-proxy',
    homepage: 'https://oauth2-proxy.github.io/oauth2-proxy',
  },
  ocular: {
    license: 'MIT',
    name: 'ocular',
    homepage: 'https://simonwep.github.io/ocular',
  },
  offen: {
    license: 'Apache-2.0',
    name: 'offen',
    homepage: 'https://www.offen.dev',
  },
  ollama: {
    license: 'MIT',
    name: 'ollama',
    homepage: 'https://ollama.com',
  },
  ombi: {
    license: 'GPL-2.0',
    name: 'Ombi',
    homepage: 'http://ombi.io',
  },
  omnitools: {
    license: 'MIT',
    name: 'omni-tools',
    homepage: 'https://omnitools.app',
  },
  onlyoffice: {
    license: 'AGPL-3.0',
    name: 'DocumentServer',
    homepage: 'https://www.onlyoffice.com/see-it-in-action',
  },
  'open-webui': {
    name: 'open-webui',
    homepage: 'https://openwebui.com',
  },
  opencloud: {
    license: 'Apache-2.0',
    name: 'opencloud',
    homepage: 'https://opencloud.eu',
  },
  opencost: {
    license: 'Apache-2.0',
    name: 'opencost',
    homepage: 'http://opencost.io',
  },
  opengist: {
    license: 'AGPL-3.0',
    name: 'opengist',
    homepage: 'https://opengist.io',
  },
  openhab: {
    license: 'EPL-2.0',
    name: 'openhab-core',
    homepage: 'https://www.openhab.org/',
  },
  openhabittracker: {
    license: 'GPL-3.0',
    name: 'OpenHabitTracker',
    homepage: 'https://openhabittracker.net',
  },
  openreader: {
    license: 'MIT',
    name: 'openreader',
    homepage: 'https://openreader.richardr.dev',
  },
  'opensearch-cluster': {
    license: 'Apache-2.0',
    name: 'OpenSearch',
    homepage: 'https://opensearch.org/docs/latest/opensearch/index/',
  },
  organizr: {
    license: 'GPL-3.0',
    name: 'Organizr',
  },
  'otel-collector': {
    license: 'Apache-2.0',
    name: 'opentelemetry-collector-releases',
    homepage: 'https://opentelemetry.io',
  },
  otterwiki: {
    license: 'MIT',
    name: 'otterwiki',
    homepage: 'https://otterwiki.com',
  },
  overleaf: {
    license: 'AGPL-3.0',
    name: 'overleaf',
  },
  owncast: {
    license: 'MIT',
    name: 'owncast',
    homepage: 'https://owncast.online',
  },
  'owntracks-recorder': {
    name: 'recorder',
  },
  pairdrop: {
    license: 'GPL-3.0',
    name: 'PairDrop',
    homepage: 'https://pairdrop.net',
  },
  paisa: {
    license: 'AGPL-3.0',
    name: 'paisa',
    homepage: 'https://paisa.fyi',
  },
  'paperless-ngx': {
    license: 'GPL-3.0',
    name: 'paperless-ngx',
    homepage: 'http://docs.paperless-ngx.com/',
  },
  'part-db': {
    license: 'AGPL-3.0',
    name: 'Part-DB-server',
    homepage: 'https://docs.part-db.de/',
  },
  passwordpusher: {
    license: 'Apache-2.0',
    name: 'PasswordPusher',
    homepage: 'https://docs.pwpush.com',
  },
  pdfding: {
    license: 'AGPL-3.0',
    name: 'PdfDing',
    homepage: 'https://www.pdfding.com',
  },
  peertube: {
    license: 'AGPL-3.0',
    name: 'PeerTube',
    homepage: 'https://joinpeertube.org/',
  },
  'pelican-panel': {
    license: 'AGPL-3.0',
    name: 'panel',
    homepage: 'https://pelican.dev',
  },
  pgadmin: {
    name: 'pgadmin4',
    homepage: 'https://www.pgadmin.org',
  },
  photoprism: {
    name: 'photoprism',
    homepage: 'https://www.photoprism.app',
  },
  photoview: {
    license: 'AGPL-3.0',
    name: 'photoview',
    homepage: 'https://photoview.github.io/',
  },
  phpmyadmin: {
    license: 'GPL-2.0',
    name: 'phpmyadmin',
    homepage: 'https://www.phpmyadmin.net/',
  },
  picoshare: {
    name: 'picoshare',
  },
  pictshare: {
    name: 'pictshare',
    homepage: 'https://www.pictshare.net',
  },
  'pigallery-2': {
    license: 'MIT',
    name: 'pigallery2',
    homepage: 'http://bpatrik.github.io/pigallery2/',
  },
  pihole: {
    name: 'pi-hole',
    homepage: 'https://pi-hole.net',
  },
  piler: {
    name: 'piler',
    homepage: 'https://www.mailpiler.org/',
  },
  pilos: {
    license: 'LGPL-2.1',
    name: 'PILOS',
    homepage: 'https://thm-health.github.io/PILOS/',
  },
  pinchflat: {
    license: 'AGPL-3.0',
    name: 'pinchflat',
  },
  pinepods: {
    license: 'GPL-3.0',
    name: 'PinePods',
    homepage: 'https://pinepods.online',
  },
  piwigo: {
    license: 'GPL-2.0',
    name: 'Piwigo',
    homepage: 'https://piwigo.org',
  },
  plumio: {
    license: 'AGPL-3.0',
    name: 'plumio',
    homepage: 'https://plumio.app',
  },
  'pocket-id': {
    license: 'BSD-2-Clause',
    name: 'pocket-id',
    homepage: 'https://pocket-id.org',
  },
  pocketbase: {
    license: 'MIT',
    name: 'pocketbase',
    homepage: 'https://pocketbase.io',
  },
  podfetch: {
    license: 'Apache-2.0',
    name: 'PodFetch',
    homepage: 'https://podfetch-docs.samtv.fyi/',
  },
  polaris: {
    license: 'MIT',
    name: 'polaris',
  },
  portainer: {
    license: 'Zlib',
    name: 'portainer',
    homepage: 'https://www.portainer.io',
  },
  postgres: {
    name: 'postgres',
    homepage: 'https://www.postgresql.org/',
  },
  prestashop: {
    name: 'PrestaShop',
    homepage: 'https://www.prestashop-project.org/',
  },
  privatebin: {
    name: 'PrivateBin',
    homepage: 'https://privatebin.info/',
  },
  projectsend: {
    license: 'GPL-2.0',
    name: 'projectsend',
    homepage: 'https://www.projectsend.org/',
  },
  prometheus: {
    license: 'Apache-2.0',
    name: 'prometheus',
    homepage: 'https://prometheus.io/',
  },
  prowlarr: {
    license: 'GPL-3.0',
    name: 'Prowlarr',
    homepage: 'https://prowlarr.com',
  },
  'pyload-ng': {
    name: 'pyload',
    homepage: 'https://pyload.net',
  },
  qbittorrent: {
    name: 'qBittorrent',
    homepage: 'https://www.qbittorrent.org',
  },
  quickshare: {
    license: 'LGPL-3.0',
    name: 'quickshare',
    homepage: 'https://ihexxa.github.io/quickshare.site',
  },
  rabbitmq: {
    name: 'rabbitmq-server',
    homepage: 'https://www.rabbitmq.com/',
  },
  radarr: {
    license: 'GPL-3.0',
    name: 'Radarr',
    homepage: 'https://radarr.video',
  },
  radicale: {
    license: 'GPL-3.0',
    name: 'Radicale',
    homepage: 'https://radicale.org',
  },
  rallly: {
    license: 'AGPL-3.0',
    name: 'rallly',
    homepage: 'https://rallly.co',
  },
  reaparr: {
    license: 'GPL-3.0',
    name: 'Reaparr',
    homepage: 'https://www.reaparr.rocks',
  },
  'receipt-wrangler': {
    name: 'receipt-wrangler',
  },
  recipya: {
    license: 'GPL-3.0',
    name: 'recipya',
    homepage: 'https://old.recipya.ca',
  },
  redaxo: {
    name: 'core',
    homepage: 'https://redaxo.org',
  },
  'redis-commander': {
    license: 'MIT',
    name: 'redis-commander',
    homepage: 'http://joeferner.github.io/redis-commander/',
  },
  redmine: {
    name: 'redmine',
    homepage: 'https://www.redmine.org',
  },
  registry: {
    license: 'Apache-2.0',
    name: 'distribution',
    homepage: 'https://distribution.github.io/distribution',
  },
  remark42: {
    license: 'MIT',
    name: 'remark42',
    homepage: 'https://remark42.com',
  },
  restreamer: {
    license: 'Apache-2.0',
    name: 'restreamer',
    homepage: 'https://docs.datarhei.com/restreamer/',
  },
  rocketchat: {
    name: 'Rocket.Chat',
    homepage: 'https://rocket.chat/',
  },
  romm: {
    license: 'AGPL-3.0',
    name: 'romm',
    homepage: 'https://romm.app',
  },
  roundcube: {
    name: 'roundcubemail',
    homepage: 'https://roundcube.net',
  },
  'rss-bridge': {
    license: 'Unlicense',
    name: 'rss-bridge',
    homepage: 'https://rss-bridge.org/bridge01/',
  },
  rundeck: {
    license: 'Apache-2.0',
    name: 'rundeck',
    homepage: 'http://rundeck.org',
  },
  sabnzbd: {
    name: 'sabnzbd',
    homepage: 'https://sabnzbd.org',
  },
  safebucket: {
    license: 'Apache-2.0',
    name: 'safebucket',
    homepage: 'https://docs.safebucket.io',
  },
  sama: {
    license: 'GPL-3.0',
    name: 'sama-server',
    homepage: 'https://samacloud.io',
  },
  'scm-manager': {
    license: 'AGPL-3.0',
    name: 'scm-manager',
    homepage: 'https://scm-manager.org',
  },
  searxng: {
    license: 'AGPL-3.0',
    name: 'searxng',
    homepage: 'https://docs.searxng.org',
  },
  seatsurfing: {
    license: 'GPL-3.0',
    name: 'seatsurfing',
    homepage: 'https://seatsurfing.io',
  },
  seaweedfs: {
    license: 'Apache-2.0',
    name: 'seaweedfs',
    homepage: 'https://seaweedfs.com',
  },
  shaarli: {
    name: 'Shaarli',
    homepage: 'https://shaarli.readthedocs.io/',
  },
  shiori: {
    license: 'MIT',
    name: 'shiori',
  },
  shipshipship: {
    license: 'Apache-2.0',
    name: 'ShipShipShip',
    homepage: 'https://shipshipship.io',
  },
  shlink: {
    license: 'MIT',
    name: 'shlink',
    homepage: 'https://shlink.io',
  },
  silverbullet: {
    license: 'MIT',
    name: 'silverbullet',
    homepage: 'https://silverbullet.md',
  },
  siyuan: {
    license: 'AGPL-3.0',
    name: 'siyuan',
    homepage: 'https://b3log.org/siyuan',
  },
  slink: {
    license: 'AGPL-3.0',
    name: 'slink',
    homepage: 'https://docs.slinkapp.io',
  },
  slskd: {
    license: 'AGPL-3.0',
    name: 'slskd',
    homepage: 'https://slskd.org',
  },
  smtp4dev: {
    license: 'BSD-3-Clause',
    name: 'smtp4dev',
  },
  snappymail: {
    license: 'AGPL-3.0',
    name: 'snappymail',
    homepage: 'https://snappymail.eu',
  },
  'snipe-it': {
    license: 'AGPL-3.0',
    name: 'snipe-it',
    homepage: 'https://snipeitapp.com',
  },
  solectrus: {
    license: 'AGPL-3.0',
    name: 'solectrus',
    homepage: 'https://solectrus.de',
  },
  sonarr: {
    license: 'GPL-3.0',
    name: 'Sonarr',
    homepage: 'https://sonarr.tv',
  },
  'speedtest-tracker': {
    license: 'MIT',
    name: 'speedtest-tracker',
    homepage: 'https://speedtest-tracker.dev/',
  },
  spegel: {
    license: 'MIT',
    name: 'spegel',
    homepage: 'https://spegel.dev',
  },
  spoolman: {
    license: 'MIT',
    name: 'Spoolman',
  },
  sqlpage: {
    license: 'MIT',
    name: 'SQLPage',
    homepage: 'https://sql-page.com',
  },
  srs: {
    license: 'MIT',
    name: 'srs',
    homepage: 'https://ossrs.io',
  },
  stash: {
    license: 'AGPL-3.0',
    name: 'stash',
    homepage: 'https://stashapp.cc/',
  },
  'static-web-server': {
    license: 'Apache-2.0',
    name: 'static-web-server',
    homepage: 'https://static-web-server.net',
  },
  'status-responder': {
    license: 'MPL-2.0',
    name: 'http-echo',
  },
  'stirling-pdf': {
    name: 'Stirling-PDF',
    homepage: 'https://stirling.com',
  },
  synapse: {
    license: 'AGPL-3.0',
    name: 'synapse',
    homepage: 'https://element-hq.github.io/synapse',
  },
  'sync-in': {
    license: 'AGPL-3.0',
    name: 'server',
    homepage: 'https://sync-in.com',
  },
  syncthing: {
    license: 'MPL-2.0',
    name: 'syncthing',
    homepage: 'https://syncthing.net/',
  },
  tachidesk: {
    license: 'MPL-2.0',
    name: 'Suwayomi-Server',
  },
  tandoor: {
    name: 'recipes',
    homepage: 'https://docs.tandoor.dev',
  },
  tautulli: {
    license: 'GPL-3.0',
    name: 'Tautulli',
    homepage: 'https://tautulli.com',
  },
  technitium: {
    license: 'GPL-3.0',
    name: 'DnsServer',
    homepage: 'https://technitium.com/dns/',
  },
  tempo: {
    license: 'AGPL-3.0',
    name: 'tempo',
    homepage: 'https://grafana.com/oss/tempo/',
  },
  teslamate: {
    license: 'AGPL-3.0',
    name: 'teslamate',
    homepage: 'https://docs.teslamate.org',
  },
  thanos: {
    license: 'Apache-2.0',
    name: 'thanos',
    homepage: 'https://thanos.io',
  },
  thelounge: {
    license: 'MIT',
    name: 'thelounge',
    homepage: 'https://thelounge.chat',
  },
  thumbor: {
    license: 'MIT',
    name: 'thumbor',
    homepage: 'http://thumbor.org',
  },
  tik: {
    name: 'tik',
    homepage: 'https://tik.projects.metio.wtf/',
  },
  tika: {
    license: 'Apache-2.0',
    name: 'tika',
    homepage: 'https://tika.apache.org/',
  },
  'tiny-tiny-rss': {
    license: 'GPL-3.0',
    name: 'tt-rss',
  },
  tinyfeed: {
    license: 'MIT',
    name: 'tinyfeed',
    homepage: 'https://feed.lovergne.dev/',
  },
  traccar: {
    license: 'Apache-2.0',
    name: 'traccar',
    homepage: 'https://www.traccar.org',
  },
  traduora: {
    license: 'AGPL-3.0',
    name: 'ever-traduora',
    homepage: 'https://traduora.co',
  },
  traggo: {
    license: 'GPL-3.0',
    name: 'server',
    homepage: 'https://traggo.net',
  },
  trailbase: {
    license: 'OSL-3.0',
    name: 'trailbase',
    homepage: 'https://trailbase.io',
  },
  transmission: {
    name: 'transmission',
    homepage: 'https://transmissionbt.com',
  },
  transmute: {
    license: 'MIT',
    name: 'transmute',
    homepage: 'https://transmute.sh',
  },
  trilium: {
    license: 'AGPL-3.0',
    name: 'Trilium',
    homepage: 'https://triliumnotes.org',
  },
  trip: {
    license: 'MIT',
    name: 'trip',
    homepage: 'https://itskovacs-trip.netlify.app/',
  },
  'tube-archivist': {
    license: 'GPL-3.0',
    name: 'tubearchivist',
    homepage: 'https://www.tubearchivist.com',
  },
  tubesync: {
    license: 'AGPL-3.0',
    name: 'tubesync',
  },
  tvheadend: {
    license: 'GPL-3.0',
    name: 'tvheadend',
    homepage: 'https://tvheadend.org',
  },
  'uptime-kuma': {
    license: 'MIT',
    name: 'uptime-kuma',
    homepage: 'https://uptime.kuma.pet',
  },
  'upvote-rss': {
    license: 'MIT',
    name: 'upvote-rss',
    homepage: 'https://www.upvote-rss.com/',
  },
  valkey: {
    license: 'BSD-3-Clause',
    name: 'valkey',
    homepage: 'https://valkey.io',
  },
  'vanilla-cookbook': {
    license: 'GPL-3.0',
    name: 'vanilla-cookbook',
  },
  vaultwarden: {
    license: 'AGPL-3.0',
    name: 'vaultwarden',
  },
  vikunja: {
    license: 'AGPL-3.0',
    name: 'vikunja',
    homepage: 'https://vikunja.io',
  },
  vince: {
    license: 'AGPL-3.0',
    name: 'vince',
    homepage: 'https://www.vinceanalytics.com/',
  },
  volsync: {
    license: 'AGPL-3.0',
    name: 'volsync',
    homepage: 'https://volsync.readthedocs.io',
  },
  'vvveb-cms': {
    license: 'AGPL-3.0',
    name: 'Vvveb',
    homepage: 'https://www.vvveb.com',
  },
  wallabag: {
    license: 'MIT',
    name: 'wallabag',
    homepage: 'https://wallabag.org',
  },
  wallos: {
    license: 'GPL-3.0',
    name: 'Wallos',
    homepage: 'https://wallosapp.com',
  },
  warpgate: {
    license: 'Apache-2.0',
    name: 'warpgate',
    homepage: 'https://warpgate.null.page',
  },
  warracker: {
    license: 'AGPL-3.0',
    name: 'Warracker',
    homepage: 'https://warracker.com',
  },
  watcharr: {
    license: 'GPL-3.0',
    name: 'Watcharr',
    homepage: 'https://watcharr.app',
  },
  wavelog: {
    license: 'MIT',
    name: 'wavelog',
    homepage: 'https://www.wavelog.org',
  },
  webtrees: {
    license: 'GPL-3.0',
    name: 'webtrees',
    homepage: 'https://webtrees.net',
  },
  wekan: {
    license: 'MIT',
    name: 'wekan',
    homepage: 'https://wekan.fi',
  },
  wetty: {
    license: 'MIT',
    name: 'wetty',
    homepage: 'https://butlerx.github.io/wetty',
  },
  wger: {
    license: 'AGPL-3.0',
    name: 'wger',
    homepage: 'https://wger.de',
  },
  whoogle: {
    license: 'MIT',
    name: 'whoogle-search',
    homepage: 'https://pypi.org/project/whoogle-search/',
  },
  'wiki-go': {
    license: 'GPL-3.0',
    name: 'wiki-go',
    homepage: 'https://wikigo.leomoon.com',
  },
  wikidocs: {
    license: 'MIT',
    name: 'WikiDocs',
    homepage: 'https://www.wikidocs.app',
  },
  wikijs: {
    license: 'AGPL-3.0',
    name: 'wiki',
    homepage: 'https://js.wiki',
  },
  wordpress: {
    name: 'WordPress',
    homepage: 'https://wordpress.org',
  },
  xbackbone: {
    license: 'Apache-2.0',
    name: 'xbackbone',
    homepage: 'http://xbackbone.app/',
  },
  xwiki: {
    license: 'LGPL-2.1',
    name: 'xwiki-platform',
    homepage: 'http://platform.xwiki.org/',
  },
  yacy: {
    name: 'yacy_search_server',
    homepage: 'http://yacy.net',
  },
  yopass: {
    license: 'Apache-2.0',
    name: 'yopass',
    homepage: 'https://yopass.se',
  },
  'your-spotify': {
    license: 'GPL-3.0',
    name: 'your_spotify',
  },
  yourls: {
    license: 'MIT',
    name: 'YOURLS',
    homepage: 'https://yourls.org',
  },
  'youtube-dl-nas': {
    license: 'MIT',
    name: 'youtube-dl-nas',
    homepage: 'https://hyeonsangjeon.github.io/youtube-dl-nas/',
  },
  'yt-dlp-web-ui': {
    license: 'GPL-3.0',
    name: 'yt-dlp-web-ui',
  },
  znc: {
    license: 'Apache-2.0',
    name: 'znc',
    homepage: 'https://znc.in/',
  },
  zoraxy: {
    license: 'AGPL-3.0',
    name: 'zoraxy',
    homepage: 'https://zoraxy.aroz.org',
  },
  'zot-oci-registry': {
    license: 'Apache-2.0',
    name: 'zot',
    homepage: 'https://zotregistry.dev',
  },
}
