// SPDX-FileCopyrightText: The kurly Authors
// SPDX-License-Identifier: 0BSD

// Generated by scripts/gen-forge.sh from each upstream repository —
// do not edit; regenerate with: gen-forge
//
// What the project's own forge says about it: the licence it detected in the
// repository, the name the repository carries, and whether it is archived. A
// workload's annotation overrides anything here; see catalog/annotations.libsonnet.
{
  '2fauth': {
    license: 'AGPL-3.0',
    name: '2FAuth',
    homepage: 'https://docs.2fauth.app/',
  },
  activepieces: {
    name: 'activepieces',
    homepage: 'https://www.activepieces.com',
  },
  actualbudget: {
    license: 'MIT',
    name: 'actual',
    homepage: 'https://actualbudget.org',
  },
  adguardhome: {
    license: 'GPL-3.0',
    name: 'AdGuardHome',
    homepage: 'https://adguard.com/adguard-home/overview.html',
  },
  adminer: {
    name: 'adminer',
    homepage: 'https://www.adminer.org/',
  },
  'airsonic-advanced': {
    license: 'GPL-3.0',
    name: 'airsonic-advanced',
  },
  alertmanager: {
    license: 'Apache-2.0',
    name: 'alertmanager',
    homepage: 'https://prometheus.io',
  },
  alist: {
    license: 'AGPL-3.0',
    name: 'alist',
    homepage: 'https://alistgo.com',
  },
  answer: {
    license: 'Apache-2.0',
    name: 'answer',
    homepage: 'https://answer.apache.org',
  },
  anythingllm: {
    license: 'MIT',
    name: 'anything-llm',
    homepage: 'https://anythingllm.com',
  },
  apprise: {
    license: 'BSD-2-Clause',
    name: 'apprise',
    homepage: 'https://hub.docker.com/r/caronc/apprise',
  },
  audiobookshelf: {
    license: 'GPL-3.0',
    name: 'audiobookshelf',
    homepage: 'https://audiobookshelf.org',
  },
  authelia: {
    license: 'Apache-2.0',
    name: 'authelia',
    homepage: 'https://www.authelia.com',
  },
  authentik: {
    name: 'authentik',
    homepage: 'https://goauthentik.io',
  },
  automatisch: {
    name: 'automatisch',
    homepage: 'https://automatisch.io',
  },
  baikal: {
    license: 'GPL-3.0',
    name: 'Baikal',
    homepage: 'https://sabre.io/baikal/',
  },
  baserow: {
    name: 'baserow',
    homepage: 'https://baserow.io',
  },
  bazarr: {
    license: 'GPL-3.0',
    name: 'bazarr',
    homepage: 'https://www.bazarr.media',
  },
  beszel: {
    license: 'MIT',
    name: 'beszel',
    homepage: 'https://beszel.dev',
  },
  bigcapital: {
    license: 'AGPL-3.0',
    name: 'bigcapital',
    homepage: 'https://bigcapital.app',
  },
  'blackbox-exporter': {
    license: 'Apache-2.0',
    name: 'blackbox_exporter',
    homepage: 'https://prometheus.io',
  },
  blinko: {
    license: 'GPL-3.0',
    name: 'blinko',
    homepage: 'https://blinko.space',
  },
  bookstack: {
    license: 'MIT',
    name: 'BookStack',
    homepage: 'https://codeberg.org/bookstack/bookstack',
  },
  browserless: {
    name: 'browserless',
    homepage: 'https://browserless.io',
  },
  bugsink: {
    name: 'bugsink',
    homepage: 'https://www.bugsink.com/',
  },
  'cal-com': {
    license: 'MIT',
    name: 'cal.diy',
    homepage: 'https://cal.diy',
  },
  calibre: {
    license: 'GPL-3.0',
    name: 'calibre',
    homepage: 'https://calibre-ebook.com',
  },
  'calibre-web': {
    license: 'GPL-3.0',
    name: 'calibre-web',
  },
  'calibre-web-automated': {
    license: 'GPL-3.0',
    name: 'Calibre-Web-Automated',
    homepage: 'https://github.com/crocodilestick/Calibre-Web-Automated',
  },
  'cassandra-cluster': {
    license: 'Apache-2.0',
    name: 'cassandra',
    homepage: 'https://cassandra.apache.org/',
  },
  changedetection: {
    license: 'Apache-2.0',
    name: 'changedetection.io',
    homepage: 'https://changedetection.io',
  },
  chatpad: {
    license: 'AGPL-3.0',
    name: 'chatpad',
    homepage: 'https://chatpad.ai',
  },
  clickhouse: {
    license: 'Apache-2.0',
    name: 'ClickHouse',
    homepage: 'https://clickhouse.com',
  },
  'cnpg-cluster': {
    name: 'postgres',
    homepage: 'https://www.postgresql.org/',
  },
  'cnpg-image-catalog': {
    name: 'postgres',
    homepage: 'https://www.postgresql.org/',
  },
  cobalt: {
    license: 'AGPL-3.0',
    name: 'cobalt',
    homepage: 'https://cobalt.tools',
  },
  'code-server': {
    license: 'MIT',
    name: 'code-server',
    homepage: 'https://coder.com',
  },
  commafeed: {
    license: 'Apache-2.0',
    name: 'commafeed',
    homepage: 'https://www.commafeed.com',
  },
  convertx: {
    license: 'AGPL-3.0',
    name: 'ConvertX',
  },
  couchdb: {
    license: 'Apache-2.0',
    name: 'couchdb',
    homepage: 'https://couchdb.apache.org/',
  },
  cryptpad: {
    license: 'AGPL-3.0',
    name: 'cryptpad',
    homepage: 'https://cryptpad.org',
  },
  cyberchef: {
    license: 'Apache-2.0',
    name: 'CyberChef',
    homepage: 'https://gchq.github.io/CyberChef',
  },
  dashy: {
    license: 'MIT',
    name: 'dashy',
    homepage: 'https://dashy.to',
  },
  davis: {
    license: 'MIT',
    name: 'davis',
    homepage: 'https://github.com/users/tchapi/projects/1/views/1',
  },
  davos: {
    license: 'MIT',
    name: 'davos',
  },
  deluge: {
    name: 'deluge',
    homepage: 'https://www.deluge-torrent.org',
  },
  dex: {
    license: 'Apache-2.0',
    name: 'dex',
    homepage: 'https://dexidp.io',
  },
  directus: {
    name: 'directus',
    homepage: 'https://directus.com',
  },
  'docker-registry-ui': {
    license: 'AGPL-3.0',
    name: 'docker-registry-ui',
    homepage: 'https://joxit.dev/docker-registry-ui/',
  },
  docmost: {
    license: 'AGPL-3.0',
    name: 'docmost',
    homepage: 'https://docmost.com',
  },
  documenso: {
    license: 'AGPL-3.0',
    name: 'documenso',
    homepage: 'https://documenso.com',
  },
  docuseal: {
    license: 'AGPL-3.0',
    name: 'docuseal',
    homepage: 'https://www.docuseal.com',
  },
  dokuwiki: {
    license: 'GPL-2.0',
    name: 'dokuwiki',
    homepage: 'http://www.dokuwiki.org',
  },
  dragonfly: {
    name: 'dragonfly',
    homepage: 'https://www.dragonflydb.io/',
  },
  'draw-io': {
    license: 'Apache-2.0',
    name: 'drawio',
    homepage: 'https://www.drawio.com',
  },
  drawio: {
    license: 'Apache-2.0',
    name: 'drawio',
    homepage: 'https://www.drawio.com',
  },
  drupal: {
    name: 'drupal',
    homepage: 'https://drupal.org/project/drupal',
  },
  duplicati: {
    name: 'duplicati',
  },
  ejabberd: {
    name: 'ejabberd',
    homepage: 'https://www.process-one.net/ejabberd/',
  },
  'element-web': {
    license: 'AGPL-3.0',
    name: 'element-web',
    homepage: 'https://element.io',
  },
  emqx: {
    name: 'emqx',
    homepage: 'https://www.emqx.com',
  },
  endurain: {
    license: 'AGPL-3.0',
    name: 'endurain',
    homepage: 'https://endurain.com',
  },
  ente: {
    license: 'AGPL-3.0',
    name: 'ente',
    homepage: 'https://ente.com',
  },
  esphome: {
    name: 'esphome',
    homepage: 'https://esphome.io/',
  },
  etherpad: {
    license: 'Apache-2.0',
    name: 'etherpad',
    homepage: 'https://etherpad.org',
  },
  excalidraw: {
    license: 'MIT',
    name: 'excalidraw',
    homepage: 'https://excalidraw.com',
  },
  expenseowl: {
    license: 'MIT',
    name: 'ExpenseOwl',
  },
  ferretdb: {
    license: 'Apache-2.0',
    name: 'FerretDB',
    homepage: 'https://www.ferretdb.com',
  },
  fider: {
    license: 'AGPL-3.0',
    name: 'fider',
    homepage: 'https://fider.io',
  },
  filebrowser: {
    license: 'Apache-2.0',
    name: 'filebrowser',
  },
  filestash: {
    license: 'AGPL-3.0',
    name: 'filestash',
    homepage: 'https://www.filestash.app/',
  },
  'firefly-iii': {
    license: 'AGPL-3.0',
    name: 'firefly-iii',
    homepage: 'https://firefly-iii.org/',
  },
  flame: {
    license: 'MIT',
    name: 'flame',
  },
  flaresolverr: {
    license: 'MIT',
    name: 'FlareSolverr',
  },
  flatnotes: {
    license: 'MIT',
    name: 'flatnotes',
  },
  focalboard: {
    name: 'focalboard',
    homepage: 'https://www.focalboard.com',
  },
  foldingathome: {
    license: 'GPL-3.0',
    name: 'fah-client-bastet',
  },
  formbricks: {
    name: 'formbricks',
    homepage: 'https://formbricks.com',
  },
  freshrss: {
    license: 'AGPL-3.0',
    name: 'FreshRSS',
    homepage: 'https://freshrss.org',
  },
  frigate: {
    license: 'MIT',
    name: 'frigate',
    homepage: 'https://frigate.video',
  },
  gatus: {
    license: 'Apache-2.0',
    name: 'gatus',
    homepage: 'https://gatus.io',
  },
  ghost: {
    license: 'MIT',
    name: 'Ghost',
    homepage: 'https://ghost.org',
  },
  ghostfolio: {
    license: 'AGPL-3.0',
    name: 'ghostfolio',
    homepage: 'https://Ghostfol.io',
  },
  gitea: {
    license: 'MIT',
    name: 'gitea',
    homepage: 'https://gitea.com',
  },
  glance: {
    license: 'AGPL-3.0',
    name: 'glance',
  },
  glitchtip: {
    license: 'mit',
    name: 'GlitchTip Backend',
  },
  gogs: {
    license: 'MIT',
    name: 'gogs',
    homepage: 'https://gogs.io',
  },
  gokapi: {
    license: 'AGPL-3.0',
    name: 'Gokapi',
  },
  gotenberg: {
    license: 'MIT',
    name: 'gotenberg',
    homepage: 'https://gotenberg.dev',
  },
  gotify: {
    name: 'server',
    homepage: 'https://gotify.net',
  },
  grafana: {
    license: 'AGPL-3.0',
    name: 'grafana',
    homepage: 'https://grafana.com',
  },
  grav: {
    license: 'MIT',
    name: 'grav',
    homepage: 'https://getgrav.org',
  },
  greenlight: {
    license: 'LGPL-3.0',
    name: 'greenlight',
  },
  grist: {
    license: 'Apache-2.0',
    name: 'grist-core',
    homepage: 'https://www.getgrist.com',
  },
  grocy: {
    license: 'MIT',
    name: 'grocy',
    homepage: 'https://grocy.info',
  },
  guacamole: {
    license: 'Apache-2.0',
    name: 'guacamole-server',
    homepage: 'https://guacamole.apache.org/',
  },
  healthchecks: {
    license: 'BSD-3-Clause',
    name: 'healthchecks',
    homepage: 'https://healthchecks.io',
  },
  hedgedoc: {
    license: 'AGPL-3.0',
    name: 'hedgedoc',
    homepage: 'https://hedgedoc.org',
  },
  heimdall: {
    license: 'MIT',
    name: 'Heimdall',
  },
  hollama: {
    license: 'MIT',
    name: 'hollama',
    homepage: 'https://hollama.fernando.is',
  },
  homarr: {
    license: 'Apache-2.0',
    name: 'homarr',
    homepage: 'https://homarr.dev',
  },
  'home-assistant': {
    license: 'Apache-2.0',
    name: 'core',
    homepage: 'https://www.home-assistant.io',
  },
  homebox: {
    license: 'AGPL-3.0',
    name: 'homebox',
    homepage: 'https://homebox.software',
  },
  homepage: {
    license: 'GPL-3.0',
    name: 'homepage',
    homepage: 'https://gethomepage.dev',
  },
  homer: {
    license: 'Apache-2.0',
    name: 'homer',
    homepage: 'https://homer-demo.netlify.app/',
  },
  immich: {
    license: 'AGPL-3.0',
    name: 'immich',
    homepage: 'https://immich.app',
  },
  influxdb: {
    license: 'Apache-2.0',
    name: 'influxdb',
    homepage: 'https://influxdata.com',
  },
  inspircd: {
    name: 'inspircd',
    homepage: 'https://www.inspircd.org',
  },
  invoiceninja: {
    name: 'invoiceninja',
    homepage: 'https://invoiceninja.com',
  },
  'it-tools': {
    license: 'GPL-3.0',
    name: 'it-tools',
    homepage: 'https://it-tools.tech',
  },
  jackett: {
    license: 'GPL-2.0',
    name: 'Jackett',
  },
  jellyfin: {
    license: 'GPL-2.0',
    name: 'jellyfin',
    homepage: 'https://jellyfin.org',
  },
  jellyseerr: {
    license: 'MIT',
    name: 'seerr',
    homepage: 'https://docs.seerr.dev',
  },
  jenkins: {
    license: 'MIT',
    name: 'jenkins',
    homepage: 'https://www.jenkins.io',
  },
  joomla: {
    license: 'GPL-2.0',
    name: 'joomla-cms',
    homepage: 'https://www.joomla.org',
  },
  joplin: {
    name: 'joplin',
    homepage: 'https://joplinapp.org',
  },
  k8up: {
    license: 'Apache-2.0',
    name: 'k8up',
    homepage: 'https://k8up.io',
  },
  kanboard: {
    license: 'MIT',
    name: 'kanboard',
    homepage: 'https://kanboard.org',
  },
  karakeep: {
    license: 'AGPL-3.0',
    name: 'karakeep',
    homepage: 'https://karakeep.app',
  },
  kavita: {
    license: 'GPL-3.0',
    name: 'Kavita',
    homepage: 'http://www.kavitareader.com',
  },
  keycloak: {
    license: 'Apache-2.0',
    name: 'keycloak',
    homepage: 'https://www.keycloak.org',
  },
  kimai: {
    license: 'AGPL-3.0',
    name: 'kimai',
    homepage: 'https://www.kimai.org',
  },
  komga: {
    license: 'MIT',
    name: 'komga',
    homepage: 'https://komga.org',
  },
  kutt: {
    license: 'MIT',
    name: 'kutt',
    homepage: 'https://kutt.to',
  },
  leantime: {
    license: 'AGPL-3.0',
    name: 'leantime',
    homepage: 'https://leantime.io',
  },
  lemmy: {
    license: 'AGPL-3.0',
    name: 'lemmy',
    homepage: 'https://join-lemmy.org',
  },
  librespeed: {
    license: 'LGPL-3.0',
    name: 'speedtest',
    homepage: 'https://librespeed.org',
  },
  lidarr: {
    license: 'GPL-3.0',
    name: 'Lidarr',
    homepage: 'http://lidarr.audio/',
  },
  linkding: {
    license: 'MIT',
    name: 'linkding',
    homepage: 'https://linkding.link/',
  },
  linkstack: {
    license: 'AGPL-3.0',
    name: 'LinkStack',
    homepage: 'https://linkstack.org',
  },
  linkwarden: {
    license: 'AGPL-3.0',
    name: 'linkwarden',
    homepage: 'https://linkwarden.app',
  },
  listmonk: {
    license: 'AGPL-3.0',
    name: 'listmonk',
    homepage: 'https://listmonk.app',
  },
  lldap: {
    license: 'GPL-3.0',
    name: 'lldap',
  },
  'lobe-chat': {
    name: 'lobehub',
    homepage: 'https://lobehub.com',
  },
  loki: {
    license: 'AGPL-3.0',
    name: 'loki',
    homepage: 'https://grafana.com/oss/loki',
  },
  lychee: {
    license: 'MIT',
    name: 'Lychee',
    homepage: 'https://lycheeorg.dev',
  },
  mailhog: {
    license: 'MIT',
    name: 'MailHog',
  },
  mailpit: {
    license: 'MIT',
    name: 'mailpit',
    homepage: 'https://mailpit.axllent.org',
  },
  mailu: {
    name: 'Mailu',
    homepage: 'https://mailu.io',
  },
  maloja: {
    license: 'GPL-3.0',
    name: 'maloja',
    homepage: 'https://maloja.krateng.ch',
  },
  mariadb: {
    license: 'GPL-2.0',
    name: 'server',
    homepage: 'https://mariadb.org',
  },
  mastodon: {
    license: 'AGPL-3.0',
    name: 'mastodon',
    homepage: 'https://joinmastodon.org',
  },
  matomo: {
    license: 'GPL-3.0',
    name: 'matomo',
    homepage: 'https://matomo.org/',
  },
  'matrix-conduit': {
    license: 'apache-2.0',
    name: 'Conduit',
  },
  mattermost: {
    name: 'mattermost',
    homepage: 'https://mattermost.com',
  },
  mautic: {
    name: 'mautic',
    homepage: 'https://www.mautic.org',
  },
  maybe: {
    license: 'AGPL-3.0',
    name: 'maybe',
    archived: true,
  },
  mazanoke: {
    license: 'GPL-3.0',
    name: 'mazanoke',
    homepage: 'https://MAZANOKE.com',
  },
  mealie: {
    license: 'AGPL-3.0',
    name: 'mealie',
    homepage: 'https://docs.mealie.io',
  },
  mediawiki: {
    name: 'mediawiki',
    homepage: 'https://www.mediawiki.org',
  },
  meilisearch: {
    name: 'meilisearch',
    homepage: 'https://www.meilisearch.com',
  },
  memcached: {
    license: 'BSD-3-Clause',
    name: 'memcached',
    homepage: 'https://memcached.org',
  },
  memos: {
    license: 'MIT',
    name: 'memos',
    homepage: 'https://usememos.com',
  },
  'mermaid-live-editor': {
    license: 'MIT',
    name: 'mermaid-live-editor',
    homepage: 'https://mermaid.live',
  },
  metabase: {
    name: 'metabase',
    homepage: 'https://metabase.com',
  },
  'metrics-server': {
    license: 'Apache-2.0',
    name: 'metrics-server',
    homepage: 'https://kubernetes.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/',
  },
  metube: {
    license: 'AGPL-3.0',
    name: 'metube',
  },
  microbin: {
    license: 'BSD-3-Clause',
    name: 'microbin',
    homepage: 'https://microbin.eu',
  },
  miniflux: {
    license: 'Apache-2.0',
    name: 'v2',
    homepage: 'https://miniflux.app',
  },
  minio: {
    license: 'AGPL-3.0',
    name: 'minio',
    archived: true,
  },
  misskey: {
    license: 'AGPL-3.0',
    name: 'misskey',
    homepage: 'https://misskey-hub.net/',
  },
  mongo: {
    name: 'mongo',
    homepage: 'https://www.mongodb.com/',
  },
  'mongo-express': {
    license: 'MIT',
    name: 'mongo-express',
  },
  'mongodb-cluster': {
    name: 'mongo',
    homepage: 'https://www.mongodb.com/',
  },
  monica: {
    license: 'AGPL-3.0',
    name: 'monica',
    homepage: 'https://beta.monicahq.com',
  },
  mosquitto: {
    name: 'mosquitto',
    homepage: 'https://mosquitto.org',
  },
  mumble: {
    name: 'mumble',
    homepage: 'https://www.mumble.info',
  },
  mylar3: {
    license: 'GPL-3.0',
    name: 'mylar3',
  },
  mysql: {
    name: 'mysql-server',
    homepage: 'http://www.mysql.com/',
  },
  'mysql-cluster': {
    name: 'mysql-server',
    homepage: 'http://www.mysql.com/',
  },
  n8n: {
    name: 'n8n',
    homepage: 'https://n8n.io',
  },
  nats: {
    license: 'Apache-2.0',
    name: 'nats-server',
    homepage: 'https://nats.io',
  },
  navidrome: {
    license: 'GPL-3.0',
    name: 'navidrome',
    homepage: 'https://www.navidrome.org',
  },
  neo4j: {
    license: 'GPL-3.0',
    name: 'neo4j',
    homepage: 'http://neo4j.com',
  },
  netbootxyz: {
    license: 'Apache-2.0',
    name: 'netboot.xyz',
    homepage: 'https://netboot.xyz',
  },
  netbox: {
    license: 'Apache-2.0',
    name: 'netbox',
    homepage: 'https://netboxlabs.com/products/netbox/',
  },
  nextcloud: {
    license: 'AGPL-3.0',
    name: 'server',
    homepage: 'https://nextcloud.com',
  },
  'nginx-proxy-manager': {
    license: 'MIT',
    name: 'nginx-proxy-manager',
    homepage: 'https://nginxproxymanager.com',
  },
  nocobase: {
    name: 'nocobase',
    homepage: 'https://www.nocobase.com',
  },
  nocodb: {
    name: 'nocodb',
    homepage: 'https://nocodb.com',
  },
  'node-red': {
    license: 'Apache-2.0',
    name: 'node-red',
    homepage: 'http://nodered.org',
  },
  ntfy: {
    license: 'Apache-2.0',
    name: 'ntfy',
    homepage: 'https://ntfy.sh',
  },
  nzbget: {
    license: 'GPL-2.0',
    name: 'nzbget',
    homepage: 'https://nzbget.com',
  },
  nzbhydra2: {
    license: 'GPL-3.0',
    name: 'nzbhydra2',
  },
  'oauth2-proxy': {
    license: 'MIT',
    name: 'oauth2-proxy',
    homepage: 'https://oauth2-proxy.github.io/oauth2-proxy',
  },
  odoo: {
    name: 'odoo',
    homepage: 'https://www.odoo.com',
  },
  ollama: {
    license: 'MIT',
    name: 'ollama',
    homepage: 'https://ollama.com',
  },
  ombi: {
    license: 'GPL-2.0',
    name: 'Ombi',
    homepage: 'http://ombi.io',
  },
  onlyoffice: {
    license: 'AGPL-3.0',
    name: 'DocumentServer',
    homepage: 'https://www.onlyoffice.com/see-it-in-action',
  },
  'open-webui': {
    name: 'open-webui',
    homepage: 'https://openwebui.com',
  },
  opencost: {
    license: 'Apache-2.0',
    name: 'opencost',
    homepage: 'http://opencost.io',
  },
  openhab: {
    license: 'EPL-2.0',
    name: 'openhab-core',
    homepage: 'https://www.openhab.org/',
  },
  openobserve: {
    license: 'AGPL-3.0',
    name: 'openobserve',
    homepage: 'https://openobserve.ai',
  },
  openproject: {
    license: 'GPL-3.0',
    name: 'openproject',
    homepage: 'https://www.openproject.org',
  },
  'opensearch-cluster': {
    license: 'Apache-2.0',
    name: 'OpenSearch',
    homepage: 'https://opensearch.org/docs/latest/opensearch/index/',
  },
  organizr: {
    license: 'GPL-3.0',
    name: 'Organizr',
  },
  'otel-collector': {
    license: 'Apache-2.0',
    name: 'opentelemetry-collector-releases',
    homepage: 'https://opentelemetry.io',
  },
  outline: {
    name: 'outline',
    homepage: 'https://www.getoutline.com',
  },
  overleaf: {
    license: 'AGPL-3.0',
    name: 'overleaf',
  },
  overseerr: {
    license: 'MIT',
    name: 'overseerr',
    homepage: 'https://overseerr.dev',
    archived: true,
  },
  owncast: {
    license: 'MIT',
    name: 'owncast',
    homepage: 'https://owncast.online',
  },
  'owntracks-recorder': {
    name: 'recorder',
  },
  pairdrop: {
    license: 'GPL-3.0',
    name: 'PairDrop',
    homepage: 'https://pairdrop.net',
  },
  paisa: {
    license: 'AGPL-3.0',
    name: 'paisa',
    homepage: 'https://paisa.fyi',
  },
  'paperless-ngx': {
    license: 'GPL-3.0',
    name: 'paperless-ngx',
    homepage: 'http://docs.paperless-ngx.com/',
  },
  passwordpusher: {
    license: 'Apache-2.0',
    name: 'PasswordPusher',
    homepage: 'https://docs.pwpush.com',
  },
  peertube: {
    license: 'AGPL-3.0',
    name: 'PeerTube',
    homepage: 'https://joinpeertube.org/',
  },
  penpot: {
    license: 'MPL-2.0',
    name: 'penpot',
    homepage: 'https://penpot.app',
  },
  pgadmin: {
    name: 'pgadmin4',
    homepage: 'https://www.pgadmin.org',
  },
  photoprism: {
    name: 'photoprism',
    homepage: 'https://www.photoprism.app',
  },
  photoview: {
    license: 'AGPL-3.0',
    name: 'photoview',
    homepage: 'https://photoview.github.io/',
  },
  phpmyadmin: {
    license: 'GPL-2.0',
    name: 'phpmyadmin',
    homepage: 'https://www.phpmyadmin.net/',
  },
  pihole: {
    name: 'pi-hole',
    homepage: 'https://pi-hole.net',
  },
  pilos: {
    license: 'LGPL-2.1',
    name: 'PILOS',
    homepage: 'https://thm-health.github.io/PILOS/',
  },
  'pingvin-share': {
    license: 'BSD-2-Clause',
    name: 'pingvin-share',
    homepage: 'https://stonith404.github.io/pingvin-share/',
    archived: true,
  },
  piwigo: {
    license: 'GPL-2.0',
    name: 'Piwigo',
    homepage: 'https://piwigo.org',
  },
  planka: {
    name: 'planka',
    homepage: 'https://planka.app',
  },
  'pocket-id': {
    license: 'BSD-2-Clause',
    name: 'pocket-id',
    homepage: 'https://pocket-id.org',
  },
  pocketbase: {
    license: 'MIT',
    name: 'pocketbase',
    homepage: 'https://pocketbase.io',
  },
  portainer: {
    license: 'Zlib',
    name: 'portainer',
    homepage: 'https://www.portainer.io',
  },
  postgres: {
    name: 'postgres',
    homepage: 'https://www.postgresql.org/',
  },
  prestashop: {
    name: 'PrestaShop',
    homepage: 'https://www.prestashop-project.org/',
  },
  privatebin: {
    name: 'PrivateBin',
    homepage: 'https://privatebin.info/',
  },
  projectsend: {
    license: 'GPL-2.0',
    name: 'projectsend',
    homepage: 'https://www.projectsend.org/',
  },
  prometheus: {
    license: 'Apache-2.0',
    name: 'prometheus',
    homepage: 'https://prometheus.io/',
  },
  prowlarr: {
    license: 'GPL-3.0',
    name: 'Prowlarr',
    homepage: 'https://prowlarr.com',
  },
  'pyload-ng': {
    name: 'pyload',
    homepage: 'https://pyload.net',
  },
  qbittorrent: {
    name: 'qBittorrent',
    homepage: 'https://www.qbittorrent.org',
  },
  qdrant: {
    license: 'Apache-2.0',
    name: 'qdrant',
    homepage: 'https://qdrant.tech',
  },
  rabbitmq: {
    name: 'rabbitmq-server',
    homepage: 'https://www.rabbitmq.com/',
  },
  radarr: {
    license: 'GPL-3.0',
    name: 'Radarr',
    homepage: 'https://radarr.video',
  },
  radicale: {
    license: 'GPL-3.0',
    name: 'Radicale',
    homepage: 'https://radicale.org',
  },
  rallly: {
    license: 'AGPL-3.0',
    name: 'rallly',
    homepage: 'https://rallly.co',
  },
  readarr: {
    license: 'GPL-3.0',
    name: 'Readarr',
    homepage: 'http://readarr.com',
    archived: true,
  },
  redis: {
    name: 'redis',
    homepage: 'http://redis.io',
  },
  'redis-commander': {
    license: 'MIT',
    name: 'redis-commander',
    homepage: 'http://joeferner.github.io/redis-commander/',
  },
  redmine: {
    name: 'redmine',
    homepage: 'https://www.redmine.org',
  },
  registry: {
    license: 'Apache-2.0',
    name: 'distribution',
    homepage: 'https://distribution.github.io/distribution',
  },
  rocketchat: {
    name: 'Rocket.Chat',
    homepage: 'https://rocket.chat/',
  },
  roundcube: {
    name: 'roundcubemail',
    homepage: 'https://roundcube.net',
  },
  'rss-bridge': {
    license: 'Unlicense',
    name: 'rss-bridge',
    homepage: 'https://rss-bridge.org/bridge01/',
  },
  rundeck: {
    license: 'Apache-2.0',
    name: 'rundeck',
    homepage: 'http://rundeck.org',
  },
  sabnzbd: {
    name: 'sabnzbd',
    homepage: 'https://sabnzbd.org',
  },
  searxng: {
    license: 'AGPL-3.0',
    name: 'searxng',
    homepage: 'https://docs.searxng.org',
  },
  seatsurfing: {
    license: 'GPL-3.0',
    name: 'seatsurfing',
    homepage: 'https://seatsurfing.io',
  },
  seaweedfs: {
    license: 'Apache-2.0',
    name: 'seaweedfs',
    homepage: 'https://seaweedfs.com',
  },
  shaarli: {
    name: 'Shaarli',
    homepage: 'https://shaarli.readthedocs.io/',
  },
  shiori: {
    license: 'MIT',
    name: 'shiori',
  },
  shlink: {
    license: 'MIT',
    name: 'shlink',
    homepage: 'https://shlink.io',
  },
  silverbullet: {
    license: 'MIT',
    name: 'silverbullet',
    homepage: 'https://silverbullet.md',
  },
  siyuan: {
    license: 'AGPL-3.0',
    name: 'siyuan',
    homepage: 'https://b3log.org/siyuan',
  },
  smtp4dev: {
    license: 'BSD-3-Clause',
    name: 'smtp4dev',
  },
  snappymail: {
    license: 'AGPL-3.0',
    name: 'snappymail',
    homepage: 'https://snappymail.eu',
  },
  'snipe-it': {
    license: 'AGPL-3.0',
    name: 'snipe-it',
    homepage: 'https://snipeitapp.com',
  },
  sonarqube: {
    license: 'LGPL-3.0',
    name: 'sonarqube',
    homepage: 'http://www.sonarqube.org',
  },
  sonarr: {
    license: 'GPL-3.0',
    name: 'Sonarr',
    homepage: 'https://sonarr.tv',
  },
  spegel: {
    license: 'MIT',
    name: 'spegel',
    homepage: 'https://spegel.dev',
  },
  'status-responder': {
    license: 'MPL-2.0',
    name: 'http-echo',
  },
  'stirling-pdf': {
    name: 'Stirling-PDF',
    homepage: 'https://stirling.com',
  },
  synapse: {
    license: 'AGPL-3.0',
    name: 'synapse',
    homepage: 'https://element-hq.github.io/synapse',
  },
  syncthing: {
    license: 'MPL-2.0',
    name: 'syncthing',
    homepage: 'https://syncthing.net/',
  },
  tachidesk: {
    license: 'MPL-2.0',
    name: 'Suwayomi-Server',
  },
  tandoor: {
    name: 'recipes',
    homepage: 'https://docs.tandoor.dev',
  },
  tautulli: {
    license: 'GPL-3.0',
    name: 'Tautulli',
    homepage: 'https://tautulli.com',
  },
  teable: {
    name: 'teable',
    homepage: 'https://teable.ai',
  },
  technitium: {
    license: 'GPL-3.0',
    name: 'DnsServer',
    homepage: 'https://technitium.com/dns/',
  },
  tempo: {
    license: 'AGPL-3.0',
    name: 'tempo',
    homepage: 'https://grafana.com/oss/tempo/',
  },
  thanos: {
    license: 'Apache-2.0',
    name: 'thanos',
    homepage: 'https://thanos.io',
  },
  thelounge: {
    license: 'MIT',
    name: 'thelounge',
    homepage: 'https://thelounge.chat',
  },
  tik: {
    name: 'tik',
  },
  tika: {
    license: 'Apache-2.0',
    name: 'tika',
    homepage: 'https://tika.apache.org/',
  },
  traccar: {
    license: 'Apache-2.0',
    name: 'traccar',
    homepage: 'https://www.traccar.org',
  },
  transmission: {
    name: 'transmission',
    homepage: 'https://transmissionbt.com',
  },
  trilium: {
    license: 'AGPL-3.0',
    name: 'Trilium',
    homepage: 'https://triliumnotes.org',
  },
  tvheadend: {
    license: 'GPL-3.0',
    name: 'tvheadend',
    homepage: 'https://tvheadend.org',
  },
  twenty: {
    name: 'twenty',
    homepage: 'https://twenty.com',
  },
  typesense: {
    license: 'GPL-3.0',
    name: 'typesense',
    homepage: 'https://typesense.org',
  },
  umami: {
    license: 'MIT',
    name: 'umami',
    homepage: 'https://umami.is',
  },
  'uptime-kuma': {
    license: 'MIT',
    name: 'uptime-kuma',
    homepage: 'https://uptime.kuma.pet',
  },
  valkey: {
    license: 'BSD-3-Clause',
    name: 'valkey',
    homepage: 'https://valkey.io',
  },
  vaultwarden: {
    license: 'AGPL-3.0',
    name: 'vaultwarden',
  },
  victoriametrics: {
    license: 'Apache-2.0',
    name: 'VictoriaMetrics',
    homepage: 'https://victoriametrics.com/',
  },
  vikunja: {
    license: 'AGPL-3.0',
    name: 'vikunja',
    homepage: 'https://vikunja.io',
  },
  volsync: {
    license: 'AGPL-3.0',
    name: 'volsync',
    homepage: 'https://volsync.readthedocs.io',
  },
  wallabag: {
    license: 'MIT',
    name: 'wallabag',
    homepage: 'https://wallabag.org',
  },
  wallos: {
    license: 'GPL-3.0',
    name: 'Wallos',
    homepage: 'https://wallosapp.com',
  },
  webtrees: {
    license: 'GPL-3.0',
    name: 'webtrees',
    homepage: 'https://webtrees.net',
  },
  wekan: {
    license: 'MIT',
    name: 'wekan',
    homepage: 'https://wekan.fi',
  },
  wger: {
    license: 'AGPL-3.0',
    name: 'wger',
    homepage: 'https://wger.de',
  },
  whoogle: {
    license: 'MIT',
    name: 'whoogle-search',
    homepage: 'https://pypi.org/project/whoogle-search/',
  },
  wikijs: {
    license: 'AGPL-3.0',
    name: 'wiki',
    homepage: 'https://js.wiki',
  },
  wordpress: {
    name: 'WordPress',
    homepage: 'https://wordpress.org',
  },
  xwiki: {
    license: 'LGPL-2.1',
    name: 'xwiki-platform',
    homepage: 'http://platform.xwiki.org/',
  },
  yourls: {
    license: 'MIT',
    name: 'YOURLS',
    homepage: 'https://yourls.org',
  },
  znc: {
    license: 'Apache-2.0',
    name: 'znc',
    homepage: 'https://znc.in/',
  },
}
