// SPDX-FileCopyrightText: The kurly Authors
// SPDX-License-Identifier: 0BSD
//
// Generated by gen-measurements — DO NOT EDIT. What each stage actually cost
// to start, measured while the e2e scenario booted it: seconds from apply to
// Ready, the highest memory reading seen on the way there, and the reading
// after it settled.
//
// MEASURED ON A KIND CLUSTER ON A DEVELOPER MACHINE. These are not production
// sizing numbers and must not be published as though they were. What carries
// over to real hardware is the shape: which workloads need far more memory to
// start than to run, which take minutes rather than seconds before they serve,
// and how they compare with one another.
//
// Each entry names the image digest it was measured on, and catalog.jsonnet
// drops the claim when the pin moves past it — a figure carried forward onto
// bits nobody ran is a guess in a field whose whole point is that it is not.
{
  '2fauth/server': { digest: 'sha256:4a1f329e42b9bdfb625db3094bd6f79a2f44640b6259d4cdb9f336c676bf120e', secondsToReady: 37, peakStartupBytes: 80060416, steadyBytes: 73039872 },
  'accent/server': { digest: 'sha256:13ba20bb667e1b2c891e489a01a75feff30abfb9ef70f2528f178f0d18b61951', secondsToReady: 21, peakStartupBytes: 258179072, steadyBytes: 315494400 },
  'activepieces/server': { digest: 'sha256:208517c4f0d798a477a0c594bf432dd0f4918433f4b6f5b5f188a6e10e638c6c', secondsToReady: 167, peakStartupBytes: 1307115520, steadyBytes: 1502883840 },
}
