// SPDX-FileCopyrightText: The kurly Authors
// SPDX-License-Identifier: 0BSD
//
// Generated by hack/smoke/deep/cr-pss.sh — DO NOT EDIT. Which Pod Security
// Standards bar the pods an OPERATOR creates clear, for the stages that render
// only a custom resource.
//
// Those stages publish `pss: null`, and that is right: PSS collapses to one
// level, and most of the standard is checked per CONTAINER, so a level computed
// from whatever pod securityContext a CRD happens to expose would be a claim
// about containers kurly never wrote. This is the answer measured instead —
// install the operator, apply the stage, and evaluate the pods it produced.
//
// A SEPARATE field from `pss` on purpose. One is derived from what kurly wrote,
// the other measured from what ran, and a consumer must be able to tell which it
// is holding. The same reason `e2e` and `delivered` are separate axes.
//
// The verdict is the WEAKEST of the stage's pods. A workload's security is the
// security of its worst pod, and reporting the best one would be choosing the
// answer we liked.
//
// ABSENT means NOT MEASURED. Never read as clean. What is absent today, and why:
//
//   cnpg-image-catalog/cluster, /namespaced   an ImageCatalog names images for
//       other clusters to run. It creates no pod, ever, so there is nothing to
//       measure rather than something that went unmeasured.
//   k8up/backup, /schedule                    a Backup runs when its schedule
//       fires and a Schedule only creates one then; neither produces a pod
//       inside the window this sweep waits. k8up/restore does, and is measured.
//   volsync/backup, /restore                  the mover pod appears when the
//       trigger fires, on the same footing.
//   tempo/server                              the operator accepted the CR and
//       produced no pod in the window.
//   cassandra-cluster/cluster                 cass-operator installs and then
//       waits on a webhook certificate that never arrives, so its CRD is absent
//       and the stage is rejected.
//   keycloak/server, loki/server,
//   opensearch-cluster/cluster                their operators are not installed
//       by cr-bsi-operators.sh — loki needs a development overlay and pinned
//       image, opensearch's manifest pulls an image that no longer exists.
//
// The first six are "there is no pod to look at", which will not change by
// waiting longer. The last four are "we could not ask", which would.
{
  'alertmanager/server': { pods: 1, level: 'restricted', violates: [] },
  'cnpg-cluster/cluster': { pods: 1, level: 'restricted', violates: [] },
  'k8up/restore': { pods: 1, level: 'baseline', violates: ['allowPrivilegeEscalation', 'runAsNonRoot', 'seccompProfile', 'capabilities'] },
  'mysql-cluster/cluster': { pods: 3, level: 'baseline', violates: ['runAsNonRoot', 'runAsUser', 'seccompProfile', 'capabilities'] },
  'prometheus/server': { pods: 1, level: 'restricted', violates: [] },
  'thanos/ruler': { pods: 1, level: 'restricted', violates: [] },
}
