// SPDX-FileCopyrightText: The kurly Authors
// SPDX-License-Identifier: 0BSD

// Generated by scripts/gen-spdx.sh from the SPDX licence list version 3.28.0 —
// do not edit; regenerate with: gen-spdx
//
// Every identifier SPDX knows, with whether it is OSI-approved and whether
// SPDX has deprecated the spelling. catalog.jsonnet rejects any licence value
// that is not a key here, so a label stating a project name or a misspelled
// identifier fails the build instead of being published as a licence.
{
  '0BSD': {
    deprecated: false,
    osiApproved: true,
  },
  '3D-Slicer-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  AAL: {
    deprecated: false,
    osiApproved: true,
  },
  ADSL: {
    deprecated: false,
    osiApproved: false,
  },
  'AFL-1.1': {
    deprecated: false,
    osiApproved: true,
  },
  'AFL-1.2': {
    deprecated: false,
    osiApproved: true,
  },
  'AFL-2.0': {
    deprecated: false,
    osiApproved: true,
  },
  'AFL-2.1': {
    deprecated: false,
    osiApproved: true,
  },
  'AFL-3.0': {
    deprecated: false,
    osiApproved: true,
  },
  'AGPL-1.0': {
    deprecated: true,
    osiApproved: false,
  },
  'AGPL-1.0-only': {
    deprecated: false,
    osiApproved: false,
  },
  'AGPL-1.0-or-later': {
    deprecated: false,
    osiApproved: false,
  },
  'AGPL-3.0': {
    deprecated: true,
    osiApproved: true,
  },
  'AGPL-3.0-only': {
    deprecated: false,
    osiApproved: true,
  },
  'AGPL-3.0-or-later': {
    deprecated: false,
    osiApproved: true,
  },
  'ALGLIB-Documentation': {
    deprecated: false,
    osiApproved: true,
  },
  'AMD-newlib': {
    deprecated: false,
    osiApproved: false,
  },
  AMDPLPA: {
    deprecated: false,
    osiApproved: false,
  },
  AML: {
    deprecated: false,
    osiApproved: false,
  },
  'AML-glslang': {
    deprecated: false,
    osiApproved: false,
  },
  AMPAS: {
    deprecated: false,
    osiApproved: false,
  },
  'ANTLR-PD': {
    deprecated: false,
    osiApproved: false,
  },
  'ANTLR-PD-fallback': {
    deprecated: false,
    osiApproved: false,
  },
  APAFML: {
    deprecated: false,
    osiApproved: false,
  },
  'APL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'APSL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'APSL-1.1': {
    deprecated: false,
    osiApproved: true,
  },
  'APSL-1.2': {
    deprecated: false,
    osiApproved: true,
  },
  'APSL-2.0': {
    deprecated: false,
    osiApproved: true,
  },
  'ASWF-Digital-Assets-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'ASWF-Digital-Assets-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  Abstyles: {
    deprecated: false,
    osiApproved: false,
  },
  'AdaCore-doc': {
    deprecated: false,
    osiApproved: false,
  },
  'Adobe-2006': {
    deprecated: false,
    osiApproved: false,
  },
  'Adobe-Display-PostScript': {
    deprecated: false,
    osiApproved: false,
  },
  'Adobe-Glyph': {
    deprecated: false,
    osiApproved: false,
  },
  'Adobe-Utopia': {
    deprecated: false,
    osiApproved: false,
  },
  'Advanced-Cryptics-Dictionary': {
    deprecated: false,
    osiApproved: false,
  },
  Afmparse: {
    deprecated: false,
    osiApproved: false,
  },
  Aladdin: {
    deprecated: false,
    osiApproved: false,
  },
  'Apache-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'Apache-1.1': {
    deprecated: false,
    osiApproved: true,
  },
  'Apache-2.0': {
    deprecated: false,
    osiApproved: true,
  },
  'App-s2p': {
    deprecated: false,
    osiApproved: false,
  },
  'Arphic-1999': {
    deprecated: false,
    osiApproved: false,
  },
  'Artistic-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'Artistic-1.0-Perl': {
    deprecated: false,
    osiApproved: true,
  },
  'Artistic-1.0-cl8': {
    deprecated: false,
    osiApproved: true,
  },
  'Artistic-2.0': {
    deprecated: false,
    osiApproved: true,
  },
  'Artistic-dist': {
    deprecated: false,
    osiApproved: false,
  },
  'Aspell-RU': {
    deprecated: false,
    osiApproved: false,
  },
  'BOLA-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-1-Clause': {
    deprecated: false,
    osiApproved: true,
  },
  'BSD-2-Clause': {
    deprecated: false,
    osiApproved: true,
  },
  'BSD-2-Clause-Darwin': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-2-Clause-FreeBSD': {
    deprecated: true,
    osiApproved: false,
  },
  'BSD-2-Clause-NetBSD': {
    deprecated: true,
    osiApproved: false,
  },
  'BSD-2-Clause-Patent': {
    deprecated: false,
    osiApproved: true,
  },
  'BSD-2-Clause-Views': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-2-Clause-first-lines': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-2-Clause-pkgconf-disclaimer': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-3-Clause': {
    deprecated: false,
    osiApproved: true,
  },
  'BSD-3-Clause-Attribution': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-3-Clause-Clear': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-3-Clause-HP': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-3-Clause-LBNL': {
    deprecated: false,
    osiApproved: true,
  },
  'BSD-3-Clause-Modification': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-3-Clause-No-Military-License': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-3-Clause-No-Nuclear-License': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-3-Clause-No-Nuclear-License-2014': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-3-Clause-No-Nuclear-Warranty': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-3-Clause-Open-MPI': {
    deprecated: false,
    osiApproved: true,
  },
  'BSD-3-Clause-Sun': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-3-Clause-Tso': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-3-Clause-acpica': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-3-Clause-flex': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-4-Clause': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-4-Clause-Shortened': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-4-Clause-UC': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-4.3RENO': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-4.3TAHOE': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-Advertising-Acknowledgement': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-Attribution-HPND-disclaimer': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-Inferno-Nettverk': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-Mark-Modifications': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-Protection': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-Source-Code': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-Source-beginning-file': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-Systemics': {
    deprecated: false,
    osiApproved: false,
  },
  'BSD-Systemics-W3Works': {
    deprecated: false,
    osiApproved: false,
  },
  'BSL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'BUSL-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  Baekmuk: {
    deprecated: false,
    osiApproved: false,
  },
  Bahyph: {
    deprecated: false,
    osiApproved: false,
  },
  Barr: {
    deprecated: false,
    osiApproved: false,
  },
  Beerware: {
    deprecated: false,
    osiApproved: false,
  },
  'BitTorrent-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'BitTorrent-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  'Bitstream-Charter': {
    deprecated: false,
    osiApproved: false,
  },
  'Bitstream-Vera': {
    deprecated: false,
    osiApproved: false,
  },
  'BlueOak-1.0.0': {
    deprecated: false,
    osiApproved: true,
  },
  'Boehm-GC': {
    deprecated: false,
    osiApproved: false,
  },
  'Boehm-GC-without-fee': {
    deprecated: false,
    osiApproved: false,
  },
  Borceux: {
    deprecated: false,
    osiApproved: false,
  },
  'Brian-Gladman-2-Clause': {
    deprecated: false,
    osiApproved: false,
  },
  'Brian-Gladman-3-Clause': {
    deprecated: false,
    osiApproved: false,
  },
  Buddy: {
    deprecated: false,
    osiApproved: false,
  },
  'C-UDA-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CAL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'CAL-1.0-Combined-Work-Exception': {
    deprecated: false,
    osiApproved: true,
  },
  'CAPEC-tou': {
    deprecated: false,
    osiApproved: false,
  },
  'CATOSL-1.1': {
    deprecated: false,
    osiApproved: true,
  },
  'CC-BY-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-2.5': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-2.5-AU': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-3.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-3.0-AT': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-3.0-AU': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-3.0-DE': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-3.0-IGO': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-3.0-NL': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-3.0-US': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-4.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-2.5': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-3.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-3.0-DE': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-4.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-ND-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-ND-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-ND-2.5': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-ND-3.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-ND-3.0-DE': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-ND-3.0-IGO': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-ND-4.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-SA-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-SA-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-SA-2.0-DE': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-SA-2.0-FR': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-SA-2.0-UK': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-SA-2.5': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-SA-3.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-SA-3.0-DE': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-SA-3.0-IGO': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-NC-SA-4.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-ND-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-ND-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-ND-2.5': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-ND-3.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-ND-3.0-DE': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-ND-4.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-SA-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-SA-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-SA-2.0-UK': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-SA-2.1-JP': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-SA-2.5': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-SA-3.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-SA-3.0-AT': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-SA-3.0-DE': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-SA-3.0-IGO': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-BY-SA-4.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-PDDC': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-PDM-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC-SA-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CC0-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CDDL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'CDDL-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  'CDL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CDLA-Permissive-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CDLA-Permissive-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CDLA-Sharing-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CECILL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CECILL-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  'CECILL-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CECILL-2.1': {
    deprecated: false,
    osiApproved: true,
  },
  'CECILL-B': {
    deprecated: false,
    osiApproved: false,
  },
  'CECILL-C': {
    deprecated: false,
    osiApproved: false,
  },
  'CERN-OHL-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  'CERN-OHL-1.2': {
    deprecated: false,
    osiApproved: false,
  },
  'CERN-OHL-P-2.0': {
    deprecated: false,
    osiApproved: true,
  },
  'CERN-OHL-S-2.0': {
    deprecated: false,
    osiApproved: true,
  },
  'CERN-OHL-W-2.0': {
    deprecated: false,
    osiApproved: true,
  },
  CFITSIO: {
    deprecated: false,
    osiApproved: false,
  },
  'CMU-Mach': {
    deprecated: false,
    osiApproved: false,
  },
  'CMU-Mach-nodoc': {
    deprecated: false,
    osiApproved: false,
  },
  'CNRI-Jython': {
    deprecated: false,
    osiApproved: false,
  },
  'CNRI-Python': {
    deprecated: false,
    osiApproved: true,
  },
  'CNRI-Python-GPL-Compatible': {
    deprecated: false,
    osiApproved: false,
  },
  'COIL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'CPAL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'CPL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'CPOL-1.02': {
    deprecated: false,
    osiApproved: false,
  },
  'CUA-OPL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  Caldera: {
    deprecated: false,
    osiApproved: false,
  },
  'Caldera-no-preamble': {
    deprecated: false,
    osiApproved: false,
  },
  Catharon: {
    deprecated: false,
    osiApproved: false,
  },
  ClArtistic: {
    deprecated: false,
    osiApproved: false,
  },
  Clips: {
    deprecated: false,
    osiApproved: false,
  },
  'Community-Spec-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'Condor-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  'Cornell-Lossless-JPEG': {
    deprecated: false,
    osiApproved: false,
  },
  Cronyx: {
    deprecated: false,
    osiApproved: false,
  },
  Crossword: {
    deprecated: false,
    osiApproved: false,
  },
  CryptoSwift: {
    deprecated: false,
    osiApproved: false,
  },
  CrystalStacker: {
    deprecated: false,
    osiApproved: false,
  },
  Cube: {
    deprecated: false,
    osiApproved: false,
  },
  'D-FSL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'DEC-3-Clause': {
    deprecated: false,
    osiApproved: false,
  },
  'DL-DE-BY-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  'DL-DE-ZERO-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  DOC: {
    deprecated: false,
    osiApproved: false,
  },
  'DRL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'DRL-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  DSDP: {
    deprecated: false,
    osiApproved: false,
  },
  'DocBook-DTD': {
    deprecated: false,
    osiApproved: false,
  },
  'DocBook-Schema': {
    deprecated: false,
    osiApproved: false,
  },
  'DocBook-Stylesheet': {
    deprecated: false,
    osiApproved: false,
  },
  'DocBook-XML': {
    deprecated: false,
    osiApproved: false,
  },
  Dotseqn: {
    deprecated: false,
    osiApproved: false,
  },
  'ECL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'ECL-2.0': {
    deprecated: false,
    osiApproved: true,
  },
  'EFL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'EFL-2.0': {
    deprecated: false,
    osiApproved: true,
  },
  EPICS: {
    deprecated: false,
    osiApproved: false,
  },
  'EPL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'EPL-2.0': {
    deprecated: false,
    osiApproved: true,
  },
  'ESA-PL-permissive-2.4': {
    deprecated: false,
    osiApproved: false,
  },
  'ESA-PL-strong-copyleft-2.4': {
    deprecated: false,
    osiApproved: false,
  },
  'ESA-PL-weak-copyleft-2.4': {
    deprecated: false,
    osiApproved: false,
  },
  EUDatagrid: {
    deprecated: false,
    osiApproved: true,
  },
  'EUPL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'EUPL-1.1': {
    deprecated: false,
    osiApproved: true,
  },
  'EUPL-1.2': {
    deprecated: false,
    osiApproved: true,
  },
  'Elastic-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  Entessa: {
    deprecated: false,
    osiApproved: true,
  },
  'ErlPL-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  Eurosym: {
    deprecated: false,
    osiApproved: false,
  },
  FBM: {
    deprecated: false,
    osiApproved: false,
  },
  'FDK-AAC': {
    deprecated: false,
    osiApproved: false,
  },
  FSFAP: {
    deprecated: false,
    osiApproved: false,
  },
  'FSFAP-no-warranty-disclaimer': {
    deprecated: false,
    osiApproved: false,
  },
  FSFUL: {
    deprecated: false,
    osiApproved: false,
  },
  FSFULLR: {
    deprecated: false,
    osiApproved: false,
  },
  FSFULLRSD: {
    deprecated: false,
    osiApproved: false,
  },
  FSFULLRWD: {
    deprecated: false,
    osiApproved: false,
  },
  'FSL-1.1-ALv2': {
    deprecated: false,
    osiApproved: false,
  },
  'FSL-1.1-MIT': {
    deprecated: false,
    osiApproved: false,
  },
  FTL: {
    deprecated: false,
    osiApproved: false,
  },
  Fair: {
    deprecated: false,
    osiApproved: true,
  },
  'Ferguson-Twofish': {
    deprecated: false,
    osiApproved: false,
  },
  'Frameworx-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'FreeBSD-DOC': {
    deprecated: false,
    osiApproved: false,
  },
  FreeImage: {
    deprecated: false,
    osiApproved: false,
  },
  Furuseth: {
    deprecated: false,
    osiApproved: false,
  },
  'GCR-docs': {
    deprecated: false,
    osiApproved: false,
  },
  GD: {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.1': {
    deprecated: true,
    osiApproved: false,
  },
  'GFDL-1.1-invariants-only': {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.1-invariants-or-later': {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.1-no-invariants-only': {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.1-no-invariants-or-later': {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.1-only': {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.1-or-later': {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.2': {
    deprecated: true,
    osiApproved: false,
  },
  'GFDL-1.2-invariants-only': {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.2-invariants-or-later': {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.2-no-invariants-only': {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.2-no-invariants-or-later': {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.2-only': {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.2-or-later': {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.3': {
    deprecated: true,
    osiApproved: false,
  },
  'GFDL-1.3-invariants-only': {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.3-invariants-or-later': {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.3-no-invariants-only': {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.3-no-invariants-or-later': {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.3-only': {
    deprecated: false,
    osiApproved: false,
  },
  'GFDL-1.3-or-later': {
    deprecated: false,
    osiApproved: false,
  },
  GL2PS: {
    deprecated: false,
    osiApproved: false,
  },
  GLWTPL: {
    deprecated: false,
    osiApproved: false,
  },
  'GPL-1.0': {
    deprecated: true,
    osiApproved: false,
  },
  'GPL-1.0+': {
    deprecated: true,
    osiApproved: false,
  },
  'GPL-1.0-only': {
    deprecated: false,
    osiApproved: false,
  },
  'GPL-1.0-or-later': {
    deprecated: false,
    osiApproved: false,
  },
  'GPL-2.0': {
    deprecated: true,
    osiApproved: true,
  },
  'GPL-2.0+': {
    deprecated: true,
    osiApproved: true,
  },
  'GPL-2.0-only': {
    deprecated: false,
    osiApproved: true,
  },
  'GPL-2.0-or-later': {
    deprecated: false,
    osiApproved: true,
  },
  'GPL-2.0-with-GCC-exception': {
    deprecated: true,
    osiApproved: false,
  },
  'GPL-2.0-with-autoconf-exception': {
    deprecated: true,
    osiApproved: false,
  },
  'GPL-2.0-with-bison-exception': {
    deprecated: true,
    osiApproved: false,
  },
  'GPL-2.0-with-classpath-exception': {
    deprecated: true,
    osiApproved: false,
  },
  'GPL-2.0-with-font-exception': {
    deprecated: true,
    osiApproved: false,
  },
  'GPL-3.0': {
    deprecated: true,
    osiApproved: true,
  },
  'GPL-3.0+': {
    deprecated: true,
    osiApproved: true,
  },
  'GPL-3.0-only': {
    deprecated: false,
    osiApproved: true,
  },
  'GPL-3.0-or-later': {
    deprecated: false,
    osiApproved: true,
  },
  'GPL-3.0-with-GCC-exception': {
    deprecated: true,
    osiApproved: true,
  },
  'GPL-3.0-with-autoconf-exception': {
    deprecated: true,
    osiApproved: false,
  },
  'Game-Programming-Gems': {
    deprecated: false,
    osiApproved: false,
  },
  Giftware: {
    deprecated: false,
    osiApproved: false,
  },
  Glide: {
    deprecated: false,
    osiApproved: false,
  },
  Glulxe: {
    deprecated: false,
    osiApproved: false,
  },
  'Graphics-Gems': {
    deprecated: false,
    osiApproved: false,
  },
  Gutmann: {
    deprecated: false,
    osiApproved: false,
  },
  HDF5: {
    deprecated: false,
    osiApproved: false,
  },
  HIDAPI: {
    deprecated: false,
    osiApproved: false,
  },
  'HP-1986': {
    deprecated: false,
    osiApproved: false,
  },
  'HP-1989': {
    deprecated: false,
    osiApproved: false,
  },
  HPND: {
    deprecated: false,
    osiApproved: true,
  },
  'HPND-DEC': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-Fenneberg-Livingston': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-INRIA-IMAG': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-Intel': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-Kevlin-Henney': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-MIT-disclaimer': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-Markus-Kuhn': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-Netrek': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-Pbmplus': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-SMC': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-UC': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-UC-export-US': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-doc': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-doc-sell': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-export-US': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-export-US-acknowledgement': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-export-US-modify': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-export2-US': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-merchantability-variant': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-sell-MIT-disclaimer-xserver': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-sell-regexpr': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-sell-variant': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-sell-variant-MIT-disclaimer': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-sell-variant-MIT-disclaimer-rev': {
    deprecated: false,
    osiApproved: false,
  },
  'HPND-sell-variant-critical-systems': {
    deprecated: false,
    osiApproved: false,
  },
  HTMLTIDY: {
    deprecated: false,
    osiApproved: false,
  },
  HaskellReport: {
    deprecated: false,
    osiApproved: false,
  },
  'Hippocratic-2.1': {
    deprecated: false,
    osiApproved: false,
  },
  'IBM-pibs': {
    deprecated: false,
    osiApproved: false,
  },
  ICU: {
    deprecated: false,
    osiApproved: true,
  },
  'IEC-Code-Components-EULA': {
    deprecated: false,
    osiApproved: false,
  },
  IJG: {
    deprecated: false,
    osiApproved: false,
  },
  'IJG-short': {
    deprecated: false,
    osiApproved: false,
  },
  IPA: {
    deprecated: false,
    osiApproved: true,
  },
  'IPL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  ISC: {
    deprecated: false,
    osiApproved: true,
  },
  'ISC-Veillard': {
    deprecated: false,
    osiApproved: false,
  },
  'ISO-permission': {
    deprecated: false,
    osiApproved: false,
  },
  ImageMagick: {
    deprecated: false,
    osiApproved: false,
  },
  Imlib2: {
    deprecated: false,
    osiApproved: false,
  },
  'Info-ZIP': {
    deprecated: false,
    osiApproved: false,
  },
  'Inner-Net-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  InnoSetup: {
    deprecated: false,
    osiApproved: false,
  },
  Intel: {
    deprecated: false,
    osiApproved: true,
  },
  'Intel-ACPI': {
    deprecated: false,
    osiApproved: false,
  },
  'Interbase-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'JPL-image': {
    deprecated: false,
    osiApproved: false,
  },
  JPNIC: {
    deprecated: false,
    osiApproved: false,
  },
  JSON: {
    deprecated: false,
    osiApproved: false,
  },
  Jam: {
    deprecated: false,
    osiApproved: true,
  },
  'JasPer-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  Kastrup: {
    deprecated: false,
    osiApproved: false,
  },
  Kazlib: {
    deprecated: false,
    osiApproved: false,
  },
  'Knuth-CTAN': {
    deprecated: false,
    osiApproved: false,
  },
  'LAL-1.2': {
    deprecated: false,
    osiApproved: false,
  },
  'LAL-1.3': {
    deprecated: false,
    osiApproved: false,
  },
  'LGPL-2.0': {
    deprecated: true,
    osiApproved: true,
  },
  'LGPL-2.0+': {
    deprecated: true,
    osiApproved: true,
  },
  'LGPL-2.0-only': {
    deprecated: false,
    osiApproved: true,
  },
  'LGPL-2.0-or-later': {
    deprecated: false,
    osiApproved: true,
  },
  'LGPL-2.1': {
    deprecated: true,
    osiApproved: true,
  },
  'LGPL-2.1+': {
    deprecated: true,
    osiApproved: true,
  },
  'LGPL-2.1-only': {
    deprecated: false,
    osiApproved: true,
  },
  'LGPL-2.1-or-later': {
    deprecated: false,
    osiApproved: true,
  },
  'LGPL-3.0': {
    deprecated: true,
    osiApproved: true,
  },
  'LGPL-3.0+': {
    deprecated: true,
    osiApproved: true,
  },
  'LGPL-3.0-only': {
    deprecated: false,
    osiApproved: true,
  },
  'LGPL-3.0-or-later': {
    deprecated: false,
    osiApproved: true,
  },
  LGPLLR: {
    deprecated: false,
    osiApproved: false,
  },
  LOOP: {
    deprecated: false,
    osiApproved: false,
  },
  'LPD-document': {
    deprecated: false,
    osiApproved: false,
  },
  'LPL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'LPL-1.02': {
    deprecated: false,
    osiApproved: true,
  },
  'LPPL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'LPPL-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  'LPPL-1.2': {
    deprecated: false,
    osiApproved: false,
  },
  'LPPL-1.3a': {
    deprecated: false,
    osiApproved: false,
  },
  'LPPL-1.3c': {
    deprecated: false,
    osiApproved: true,
  },
  'LZMA-SDK-9.11-to-9.20': {
    deprecated: false,
    osiApproved: false,
  },
  'LZMA-SDK-9.22': {
    deprecated: false,
    osiApproved: false,
  },
  Latex2e: {
    deprecated: false,
    osiApproved: false,
  },
  'Latex2e-translated-notice': {
    deprecated: false,
    osiApproved: false,
  },
  Leptonica: {
    deprecated: false,
    osiApproved: false,
  },
  'LiLiQ-P-1.1': {
    deprecated: false,
    osiApproved: true,
  },
  'LiLiQ-R-1.1': {
    deprecated: false,
    osiApproved: true,
  },
  'LiLiQ-Rplus-1.1': {
    deprecated: false,
    osiApproved: true,
  },
  Libpng: {
    deprecated: false,
    osiApproved: false,
  },
  'Linux-OpenIB': {
    deprecated: false,
    osiApproved: false,
  },
  'Linux-man-pages-1-para': {
    deprecated: false,
    osiApproved: false,
  },
  'Linux-man-pages-copyleft': {
    deprecated: false,
    osiApproved: false,
  },
  'Linux-man-pages-copyleft-2-para': {
    deprecated: false,
    osiApproved: false,
  },
  'Linux-man-pages-copyleft-var': {
    deprecated: false,
    osiApproved: false,
  },
  'Lucida-Bitmap-Fonts': {
    deprecated: false,
    osiApproved: false,
  },
  MIPS: {
    deprecated: false,
    osiApproved: false,
  },
  MIT: {
    deprecated: false,
    osiApproved: true,
  },
  'MIT-0': {
    deprecated: false,
    osiApproved: true,
  },
  'MIT-CMU': {
    deprecated: false,
    osiApproved: false,
  },
  'MIT-Click': {
    deprecated: false,
    osiApproved: false,
  },
  'MIT-Festival': {
    deprecated: false,
    osiApproved: false,
  },
  'MIT-Khronos-old': {
    deprecated: false,
    osiApproved: false,
  },
  'MIT-Modern-Variant': {
    deprecated: false,
    osiApproved: true,
  },
  'MIT-STK': {
    deprecated: false,
    osiApproved: false,
  },
  'MIT-Wu': {
    deprecated: false,
    osiApproved: false,
  },
  'MIT-advertising': {
    deprecated: false,
    osiApproved: false,
  },
  'MIT-enna': {
    deprecated: false,
    osiApproved: false,
  },
  'MIT-feh': {
    deprecated: false,
    osiApproved: false,
  },
  'MIT-open-group': {
    deprecated: false,
    osiApproved: false,
  },
  'MIT-testregex': {
    deprecated: false,
    osiApproved: false,
  },
  MITNFA: {
    deprecated: false,
    osiApproved: false,
  },
  MMIXware: {
    deprecated: false,
    osiApproved: false,
  },
  'MMPL-1.0.1': {
    deprecated: false,
    osiApproved: false,
  },
  'MPEG-SSG': {
    deprecated: false,
    osiApproved: false,
  },
  'MPL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'MPL-1.1': {
    deprecated: false,
    osiApproved: true,
  },
  'MPL-2.0': {
    deprecated: false,
    osiApproved: true,
  },
  'MPL-2.0-no-copyleft-exception': {
    deprecated: false,
    osiApproved: true,
  },
  'MS-LPL': {
    deprecated: false,
    osiApproved: false,
  },
  'MS-PL': {
    deprecated: false,
    osiApproved: true,
  },
  'MS-RL': {
    deprecated: false,
    osiApproved: true,
  },
  MTLL: {
    deprecated: false,
    osiApproved: false,
  },
  'Mackerras-3-Clause': {
    deprecated: false,
    osiApproved: false,
  },
  'Mackerras-3-Clause-acknowledgment': {
    deprecated: false,
    osiApproved: false,
  },
  MakeIndex: {
    deprecated: false,
    osiApproved: false,
  },
  'Martin-Birgmeier': {
    deprecated: false,
    osiApproved: false,
  },
  'McPhee-slideshow': {
    deprecated: false,
    osiApproved: false,
  },
  Minpack: {
    deprecated: false,
    osiApproved: false,
  },
  MirOS: {
    deprecated: false,
    osiApproved: true,
  },
  Motosoto: {
    deprecated: false,
    osiApproved: true,
  },
  'MulanPSL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'MulanPSL-2.0': {
    deprecated: false,
    osiApproved: true,
  },
  Multics: {
    deprecated: false,
    osiApproved: true,
  },
  Mup: {
    deprecated: false,
    osiApproved: false,
  },
  'NAIST-2003': {
    deprecated: false,
    osiApproved: false,
  },
  'NASA-1.3': {
    deprecated: false,
    osiApproved: true,
  },
  'NBPL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'NCBI-PD': {
    deprecated: false,
    osiApproved: false,
  },
  'NCGL-UK-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  NCL: {
    deprecated: false,
    osiApproved: false,
  },
  NCSA: {
    deprecated: false,
    osiApproved: true,
  },
  NGPL: {
    deprecated: false,
    osiApproved: true,
  },
  'NICTA-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'NIST-PD': {
    deprecated: false,
    osiApproved: false,
  },
  'NIST-PD-TNT': {
    deprecated: false,
    osiApproved: false,
  },
  'NIST-PD-fallback': {
    deprecated: false,
    osiApproved: false,
  },
  'NIST-Software': {
    deprecated: false,
    osiApproved: false,
  },
  'NLOD-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'NLOD-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  NLPL: {
    deprecated: false,
    osiApproved: false,
  },
  NOSL: {
    deprecated: false,
    osiApproved: false,
  },
  'NPL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'NPL-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  'NPOSL-3.0': {
    deprecated: false,
    osiApproved: true,
  },
  NRL: {
    deprecated: false,
    osiApproved: false,
  },
  'NTIA-PD': {
    deprecated: false,
    osiApproved: false,
  },
  NTP: {
    deprecated: false,
    osiApproved: true,
  },
  'NTP-0': {
    deprecated: false,
    osiApproved: false,
  },
  Naumen: {
    deprecated: false,
    osiApproved: true,
  },
  'Net-SNMP': {
    deprecated: true,
    osiApproved: false,
  },
  NetCDF: {
    deprecated: false,
    osiApproved: false,
  },
  Newsletr: {
    deprecated: false,
    osiApproved: false,
  },
  Nokia: {
    deprecated: false,
    osiApproved: true,
  },
  Noweb: {
    deprecated: false,
    osiApproved: false,
  },
  Nunit: {
    deprecated: true,
    osiApproved: false,
  },
  'O-UDA-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  OAR: {
    deprecated: false,
    osiApproved: false,
  },
  'OCCT-PL': {
    deprecated: false,
    osiApproved: false,
  },
  'OCLC-2.0': {
    deprecated: false,
    osiApproved: true,
  },
  'ODC-By-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'ODbL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  OFFIS: {
    deprecated: false,
    osiApproved: false,
  },
  'OFL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'OFL-1.0-RFN': {
    deprecated: false,
    osiApproved: false,
  },
  'OFL-1.0-no-RFN': {
    deprecated: false,
    osiApproved: false,
  },
  'OFL-1.1': {
    deprecated: false,
    osiApproved: true,
  },
  'OFL-1.1-RFN': {
    deprecated: false,
    osiApproved: true,
  },
  'OFL-1.1-no-RFN': {
    deprecated: false,
    osiApproved: true,
  },
  'OGC-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'OGDL-Taiwan-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'OGL-Canada-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  'OGL-UK-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'OGL-UK-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  'OGL-UK-3.0': {
    deprecated: false,
    osiApproved: false,
  },
  OGTSL: {
    deprecated: false,
    osiApproved: true,
  },
  'OLDAP-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  'OLDAP-1.2': {
    deprecated: false,
    osiApproved: false,
  },
  'OLDAP-1.3': {
    deprecated: false,
    osiApproved: false,
  },
  'OLDAP-1.4': {
    deprecated: false,
    osiApproved: false,
  },
  'OLDAP-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  'OLDAP-2.0.1': {
    deprecated: false,
    osiApproved: false,
  },
  'OLDAP-2.1': {
    deprecated: false,
    osiApproved: false,
  },
  'OLDAP-2.2': {
    deprecated: false,
    osiApproved: false,
  },
  'OLDAP-2.2.1': {
    deprecated: false,
    osiApproved: false,
  },
  'OLDAP-2.2.2': {
    deprecated: false,
    osiApproved: false,
  },
  'OLDAP-2.3': {
    deprecated: false,
    osiApproved: false,
  },
  'OLDAP-2.4': {
    deprecated: false,
    osiApproved: false,
  },
  'OLDAP-2.5': {
    deprecated: false,
    osiApproved: false,
  },
  'OLDAP-2.6': {
    deprecated: false,
    osiApproved: false,
  },
  'OLDAP-2.7': {
    deprecated: false,
    osiApproved: false,
  },
  'OLDAP-2.8': {
    deprecated: false,
    osiApproved: true,
  },
  'OLFL-1.3': {
    deprecated: false,
    osiApproved: true,
  },
  OML: {
    deprecated: false,
    osiApproved: false,
  },
  'OPL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'OPL-UK-3.0': {
    deprecated: false,
    osiApproved: false,
  },
  'OPUBL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'OSC-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'OSET-PL-2.1': {
    deprecated: false,
    osiApproved: true,
  },
  'OSL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'OSL-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  'OSL-2.0': {
    deprecated: false,
    osiApproved: true,
  },
  'OSL-2.1': {
    deprecated: false,
    osiApproved: true,
  },
  'OSL-3.0': {
    deprecated: false,
    osiApproved: true,
  },
  OSSP: {
    deprecated: false,
    osiApproved: false,
  },
  'OpenMDW-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'OpenPBS-2.3': {
    deprecated: false,
    osiApproved: false,
  },
  OpenSSL: {
    deprecated: false,
    osiApproved: false,
  },
  'OpenSSL-standalone': {
    deprecated: false,
    osiApproved: false,
  },
  OpenVision: {
    deprecated: false,
    osiApproved: false,
  },
  PADL: {
    deprecated: false,
    osiApproved: false,
  },
  'PDDL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'PHP-3.0': {
    deprecated: false,
    osiApproved: true,
  },
  'PHP-3.01': {
    deprecated: false,
    osiApproved: true,
  },
  PPL: {
    deprecated: false,
    osiApproved: false,
  },
  'PSF-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  'ParaType-Free-Font-1.3': {
    deprecated: false,
    osiApproved: false,
  },
  'Parity-6.0.0': {
    deprecated: false,
    osiApproved: false,
  },
  'Parity-7.0.0': {
    deprecated: false,
    osiApproved: false,
  },
  Pixar: {
    deprecated: false,
    osiApproved: false,
  },
  Plexus: {
    deprecated: false,
    osiApproved: false,
  },
  'PolyForm-Noncommercial-1.0.0': {
    deprecated: false,
    osiApproved: false,
  },
  'PolyForm-Small-Business-1.0.0': {
    deprecated: false,
    osiApproved: false,
  },
  PostgreSQL: {
    deprecated: false,
    osiApproved: true,
  },
  'Python-2.0': {
    deprecated: false,
    osiApproved: true,
  },
  'Python-2.0.1': {
    deprecated: false,
    osiApproved: false,
  },
  'QPL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'QPL-1.0-INRIA-2004': {
    deprecated: false,
    osiApproved: false,
  },
  Qhull: {
    deprecated: false,
    osiApproved: false,
  },
  'RHeCos-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  'RPL-1.1': {
    deprecated: false,
    osiApproved: true,
  },
  'RPL-1.5': {
    deprecated: false,
    osiApproved: true,
  },
  'RPSL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'RSA-MD': {
    deprecated: false,
    osiApproved: false,
  },
  RSCPL: {
    deprecated: false,
    osiApproved: true,
  },
  Rdisc: {
    deprecated: false,
    osiApproved: false,
  },
  Ruby: {
    deprecated: false,
    osiApproved: false,
  },
  'Ruby-pty': {
    deprecated: false,
    osiApproved: false,
  },
  'SAX-PD': {
    deprecated: false,
    osiApproved: false,
  },
  'SAX-PD-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  SCEA: {
    deprecated: false,
    osiApproved: false,
  },
  'SGI-B-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'SGI-B-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  'SGI-B-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  'SGI-OpenGL': {
    deprecated: false,
    osiApproved: false,
  },
  'SGMLUG-PM': {
    deprecated: false,
    osiApproved: false,
  },
  SGP4: {
    deprecated: false,
    osiApproved: false,
  },
  'SHL-0.5': {
    deprecated: false,
    osiApproved: false,
  },
  'SHL-0.51': {
    deprecated: false,
    osiApproved: false,
  },
  SISSL: {
    deprecated: false,
    osiApproved: true,
  },
  'SISSL-1.2': {
    deprecated: false,
    osiApproved: false,
  },
  SL: {
    deprecated: false,
    osiApproved: false,
  },
  'SMAIL-GPL': {
    deprecated: false,
    osiApproved: false,
  },
  SMLNJ: {
    deprecated: false,
    osiApproved: false,
  },
  SMPPL: {
    deprecated: false,
    osiApproved: false,
  },
  SNIA: {
    deprecated: false,
    osiApproved: false,
  },
  SOFA: {
    deprecated: false,
    osiApproved: false,
  },
  'SPL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'SSH-OpenSSH': {
    deprecated: false,
    osiApproved: false,
  },
  'SSH-short': {
    deprecated: false,
    osiApproved: false,
  },
  'SSLeay-standalone': {
    deprecated: false,
    osiApproved: false,
  },
  'SSPL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'SUL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  SWL: {
    deprecated: false,
    osiApproved: false,
  },
  Saxpath: {
    deprecated: false,
    osiApproved: false,
  },
  SchemeReport: {
    deprecated: false,
    osiApproved: false,
  },
  Sendmail: {
    deprecated: false,
    osiApproved: false,
  },
  'Sendmail-8.23': {
    deprecated: false,
    osiApproved: false,
  },
  'Sendmail-Open-Source-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  'SimPL-2.0': {
    deprecated: false,
    osiApproved: true,
  },
  Sleepycat: {
    deprecated: false,
    osiApproved: true,
  },
  Soundex: {
    deprecated: false,
    osiApproved: false,
  },
  'Spencer-86': {
    deprecated: false,
    osiApproved: false,
  },
  'Spencer-94': {
    deprecated: false,
    osiApproved: false,
  },
  'Spencer-99': {
    deprecated: false,
    osiApproved: false,
  },
  'StandardML-NJ': {
    deprecated: true,
    osiApproved: false,
  },
  'SugarCRM-1.1.3': {
    deprecated: false,
    osiApproved: false,
  },
  'Sun-PPP': {
    deprecated: false,
    osiApproved: false,
  },
  'Sun-PPP-2000': {
    deprecated: false,
    osiApproved: false,
  },
  SunPro: {
    deprecated: false,
    osiApproved: false,
  },
  Symlinks: {
    deprecated: false,
    osiApproved: false,
  },
  'TAPR-OHL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  TCL: {
    deprecated: false,
    osiApproved: false,
  },
  'TCP-wrappers': {
    deprecated: false,
    osiApproved: false,
  },
  'TGPPL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  TMate: {
    deprecated: false,
    osiApproved: false,
  },
  'TORQUE-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  TOSL: {
    deprecated: false,
    osiApproved: false,
  },
  TPDL: {
    deprecated: false,
    osiApproved: false,
  },
  'TPL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  TTWL: {
    deprecated: false,
    osiApproved: false,
  },
  TTYP0: {
    deprecated: false,
    osiApproved: false,
  },
  'TU-Berlin-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'TU-Berlin-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  TekHVC: {
    deprecated: false,
    osiApproved: false,
  },
  TermReadKey: {
    deprecated: false,
    osiApproved: false,
  },
  ThirdEye: {
    deprecated: false,
    osiApproved: false,
  },
  TrustedQSL: {
    deprecated: false,
    osiApproved: false,
  },
  UCAR: {
    deprecated: false,
    osiApproved: false,
  },
  'UCL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'UMich-Merit': {
    deprecated: false,
    osiApproved: false,
  },
  'UPL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'URT-RLE': {
    deprecated: false,
    osiApproved: false,
  },
  'Ubuntu-font-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  UnRAR: {
    deprecated: false,
    osiApproved: false,
  },
  'Unicode-3.0': {
    deprecated: false,
    osiApproved: true,
  },
  'Unicode-DFS-2015': {
    deprecated: false,
    osiApproved: false,
  },
  'Unicode-DFS-2016': {
    deprecated: false,
    osiApproved: true,
  },
  'Unicode-TOU': {
    deprecated: false,
    osiApproved: false,
  },
  UnixCrypt: {
    deprecated: false,
    osiApproved: false,
  },
  Unlicense: {
    deprecated: false,
    osiApproved: true,
  },
  'Unlicense-libtelnet': {
    deprecated: false,
    osiApproved: false,
  },
  'Unlicense-libwhirlpool': {
    deprecated: false,
    osiApproved: false,
  },
  VOSTROM: {
    deprecated: false,
    osiApproved: false,
  },
  'VSL-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  Vim: {
    deprecated: false,
    osiApproved: false,
  },
  'Vixie-Cron': {
    deprecated: false,
    osiApproved: false,
  },
  W3C: {
    deprecated: false,
    osiApproved: true,
  },
  'W3C-19980720': {
    deprecated: false,
    osiApproved: false,
  },
  'W3C-20150513': {
    deprecated: false,
    osiApproved: true,
  },
  WTFNMFPL: {
    deprecated: false,
    osiApproved: false,
  },
  WTFPL: {
    deprecated: false,
    osiApproved: false,
  },
  'Watcom-1.0': {
    deprecated: false,
    osiApproved: true,
  },
  'Widget-Workshop': {
    deprecated: false,
    osiApproved: false,
  },
  WordNet: {
    deprecated: false,
    osiApproved: true,
  },
  Wsuipa: {
    deprecated: false,
    osiApproved: false,
  },
  X11: {
    deprecated: false,
    osiApproved: false,
  },
  'X11-distribute-modifications-variant': {
    deprecated: false,
    osiApproved: false,
  },
  'X11-no-permit-persons': {
    deprecated: false,
    osiApproved: false,
  },
  'X11-swapped': {
    deprecated: false,
    osiApproved: false,
  },
  'XFree86-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  XSkat: {
    deprecated: false,
    osiApproved: false,
  },
  'Xdebug-1.03': {
    deprecated: false,
    osiApproved: false,
  },
  Xerox: {
    deprecated: false,
    osiApproved: false,
  },
  Xfig: {
    deprecated: false,
    osiApproved: false,
  },
  Xnet: {
    deprecated: false,
    osiApproved: true,
  },
  'YPL-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  'YPL-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  'ZPL-1.1': {
    deprecated: false,
    osiApproved: false,
  },
  'ZPL-2.0': {
    deprecated: false,
    osiApproved: true,
  },
  'ZPL-2.1': {
    deprecated: false,
    osiApproved: true,
  },
  Zed: {
    deprecated: false,
    osiApproved: false,
  },
  Zeeff: {
    deprecated: false,
    osiApproved: false,
  },
  'Zend-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  'Zimbra-1.3': {
    deprecated: false,
    osiApproved: false,
  },
  'Zimbra-1.4': {
    deprecated: false,
    osiApproved: false,
  },
  Zlib: {
    deprecated: false,
    osiApproved: true,
  },
  'any-OSI': {
    deprecated: false,
    osiApproved: false,
  },
  'any-OSI-perl-modules': {
    deprecated: false,
    osiApproved: false,
  },
  'bcrypt-Solar-Designer': {
    deprecated: false,
    osiApproved: false,
  },
  blessing: {
    deprecated: false,
    osiApproved: false,
  },
  'bzip2-1.0.5': {
    deprecated: true,
    osiApproved: false,
  },
  'bzip2-1.0.6': {
    deprecated: false,
    osiApproved: false,
  },
  'check-cvs': {
    deprecated: false,
    osiApproved: false,
  },
  checkmk: {
    deprecated: false,
    osiApproved: false,
  },
  'copyleft-next-0.3.0': {
    deprecated: false,
    osiApproved: false,
  },
  'copyleft-next-0.3.1': {
    deprecated: false,
    osiApproved: false,
  },
  curl: {
    deprecated: false,
    osiApproved: false,
  },
  'cve-tou': {
    deprecated: false,
    osiApproved: false,
  },
  diffmark: {
    deprecated: false,
    osiApproved: false,
  },
  dtoa: {
    deprecated: false,
    osiApproved: false,
  },
  dvipdfm: {
    deprecated: false,
    osiApproved: false,
  },
  'eCos-2.0': {
    deprecated: true,
    osiApproved: false,
  },
  eGenix: {
    deprecated: false,
    osiApproved: false,
  },
  'etalab-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  fwlw: {
    deprecated: false,
    osiApproved: false,
  },
  'gSOAP-1.3b': {
    deprecated: false,
    osiApproved: false,
  },
  'generic-xts': {
    deprecated: false,
    osiApproved: false,
  },
  gnuplot: {
    deprecated: false,
    osiApproved: false,
  },
  gtkbook: {
    deprecated: false,
    osiApproved: false,
  },
  hdparm: {
    deprecated: false,
    osiApproved: false,
  },
  'hyphen-bulgarian': {
    deprecated: false,
    osiApproved: false,
  },
  iMatix: {
    deprecated: false,
    osiApproved: false,
  },
  jove: {
    deprecated: false,
    osiApproved: false,
  },
  'libpng-1.6.35': {
    deprecated: false,
    osiApproved: false,
  },
  'libpng-2.0': {
    deprecated: false,
    osiApproved: false,
  },
  'libselinux-1.0': {
    deprecated: false,
    osiApproved: false,
  },
  libtiff: {
    deprecated: false,
    osiApproved: false,
  },
  'libutil-David-Nugent': {
    deprecated: false,
    osiApproved: false,
  },
  lsof: {
    deprecated: false,
    osiApproved: false,
  },
  magaz: {
    deprecated: false,
    osiApproved: false,
  },
  mailprio: {
    deprecated: false,
    osiApproved: false,
  },
  man2html: {
    deprecated: false,
    osiApproved: false,
  },
  metamail: {
    deprecated: false,
    osiApproved: false,
  },
  'mpi-permissive': {
    deprecated: false,
    osiApproved: false,
  },
  mpich2: {
    deprecated: false,
    osiApproved: false,
  },
  mplus: {
    deprecated: false,
    osiApproved: false,
  },
  ngrep: {
    deprecated: false,
    osiApproved: false,
  },
  pkgconf: {
    deprecated: false,
    osiApproved: false,
  },
  pnmstitch: {
    deprecated: false,
    osiApproved: false,
  },
  psfrag: {
    deprecated: false,
    osiApproved: false,
  },
  psutils: {
    deprecated: false,
    osiApproved: false,
  },
  'python-ldap': {
    deprecated: false,
    osiApproved: false,
  },
  radvd: {
    deprecated: false,
    osiApproved: false,
  },
  snprintf: {
    deprecated: false,
    osiApproved: false,
  },
  softSurfer: {
    deprecated: false,
    osiApproved: false,
  },
  'ssh-keyscan': {
    deprecated: false,
    osiApproved: false,
  },
  swrule: {
    deprecated: false,
    osiApproved: false,
  },
  threeparttable: {
    deprecated: false,
    osiApproved: false,
  },
  ulem: {
    deprecated: false,
    osiApproved: false,
  },
  w3m: {
    deprecated: false,
    osiApproved: false,
  },
  wwl: {
    deprecated: false,
    osiApproved: false,
  },
  wxWindows: {
    deprecated: true,
    osiApproved: true,
  },
  xinetd: {
    deprecated: false,
    osiApproved: false,
  },
  'xkeyboard-config-Zinoviev': {
    deprecated: false,
    osiApproved: false,
  },
  xlock: {
    deprecated: false,
    osiApproved: false,
  },
  xpp: {
    deprecated: false,
    osiApproved: false,
  },
  xzoom: {
    deprecated: false,
    osiApproved: false,
  },
  'zlib-acknowledgement': {
    deprecated: false,
    osiApproved: false,
  },
}
