// SPDX-FileCopyrightText: The kurly Authors
// SPDX-License-Identifier: 0BSD

// Generated by scripts/gen-upstream.sh from the images the workloads pin —
// do not edit; regenerate with: gen-upstream
//
// What each image says about the software it packages. A workload annotation
// overrides anything here; see catalog/annotations.libsonnet.
{
}
