# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# Writes the SPDX licence list to catalog/spdx.gen.libsonnet, so the catalogue
# can check a licence value against the real register instead of against a
# shape.
#
# A shape check ("looks like an identifier") passes `ESPHome`, `AGPLv3` and
# `BSL-1.1` — a project's own name, a spelling SPDX does not use, and an
# identifier that means the Boost licence when the image means the Business
# Source one. Each of those reads as a licence to anyone rendering the field,
# and the last two would make a source-offer obligation miss a case or a
# proprietary edition look permissive. Only the register knows.
#
# The list rides in the devShell (nixpkgs' spdx-license-list-data, pinned by
# flake.lock and bumped by Renovate), so this generator needs no network and
# check-catalog can rerun it in the per-PR gate — the published set of valid
# identifiers cannot drift from the one that was checked against.
#
# Each entry carries the two things a consumer cannot work out from the string:
# whether the licence is OSI-approved (a platform that says it hosts open source
# needs to know that BUSL-1.1 is not), and whether the identifier is deprecated
# (`GPL-3.0` says neither `-only` nor `-or-later`, so it is ambiguous rather
# than wrong — worth saying, never worth guessing away).
set -euo pipefail

out=catalog/spdx.gen.libsonnet
data="${SPDX_LICENSE_LIST_DATA:?the devShell must provide spdx-license-list-data}/json/licenses.json"

{
  printf '// %s: The kurly Authors\n' 'SPDX-FileCopyrightText'
  printf '// %s: 0BSD\n\n' 'SPDX-License-Identifier'
  printf '// Generated by scripts/gen-spdx.sh from the SPDX licence list version %s —\n' \
    "$(jq -r '.licenseListVersion' "$data")"
  printf '// do not edit; regenerate with: gen-spdx\n'
  printf '//\n'
  printf '// Every identifier SPDX knows, with whether it is OSI-approved and whether\n'
  printf '// SPDX has deprecated the spelling. catalog.jsonnet rejects any licence value\n'
  printf '// that is not a key here, so a label stating a project name or a misspelled\n'
  printf '// identifier fails the build instead of being published as a licence.\n'
  # Through jsonnetfmt because catalog/*.libsonnet is format-checked: JSON is
  # valid Jsonnet, but not the spelling jsonnetfmt settles on.
  jq --sort-keys \
    '[.licenses[] | { key: .licenseId, value: { osiApproved: .isOsiApproved, deprecated: .isDeprecatedLicenseId } }] | from_entries' \
    "$data" | jsonnetfmt -
} > "${out}.tmp"
mv "${out}.tmp" "$out"

echo "wrote ${out}: $(jq -r '.licenses | length' "$data") identifiers from SPDX list $(jq -r '.licenseListVersion' "$data")"
