# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# Reads each workload's image labels from the registry and writes what they say
# about the software into catalog/upstream.gen.libsonnet — the license it is
# published under, the repository it is built from, and its own name for itself.
#
# These are facts about the software rather than about kurly, and the image is
# the most direct place to ask: the OCI annotations are set by the people who
# build it. Deriving them beats transcribing them, for the same reason
# architectures are derived — a hand-typed license is a claim that rots quietly,
# and this one carries a legal obligation.
#
# NOT every label is usable, so each is validated before it is published:
#
#   * a license must look like an SPDX expression; images carry things like
#     "ESPHome" in that field, and a wrong identifier is worse than none
#   * a source must be an https URL
#
# Anything that fails validation is dropped, and anything a workload's own
# annotation states wins over the label — a maintainer who checked the upstream
# beats a label generated by a build pipeline. What remains uncovered is reported
# at the end, because that list is the work.
#
# Network-bound, like gen-architectures: run it on demand or on a schedule, never
# in the per-PR gate.
set -euo pipefail

out=catalog/upstream.gen.libsonnet
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

# An SPDX expression as it appears in practice: identifiers, an optional `-only`
# / `-or-later`, joined by AND/OR/WITH. Deliberately shape-only — kurly does not
# ship an SPDX list, and a shape check already rejects the junk labels carry.
spdx='^[A-Za-z0-9.+-]+( (AND|OR|WITH) [A-Za-z0-9.+-]+)*$'

covered=0
total=0
missing=""

{
  printf '// %s: The kurly Authors\n' 'SPDX-FileCopyrightText'
  printf '// %s: 0BSD\n\n' 'SPDX-License-Identifier'
  printf '// Generated by scripts/gen-upstream.sh from the images the workloads pin —\n'
  printf '// do not edit; regenerate with: gen-upstream\n'
  printf '//\n'
  printf '// What each image says about the software it packages. A workload annotation\n'
  printf '// overrides anything here; see catalog/annotations.libsonnet.\n'
  printf '{\n'
} > "$tmp"

for dir in workloads/*/; do
  id="${dir#workloads/}"
  id="${id%/}"
  image=""
  for f in "$dir"*.image; do
    [ -f "$f" ] || continue
    image="$(tr -d '\n' < "$f")"
    break
  done
  [ -n "$image" ] || continue
  total=$((total + 1))

  labels="$(skopeo inspect --no-tags "docker://${image}" 2>/dev/null | jq -c '.Labels // {}' || echo '{}')"
  license="$(jq -r '.["org.opencontainers.image.licenses"] // empty' <<<"$labels")"
  source="$(jq -r '.["org.opencontainers.image.source"] // empty' <<<"$labels")"
  url="$(jq -r '.["org.opencontainers.image.url"] // empty' <<<"$labels")"
  title="$(jq -r '.["org.opencontainers.image.title"] // empty' <<<"$labels")"

  grep -qE "$spdx" <<<"$license" || license=""
  case "$source" in https://*) ;; *) source="" ;; esac
  case "$url" in https://*) ;; *) url="" ;; esac
  # A .git suffix is how a build pipeline writes a clone URL; the field is a link.
  source="${source%.git}"

  if [ -z "$license" ] && [ -z "$source" ] && [ -z "$url" ] && [ -z "$title" ]; then
    missing="${missing}${id} "
    continue
  fi
  covered=$((covered + 1))

  {
    # jsonnetfmt quotes a key only when it must; emit quoted and let it decide.
    printf "  '%s': {\n" "$id"
    [ -n "$license" ] && printf "    license: '%s',\n" "$license"
    [ -n "$title" ] && printf "    title: '%s',\n" "${title//\'/\\\'}"
    [ -n "$source" ] && printf "    source: '%s',\n" "$source"
    [ -n "$url" ] && printf "    homepage: '%s',\n" "$url"
    printf '  },\n'
  } >> "$tmp"
done

printf '}\n' >> "$tmp"
mv "$tmp" "$out"
trap - EXIT

echo "wrote ${out}: ${covered}/${total} workloads carry usable image labels"
[ -n "$missing" ] && {
  echo "no usable labels (annotate these by hand in catalog/annotations.libsonnet):"
  printf '%s\n' "$missing" | tr ' ' '\n' | grep -v '^$' | sort | paste -sd' ' -
}
exit 0
