#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# Generates the fast-check e2e scenario for every workload that boots from its own
# published image, driven entirely by the catalog: `hack/smoke/scenario-<id>.sh`
# provisions any declared dependency, mints the Secret the app reads, boots every
# stage, and waits for health. `gen-maturity` lifts each covered workload to the
# `e2e` tier from the scenario's existence.
#
# There are NO per-workload workflows — a single `.github/workflows/e2e.yml`
# pipeline detects which workloads a PR changed and runs their fast check (this
# scenario) then their deep check, so CI is one run, never hundreds.
#
# It touches ONLY generated files: a scenario carrying the marker below is
# regenerated in place, one lacking it (a hand-authored scenario like tik's) is
# left untouched. Standalone workloads (empty `requires`) just boot; dependency-
# backed ones first stand up a throwaway postgres/valkey at the service names the
# app defaults to, so it connects with no param override, and get a Secret minted
# from the catalog's per-stage `secretKeys`.
set -euo pipefail
# Run from the repository root (as the flake's `gen-smoke` command does), matching
# the sibling gen-* scripts — paths below are repo-relative.

# Assemble the SPDX tag names from parts so the literal tokens never appear whole
# in this generator's source — otherwise REUSE reads the header lines this script
# PRINTS as (invalid, duplicated) license expressions of the script itself.
spdx_copy='SPDX-File''CopyrightText'
spdx_lic='SPDX-License''-Identifier'

# EVERY catalogued workload gets a scenario, whether or not its architectures have
# been measured. Gating generation on `architectures` treated a fact NOBODY HAD
# ASKED FOR as a fact that is not there: the field is network-derived and
# regenerated on demand, so it is null for every newly added workload. The gate
# did not merely skip those — it left the scenario ALREADY ON DISK in place while
# reporting a successful run, so 77 workloads walked against a scenario generated
# before the catalogue said what they depend on. A stale scenario is worse than a
# missing one, because the walk runs it and reports on it.
#
# A stage with NO POD TEMPLATE is still skipped, and that filter is a different
# kind of thing: `posture` is DERIVED by rendering the stage, so its being null
# states positively that the stage renders a custom resource whose pods an
# operator runs — it is an answer, not an unasked question. Such a stage cannot
# boot (composing a kurly feature onto a custom resource is refused by the
# workload's own assert) and is validated by server-side dry-run against the real
# operator schema, which needs CRD URLs the catalogue does not carry. Those
# scenarios are therefore hand-written, and are named on every run so a workload
# missing one is visible rather than silently uncovered.
marker='# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke'
catalog=.build/catalog.json
[ -f "$catalog" ] || { echo "::error::$catalog missing — run gen-catalog first"; exit 1; }

generated=0 generated_dep=0 skipped_hand=0

# Extracts a stage parameter's simple quoted default (dbHost='x' -> x); empty when
# the default is a computed expression rather than a literal.
# ALWAYS ASK THE CATALOGUE, NEVER THE SOURCE. A stage's parameter defaults are
# published per stage as `args`, and check-catalog fails when an annotated
# default disagrees with the real one — so the catalogue is both authoritative
# and verified, while a grep over the jsonnet is neither. It reads only what is
# spelled the way the pattern expects and answers "absent" for everything else,
# which is indistinguishable from a parameter that genuinely has no default.
#
# That difference provisioned the wrong database for piler: it declares
# engine: mysql in the catalogue and takes its connection details from a Secret,
# so a grep of its source for 3306 found nothing and the harness handed it a
# PostgreSQL. The workload then reported that it could not reach its database,
# which reads as the workload's defect.
#
#   param <workload>/<stage> <argument>
param() {
  jq -r --arg k "$1" --arg n "$2" '
    .workloads[].stages[] | select(.importPath == "github.com/metio/kurly/workloads/\($k).libsonnet")
    | .args[]? | select(.name == $n) | .default // empty' "$catalog" 2>/dev/null | head -1 || true
}

# Extra Jsonnet composed onto a stage before it boots, from hack/smoke/extra.json —
# how an app that refuses to start without a deployment-specific value (its own
# public URL, a licence key) is given one for the smoke, without inventing a
# default the workload itself must not carry. Keyed by "<id>/<stage>", falling back
# to "<id>" for every stage of a workload.
extra=hack/smoke/extra.json
extra_for() {
  jq -r --arg k "$1" --arg id "${1%%/*}" '(.[$k] // .[$id] // {}).compose // ""' "$extra"
}

# The same file's other facet, and it must be emitted too: `compose` is added to
# a built app with `+`, while `params` is passed when the stage function is
# CALLED — the only way to reach an argument. A generator that read only
# `compose` dropped the other silently, and the scenario then booted a stage
# configured differently from the one the entry describes.
params_for() {
  jq -r --arg k "$1" --arg id "${1%%/*}" '(.[$k] // .[$id] // {}).params // ""' "$extra"
}

# The same file's third facet: how long this workload's first start legitimately
# takes. The default rollout ceiling suits a workload that starts in seconds and
# is simply WRONG for one that builds assets or migrates a large schema before it
# answers — docassemble and netbox both become healthy, in around seven minutes.
# Declared per workload rather than raised globally, because a global raise would
# make every genuinely broken workload cost that long before it failed.
timeout_for() {
  jq -r --arg k "$1" --arg id "${1%%/*}" '(.[$k] // .[$id] // {}).rolloutTimeout // ""' "$extra"
}

# A generated scenario is regenerated in place; a hand-written one is left alone.
is_hand_written() {
  local scenario="hack/smoke/scenario-$1.sh"
  [ -f "$scenario" ] && ! grep -qF "$marker" "$scenario"
}

emit_header() {
  printf '#!/usr/bin/env bash\n'
  printf '# %s: The kurly Authors\n' "$spdx_copy"
  printf '# %s: 0BSD\n\n' "$spdx_lic"
  printf '%s\n' "$marker"
}

# --- standalone workloads: empty `requires`, at least one real image ----------
while IFS=$'\t' read -r id stages; do
  [ -n "$id" ] || continue
  if is_hand_written "$id"; then skipped_hand=$((skipped_hand + 1)); continue; fi
  scenario="hack/smoke/scenario-${id}.sh"

  # Boot each stage in its own namespace; a single-stage workload gets the bare
  # kurly-<id> namespace, multi-stage workloads suffix the stage.
  boot_lines=""
  IFS=',' read -ra arr <<<"$stages"
  for stage in "${arr[@]}"; do
    file="workloads/${id}/${stage}.libsonnet"
    [ -f "$file" ] || { echo "::error::${file} referenced by the catalog does not exist"; exit 1; }
    if [ "${#arr[@]}" -eq 1 ]; then ns="kurly-${id}"; else ns="kurly-${id}-${stage}"; fi
    primaryKey="${id}/${stage}"
    # A stage that reads a Secret (envFromSecret) declares secretKeys in the
    # catalog even without a database/cache dependency; mint that Secret before
    # booting or the container fails with "secret not found".
    # A FRESH NAMESPACE PER STAGE, named after it but never reused: a re-run
    # minutes after the last cleanup would otherwise create into a namespace
    # still draining, which accepts the create and refuses everything in it.
    boot_lines+="ns=\"\$(kurly::namespace_unique ${ns})\""$'\n'
    # A stage that reads a Secret (envFromSecret) declares secretKeys in the
    # catalog even without a database/cache dependency; mint that Secret before
    # booting or the container fails with "secret not found".
    if [ "$(jq -r --arg ip "github.com/metio/kurly/${file}" '[.workloads[].stages[] | select(.importPath==$ip) | .secretKeys // []] | add | length' "$catalog")" != 0 ]; then
      secretName="$(param "$primaryKey" secretName)"; [ -n "$secretName" ] || secretName="$id"
      boot_lines+="kurly::secret \"\$ns\" ${secretName} ${file}"$'\n'
    fi
    ex="$(extra_for "${id}/${stage}")"
    pa="$(params_for "${id}/${stage}")"
    to="$(timeout_for "${id}/${stage}")"
    [ -z "$to" ] || boot_lines+="export KURLY_ROLLOUT_TIMEOUT=${to}"$'\n'
    boot_lines+="kurly::boot ${file} \"\$ns\" \"${ex}\" \"${pa}\""$'\n'
  done

  {
    emit_header
    printf '# e2e for the %s workload: boot every stage on a live kind cluster from its\n' "$id"
    printf '# own published image and wait for it to become healthy. No external dependency.\n'
    printf 'cd "$(dirname "$0")/../.."\n'
    printf '# shellcheck source=hack/smoke/lib.sh\n'
    printf 'source hack/smoke/lib.sh\n'
    printf 'kurly::vendor\n\n'
    printf '%s' "$boot_lines"
  } >"$scenario"
  chmod +x "$scenario"
  generated=$((generated + 1))
done < <(jq -r '
  .workloads[]
  | select((.requires // [] | length) == 0)
  | select([.stages[].posture] | any(. != null))
  | "\(.id)\t\([.stages[].id] | join(","))"
' "$catalog")

# --- dependency-backed workloads ----------------------------------------------
# Provision each declared dependency at the service name the app defaults to (so
# it connects with no param override), mint the Secret it reads, then boot every
# stage in the shared namespace. The connection defaults follow kurly's naming
# convention (<name>-db-rw, <name>-cache-headless); the throwaway postgres/valkey
# are created under exactly those names.
while IFS=$'\t' read -r id stages db cache objstore; do
  [ -n "$id" ] || continue
  if is_hand_written "$id"; then skipped_hand=$((skipped_hand + 1)); continue; fi
  scenario="hack/smoke/scenario-${id}.sh"
  IFS=',' read -ra arr <<<"$stages"
  primary="workloads/${id}/${arr[0]}.libsonnet"
  primaryKey="${id}/${arr[0]}"

  prov=""
  if [ "$db" = "1" ]; then
    dbName="$(param "$primaryKey" dbName)"; [ -n "$dbName" ] || dbName="$(param "$primaryKey" database)"; [ -n "$dbName" ] || dbName="$id"
    dbUser="$(param "$primaryKey" dbUser)"; [ -n "$dbUser" ] || dbUser="$id"
    # MongoDB first, because it is the one engine the two tests below cannot tell
    # apart: a Mongo-backed stage mentions neither 3306 nor 5432, so it fell
    # through to the PostgreSQL branch and was handed a server speaking the wrong
    # protocol. The workload then failed to connect, which reads as the
    # workload's defect and is the harness having provisioned the wrong database.
    #
    # Asked of the CATALOGUE rather than of the file, because the engine is
    # derived there in a documented precedence — and ferretdb speaks the MongoDB
    # protocol while storing in PostgreSQL, so grepping the source for "mongo"
    # would take its database away.
    engine="$(jq -r --arg id "$id" '[.workloads[]|select(.id==$id)|.requires[]?|select(.kind=="database")|.engine//empty]|first//""' "$catalog")"
    if [ "$engine" = "mongodb" ]; then
      dbHost="$(param "$primaryKey" dbHost)"; [ -n "$dbHost" ] || dbHost="${id}-db"
      prov+="kurly::mongodb \"\$ns\" ${dbHost}"$'\n'
    elif [ "$engine" = "elasticsearch" ]; then
      # The host comes from the stage's own URL parameter where it has one: an
      # app that takes `esUrl` names the scheme and port too, and provisioning at
      # some other name would leave it pointing at nothing.
      esHost="$(param "$primaryKey" esHost)"
      [ -n "$esHost" ] || esHost="$(param "$primaryKey" esUrl | sed -E 's#^https?://##; s#:[0-9]+.*$##')"
      [ -n "$esHost" ] || esHost="${id}-search"
      prov+="kurly::elasticsearch \"\$ns\" ${esHost}"$'\n'
    # THE CATALOGUE FIRST, the file only as a fallback. The two branches above ask
    # the catalogue and this one used to grep the stage's source for 3306 or
    # mysql, so a workload that DECLARES engine: mysql while taking its
    # connection details from a Secret matched nothing and fell through to
    # PostgreSQL — piler did, and then reported that it could not reach its
    # database, which reads as the workload's defect and is the harness having
    # provisioned a server speaking the wrong protocol.
    #
    # The grep survives for stages the catalogue states no engine for: it is a
    # guess, but a guess from the file is better than defaulting every one of
    # them to PostgreSQL.
    elif [ "$engine" = "mysql" ] || [ "$engine" = "mariadb" ]; then
      dbHost="$(param "$primaryKey" dbHost)"; [ -n "$dbHost" ] || dbHost="${id}-db"
      prov+="kurly::mysql \"\$ns\" ${dbHost} ${dbName} ${dbUser}"$'\n'
    # THE LAST RESORT, and it announces itself. The catalogue states an engine for
    # only part of the fleet, and a stage without one would otherwise be handed a
    # PostgreSQL in silence. Guessing from the file is better than that, but the
    # FIX is to record the engine in the catalogue — so every guess is printed
    # with the stage that needs annotating rather than left to be discovered by a
    # workload failing to connect.
    elif [ -z "$engine" ] && grep -qE "3306|mariadb|mysql" "$primary" 2>/dev/null; then
      echo "gen-smoke: ${id}: engine guessed from the source as mysql — annotate requires[].engine in the catalogue" >&2
      dbHost="$(param "$primaryKey" dbHost)"; [ -n "$dbHost" ] || dbHost="${id}-db"
      prov+="kurly::mysql \"\$ns\" ${dbHost} ${dbName} ${dbUser}"$'\n'
    else
      dbHost="$(param "$primaryKey" dbHost)"; [ -n "$dbHost" ] || dbHost="${id}-db-rw"
      # A workload that needs a PostgreSQL extension gets a server image carrying
      # it — the stock image would fail its first CREATE EXTENSION.
      pgimage=""
      case "$(jq -r --arg id "$id" '[.workloads[]|select(.id==$id)|.requires[]?|select(.kind=="database")|.extensions//[]|.[]]|join(",")' "$catalog")" in
        # VectorChord only works when the server preloads it, and immich pins the
        # extension version range it supports.
        *vchord*) pgimage=" ghcr.io/immich-app/postgres:17-vectorchord0.4.3-pgvector0.8.1-pgvectors0.3.0 '\"-c\", \"shared_preload_libraries=vchord.so\"'" ;;
        # PostGIS ships the `geometry` type as an extension the stock image does
        # not carry: a workload that stores coordinates fails its FIRST migration
        # with `type "geometry" does not exist`, which reads as a broken schema
        # rather than a missing server feature.
        *postgis*) pgimage=" docker.io/postgis/postgis:17-3.5" ;;
      esac
      prov+="kurly::postgres \"\$ns\" ${dbHost} ${dbName} ${dbUser}${pgimage}"$'\n'
    fi
  fi
  # A workload declaring objectStorage gets a real S3 gateway, because there is
  # nothing to fake: it signs requests and reads back what it wrote. seaweedfs is
  # already carried here, so the smoke uses the same server a consumer would.
  # Without this an S3-backed workload cannot be proven at all — it starts, finds
  # no endpoint, and dies in a way that reads as its own defect.
  if [ "$objstore" = "1" ]; then
    bucket="$(param "$primaryKey" bucket)"; [ -n "$bucket" ] || bucket="$id"
    prov+="kurly::objectstorage \"\$ns\" ${bucket}"$'\n'
  fi
  if [ "$cache" = "1" ]; then
    redisHost="$(param "$primaryKey" redisHost)"; [ -n "$redisHost" ] || redisHost="${id}-cache-headless"
    # Provision the cache the way the workload connects to it. Most take a host and
    # no credential — which is how a cache in the workload's OWN namespace is
    # normally run, reachable only from that namespace and kept that way by a
    # NetworkPolicy rather than a password. A few read a whole connection URL from
    # their Secret, and the catalog's redisUrl generator writes a password into it,
    # so those need a server that expects one. Guessing either way fails: an app
    # with no credential meets NOAUTH, an app sending one meets "Client sent AUTH,
    # but no password is set".
    if jq -e --arg id "$id" '.workloads[]|select(.id==$id)|.stages[]|.secretKeys//[]|.[]|select(.generate=="redisUrl")' "$catalog" >/dev/null 2>&1; then
      prov+="kurly::cache \"\$ns\" ${redisHost}"$'\n'
    else
      prov+="kurly::cache \"\$ns\" ${redisHost} \"\""$'\n'
    fi
  fi

  boot_lines=""
  for stage in "${arr[@]}"; do
    file="workloads/${id}/${stage}.libsonnet"
    [ -f "$file" ] || { echo "::error::${file} referenced by the catalog does not exist"; exit 1; }
    secretName="$(param "$file" secretName)"; [ -n "$secretName" ] || secretName="$id"
    boot_lines+="kurly::secret \"\$ns\" ${secretName} ${file}"$'\n'
    ex="$(extra_for "${id}/${stage}")"
    pa="$(params_for "${id}/${stage}")"
    to="$(timeout_for "${id}/${stage}")"
    [ -z "$to" ] || boot_lines+="export KURLY_ROLLOUT_TIMEOUT=${to}"$'\n'
    boot_lines+="kurly::boot ${file} \"\$ns\" \"${ex}\" \"${pa}\""$'\n'
  done

  {
    emit_header
    printf '# e2e for the %s workload: provision its declared dependencies (a throwaway\n' "$id"
    printf '# postgres/valkey at the service names it defaults to), mint the Secret it reads\n'
    printf '# from the catalog secretKeys, then boot every stage and wait for health.\n'
    printf 'cd "$(dirname "$0")/../.."\n'
    printf '# shellcheck source=hack/smoke/lib.sh\n'
    printf 'source hack/smoke/lib.sh\n'
    printf 'kurly::vendor\n\n'
    # A FRESH NAMESPACE PER RUN, for the same reason the standalone branch takes
    # one: a re-run shortly after the last cleanup would otherwise create into a
    # namespace still draining, which accepts the create and refuses everything
    # inside it. The dependency provisioners below all take "$ns", so they land
    # in the same fresh namespace as the workload.
    printf 'ns="$(kurly::namespace_unique kurly-%s)"\n' "$id"
    printf 'kurly::namespace "$ns"\n\n'
    printf '%s\n' "$prov"
    printf '%s' "$boot_lines"
  } >"$scenario"
  chmod +x "$scenario"
  generated_dep=$((generated_dep + 1))
done < <(jq -r '
  .workloads[]
  | select((.requires // [] | length) > 0)
  | select([.stages[].posture] | any(. != null))
  | "\(.id)\t\([.stages[].id] | join(","))\t\(if ((.requires//[])|map(select(.kind=="database"))|length)>0 then 1 else 0 end)\t\(if ((.requires//[])|map(select(.kind=="cache"))|length)>0 then 1 else 0 end)\t\(if ((.requires//[])|map(select(.kind=="objectStorage"))|length)>0 then 1 else 0 end)"
' "$catalog")

# A durable coverage ledger, regenerated every run so it never drifts and stays
# readable across working sessions.
{
  printf '<!-- %s: The kurly Authors -->\n' "$spdx_copy"
  printf '<!-- %s: 0BSD -->\n\n' "$spdx_lic"
  printf '<!-- generated by scripts/gen-smoke.sh — do not edit -->\n\n'
  printf '# e2e coverage\n\n'
  printf 'An e2e scenario boots every workload on a live kind cluster — standalone\n'
  printf 'workloads directly, dependency-backed ones after provisioning a throwaway\n'
  printf 'postgres/valkey and minting their Secret. All are generated by `gen-smoke`.\n\n'
  total=$(jq '.workloads | length' "$catalog")
  cov=$(jq '[.workloads[] | select(.maturity.tier == "e2e")] | length' "$catalog")
  printf '**%s / %s workloads have an e2e scenario.**\n' "$cov" "$total"
  remaining="$(jq -r '.workloads[] | select(.maturity.tier != "e2e") | "- \(.id)"' "$catalog" | LC_ALL=C sort)"
  if [ -n "$remaining" ]; then
    printf '\nWorkloads still awaiting a scenario:\n\n%s\n' "$remaining"
  else
    printf '\nEvery workload has an e2e scenario.\n'
  fi
} >hack/smoke/COVERAGE.md

echo "gen-smoke: generated ${generated} standalone + ${generated_dep} dependency-backed scenarios"
echo "gen-smoke: left ${skipped_hand} hand-written scenarios untouched"

# Name the custom-resource workloads rather than passing over them: each needs a
# hand-written scenario carrying its operator's CRD URLs, and one that has none is
# UNCOVERED — a fact that should be read off this output, not discovered by a walk
# reporting the workload as skipped.
while IFS= read -r id; do
  [ -n "$id" ] || continue
  [ -f "hack/smoke/scenario-${id}.sh" ] \
    || echo "gen-smoke: ${id}: custom resource with no hand-written scenario — uncovered"
done < <(jq -r '
  .workloads[]
  | select([.stages[].posture] | any(. != null) | not)
  | .id
' "$catalog")
echo "gen-smoke: wrote hack/smoke/COVERAGE.md"
