# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# Reads each workload's image labels from the registry and writes what they say
# about the software into catalog/upstream.gen.libsonnet — the license it is
# published under, the repository it is built from, and its own name for itself.
#
# These are facts about the software rather than about kurly, and the image is
# the most direct place to ask: the OCI annotations are set by the people who
# build it. Deriving them beats transcribing them, for the same reason
# architectures are derived — a hand-typed license is a claim that rots quietly,
# and this one carries a legal obligation.
#
# NOT every label is usable, so each is validated before it is published:
#
#   * a license must look like an SPDX expression, so a paragraph of prose never
#     reaches the file; whether the identifiers in it are ones SPDX actually
#     knows is settled in catalog.jsonnet against the register, because the
#     answer changes when the register does and this file is written rarely
#   * a source must be an https URL
#
# Anything that fails validation is dropped, and anything a workload's own
# annotation states wins over the label — a maintainer who checked the upstream
# beats a label generated by a build pipeline. What remains uncovered is reported
# at the end, because that list is the work.
#
# A registry that will not answer is NOT the same as an image that says nothing,
# and the difference matters: three hundred inspects will hit a rate limit or a
# timeout sooner or later, and treating that as "no labels" would quietly delete
# facts that were derived before. So each inspect retries, and a workload whose
# registry stays unreachable keeps whatever the previous run recorded — the run
# then fails, naming them, rather than publishing a thinner catalogue that looks
# like an intentional change.
#
# Network-bound, like gen-architectures: run it on demand or on a schedule, never
# in the per-PR gate.
#
# WORKLOADS (space-separated ids) narrows the sweep to those workloads, keeping
# what the last run derived for the rest. Asking three hundred registries takes
# hours against a rate limit, and one bumped image should not have to pay for it.
set -euo pipefail

# The workload glob below expands in the shell's collation order, and a locale
# that ignores punctuation orders `calibre-web` after `calibre` where C orders it
# before. The generated file would then differ between a contributor's machine
# and CI, and the drift check would fail on nothing but which one ran it.
export LC_ALL=C

only="${WORKLOADS:-}"
out=catalog/upstream.gen.libsonnet
# Written progressively, next to the output rather than in a temp dir: asking
# three hundred registries takes hours, and a run that is interrupted at image
# 279 must not throw away 279 answers. The next run reads whatever is here as
# what was already derived, so it resumes instead of restarting.
tmp="${out}.partial"
previous="$(mktemp)"
trap 'rm -f "$previous"' EXIT

# What is already derived — the last complete run, plus anything an interrupted
# one got through.
{
  if [ -f "$out" ]; then jsonnet "$out" 2>/dev/null || echo '{}'; else echo '{}'; fi
  # Closed into a real file rather than a process substitution: jsonnet reopens
  # the path it is given, and /dev/fd/N has already been consumed by then.
  if [ -f "$tmp" ]; then
    partial="$(mktemp --suffix=.libsonnet)"
    cat "$tmp" > "$partial"
    printf '}\n' >> "$partial"
    jsonnet "$partial" 2>/dev/null || echo '{}'
    rm -f "$partial"
  else echo '{}'; fi
} | jq --slurp '.[0] * .[1]' > "$previous"

# An SPDX expression as it appears in practice: identifiers, an optional `-only`
# / `-or-later`, joined by AND/OR/WITH. Shape only, on purpose: the label is
# recorded as the image states it, and catalog/spdx.gen.libsonnet decides which
# identifiers are real. Keeping the raw value is what lets check-catalog name a
# junk label instead of merely omitting the licence.
spdx='^[A-Za-z0-9.+-]+( (AND|OR|WITH) [A-Za-z0-9.+-]+)*$'

covered=0
total=0
count="$(find workloads -mindepth 1 -maxdepth 1 -type d | wc -l)"
missing=""
kept=""

{
  printf '// %s: The kurly Authors\n' 'SPDX-FileCopyrightText'
  printf '// %s: 0BSD\n\n' 'SPDX-License-Identifier'
  printf '// Generated by scripts/gen-upstream.sh from the images the workloads pin —\n'
  printf '// do not edit; regenerate with: gen-upstream\n'
  printf '//\n'
  printf '// What each image says about the software it packages. A workload annotation\n'
  printf '// overrides anything here; see catalog/annotations.libsonnet.\n'
  printf '{\n'
} > "$tmp"

for dir in workloads/*/; do
  id="${dir#workloads/}"
  id="${id%/}"
  image=""
  for f in "$dir"*.image; do
    [ -f "$f" ] || continue
    image="$(tr -d '\n' < "$f")"
    break
  done
  [ -n "$image" ] || continue
  total=$((total + 1))

  # Outside the requested subset: keep what the last run derived, unasked.
  if [ -n "$only" ] && ! grep -qw -- "$id" <<<"$only"; then
    entry="$(jq -c --arg id "$id" '.[$id] // empty' "$previous")"
    if [ -n "$entry" ]; then
      covered=$((covered + 1))
      {
        printf "  '%s': {\n" "$id"
        jq -r 'to_entries[] | "    \(.key): '"'"'\(.value)'"'"',"' <<<"$entry"
        printf '  },\n'
      } >> "$tmp"
    fi
    continue
  fi

  # --retry-times covers the transient failures skopeo recognises; the loop
  # covers the ones it does not (a timeout, a rate limit answered as an error),
  # backing off so a burst of three hundred inspects does not sustain one.
  labels=""
  attempts=0
  for delay in 0 5 20; do
    attempts=$((attempts + 1))
    [ "$delay" = 0 ] || sleep "$delay"
    if labels="$(timeout 60 skopeo inspect --retry-times 3 --no-tags "docker://${image}" 2>/dev/null | jq -c '.Labels // {}')"; then
      [ -n "$labels" ] && break
    fi
    labels=""
  done
  if [ -z "$labels" ]; then
    printf '%3d/%-3d %-28s unreachable\n' "$total" "$count" "$id" >&2
    # The registry never answered. Keep what the last run derived rather than
    # publishing an absence that reads like a decision.
    kept="${kept}${id} "
    entry="$(jq -c --arg id "$id" '.[$id] // empty' "$previous")"
    if [ -n "$entry" ]; then
      covered=$((covered + 1))
      {
        printf "  '%s': {\n" "$id"
        jq -r 'to_entries[] | "    \(.key): '"'"'\(.value)'"'"',"' <<<"$entry"
        printf '  },\n'
      } >> "$tmp"
    fi
    continue
  fi
  license="$(jq -r '.["org.opencontainers.image.licenses"] // empty' <<<"$labels")"
  source="$(jq -r '.["org.opencontainers.image.source"] // empty' <<<"$labels")"
  url="$(jq -r '.["org.opencontainers.image.url"] // empty' <<<"$labels")"
  title="$(jq -r '.["org.opencontainers.image.title"] // empty' <<<"$labels")"

  grep -qE "$spdx" <<<"$license" || license=""
  case "$source" in https://*) ;; *) source="" ;; esac
  case "$url" in https://*) ;; *) url="" ;; esac
  # A .git suffix is how a build pipeline writes a clone URL; the field is a link.
  source="${source%.git}"

  if [ -z "$license" ] && [ -z "$source" ] && [ -z "$url" ] && [ -z "$title" ]; then
    missing="${missing}${id} "
    continue
  fi
  covered=$((covered + 1))
  # Progress, per image: the sweep takes an hour or more against a rate-limiting
  # registry, and a run that says nothing for that long hides both its progress
  # and the fact that a second copy of it is running.
  printf '%3d/%-3d %-28s %s\n' "$total" "$count" "$id" \
    "$( [ "$attempts" -gt 1 ] && printf 'retried %sx ' "$attempts"; [ -n "$license" ] && printf '%s ' "$license"; [ -n "$source" ] && printf 'src ' )" >&2

  {
    # jsonnetfmt quotes a key only when it must; emit quoted and let it decide.
    printf "  '%s': {\n" "$id"
    [ -n "$license" ] && printf "    license: '%s',\n" "$license"
    [ -n "$title" ] && printf "    title: '%s',\n" "${title//\'/\\\'}"
    [ -n "$source" ] && printf "    source: '%s',\n" "$source"
    [ -n "$url" ] && printf "    homepage: '%s',\n" "$url"
    printf '  },\n'
  } >> "$tmp"
done

printf '}\n' >> "$tmp"
mv "$tmp" "$out"

echo "wrote ${out}: ${covered}/${total} workloads carry usable image labels"
[ -n "$missing" ] && {
  echo "no usable labels (annotate these by hand in catalog/annotations.libsonnet):"
  printf '%s\n' "$missing" | tr ' ' '\n' | grep -v '^$' | sort | paste -sd' ' -
}
[ -n "$kept" ] && {
  echo "::error::registry unreachable for: $(printf '%s\n' "$kept" | tr ' ' '\n' | grep -v '^$' | sort | paste -sd' ' -)"
  echo "::error::their previous entries were kept — rerun once the registry answers"
  exit 1
}
exit 0
