# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# Generates catalog/architectures.gen.libsonnet: the linux CPU architectures each
# stage's pinned image publishes, read from the image's manifest list. A
# self-service portal reads it to keep an amd64-only image off an arm64 node
# (a per-tenant runtime failure) and to place arm-capable workloads on the
# cheaper burst tier. Derived from the registry, so it cannot be guessed wrong —
# rerun it when an image is bumped (Renovate touches the .image file, this reads
# it). check-catalog fails if an image-bearing stage has no entry.
set -uo pipefail
cd "$(dirname "$0")/.."

out=catalog/architectures.gen.libsonnet

# One stage: workloads/<w>/<stage>.image -> "<w>/<stage>": ["amd64",...]. A
# manifest LIST advertises its platforms; a single-arch image carries its
# architecture in the image config. An unreadable ref falls back to amd64 (the
# safe assumption — never schedules onto arm on a guess).
inspect_one() {
  local img="$1" key ref raw arches
  key="$(printf '%s' "$img" | sed -E 's#workloads/([^/]+)/([^/]+)\.image#\1/\2#')"
  ref="$(cat "$img")"
  raw="$(skopeo inspect --retry-times 3 --raw "docker://${ref}" 2>/dev/null || true)"
  if [ -z "$raw" ]; then
    arches='["amd64"]'
  elif printf '%s' "$raw" | jq -e '.manifests' >/dev/null 2>&1; then
    arches="$(printf '%s' "$raw" | jq -c '[.manifests[].platform | select(.os=="linux") | .architecture] | unique')"
  else
    arches="$(skopeo inspect --retry-times 3 "docker://${ref}" 2>/dev/null | jq -c '[.Architecture]' 2>/dev/null || printf '["amd64"]')"
  fi
  printf '  "%s": %s,\n' "$key" "$arches"
}
export -f inspect_one

# Assemble the SPDX tags from parts so this generator does not itself read as
# carrying a second license declaration (REUSE scans it for SPDX tags).
spdx_copyright='SPDX-FileCopyrightText'
spdx_license='SPDX-License-Identifier'

{
  printf '// %s: The kurly Authors\n' "$spdx_copyright"
  printf '// %s: 0BSD\n' "$spdx_license"
  echo "//"
  echo "// Generated by gen-architectures — DO NOT EDIT. The linux CPU architectures"
  echo "// each stage's pinned image publishes, read from its manifest list. Rerun"
  echo "// gen-architectures after an image bump; check-catalog fails on a missing entry."
  echo "{"
  git ls-files 'workloads/*/*.image' | xargs -P8 -I{} bash -c 'inspect_one "$@"' _ {} | LC_ALL=C sort
  echo "}"
} >"$out"

echo "wrote $out ($(grep -c ': \[' "$out") stages)"
