# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# Asks a real API server which bollwerk policies each workload stage violates,
# and writes the answers to catalog/bsi.gen.libsonnet.
#
# Why a cluster rather than a reading of the rules: bollwerk's policies are CEL,
# and the thing that evaluates CEL the way production will is the API server that
# will evaluate it in production. A hand-written "policy X means Y" mapping would
# be a second implementation of the rules, and it would drift silently. (The
# kyverno CLI can evaluate policies offline, but it ignores their matchConstraints
# here — it reports a PersistentVolumeClaim as violating a ServiceAccount policy —
# so its verdicts cannot be published.)
#
# Nothing here is authored by hand: the policies come from bollwerk (in this
# repository), the manifests from the workloads, the verdicts from the API server.
#
# Every binding is installed as **Warn**, which is what makes one pass enough. A
# Deny stops at the first policy that rejects, so a stage violating four would
# report one; Audit only reaches the audit log. Warn returns EVERY violation as a
# warning header on the very same dry-run, so each stage is asked once and
# answered completely — and nothing is ever rejected, so the sweep cannot leave a
# cluster that refuses workloads behind it.
#
# A stage whose kind is a custom resource is left out rather than reported as
# compliant: its CRD is absent here, so the API server rejects it before a policy
# sees it, and "not measured" must never read as "passed".
set -euo pipefail

# The workload glob below expands in the shell's collation order, and a locale
# that ignores punctuation orders `calibre-web` after `calibre` where C orders it
# before. The generated file would then differ between a contributor's machine
# and CI, and the drift check would fail on nothing but which one ran it.
export LC_ALL=C

out=catalog/bsi.gen.libsonnet
ns=bsi-probe

# The policies are cluster-scoped, so this must never run against a cluster
# anyone relies on — even as Warn, they would annotate everything admitted there.
context="$(kubectl config current-context 2>/dev/null || true)"
case "$context" in
  kind-*) ;;
  *)
    echo "::error::refusing to run against non-kind context '${context}'; this installs cluster-wide policies"
    exit 1
    ;;
esac

work="$(mktemp -d)"
cleanup() {
  kubectl delete --filename="${work}/policies.json" --ignore-not-found --wait=false >/dev/null 2>&1 || true
  kubectl delete namespace "$ns" --ignore-not-found --wait=false >/dev/null 2>&1 || true
  rm -rf "$work"
}
trap cleanup EXIT

# jb install CLEANS the vendor tree it manages, so the repo symlink has to be
# made after it and not before: created first, jb deletes it, every stage then
# fails to import its own workload, and the sweep reports the whole catalogue as
# unjudged — which reads like 300 missing CRDs rather than like a broken
# checkout.
[ -f vendor/.kurly-vendored ] || { jb install >/dev/null && touch vendor/.kurly-vendored; }
mkdir -p vendor/github.com/metio
ln -sfn ../../.. vendor/github.com/metio/kurly

kubectl create namespace "$ns" --dry-run=client --output=yaml | kubectl apply --filename=- >/dev/null

echo "== installing every bollwerk policy as Warn =="
jsonnet -e 'local b = import "bollwerk/bollwerk.libsonnet";
  {
    apiVersion: "v1",
    kind: "List",
    items: [
      if i.kind == "ValidatingAdmissionPolicyBinding" then i + { spec+: { validationActions: ["Warn"] } } else i
      for i in b.list.items
    ],
  }' > "${work}/policies.json"
kubectl apply --filename="${work}/policies.json" >/dev/null

# The policies are recorded by NAME: two of them share an id (both hostpath
# rules are 009), and the name is also what the API server reports. The catalog
# resolves a name to its id, category and BSI requirement from the policies
# themselves.
jsonnet -e 'local b = import "bollwerk/bollwerk.libsonnet";
  [ i.metadata.name for i in b.list.items if i.kind == "ValidatingAdmissionPolicy" ]' > "${work}/names.json"

# A binding is not enforced the instant it lands; give the API server a moment to
# pick the set up before trusting a verdict.
sleep 10

echo "== asking the API server about every stage =="
judged=0
unevaluated=""
: > "${work}/entries"
{
  printf '// %s: The kurly Authors\n' 'SPDX-FileCopyrightText'
  printf '// %s: 0BSD\n\n' 'SPDX-License-Identifier'
  printf '// Generated by scripts/gen-bsi.sh — do not edit; regenerate with: gen-bsi\n'
  printf '//\n'
  printf '// The bollwerk policies each stage violates, as judged by an API server\n'
  printf '// evaluating the policies themselves. A stage that breaks none carries an\n'
  printf '// empty list; one that could not be judged (a custom resource whose CRD is\n'
  printf '// absent) is absent here, because "not measured" is not "passed".\n'
  printf '{\n'
} > "${work}/out.libsonnet"

for dir in workloads/*/; do
  id="${dir#workloads/}"; id="${id%/}"
  for file in "$dir"*.libsonnet; do
    [ -f "$file" ] || continue
    stage="$(basename "$file" .libsonnet)"
    render="${work}/render.json"
    # The stage exactly as a consumer renders it. It used to be composed with
    # k.hostUsers() — the relaxation the smoke scenarios need because kind
    # cannot nest user namespaces — but nothing here ever starts a pod: a
    # server-side dry run is admission only. Composing it meant every verdict
    # described a workload with hostUsers:true, which is not the workload kurly
    # ships, and it hid the user namespace from the very policies that read it.
    if ! jsonnet -J vendor -e \
      "local k = import 'github.com/metio/kurly/main.libsonnet'; k.list((import '${file}')())" \
      > "$render" 2>/dev/null; then
      unevaluated="${unevaluated}${id}/${stage} "
      continue
    fi
    # Warnings arrive on stderr; a rejection means the object never reached the
    # policies (a custom resource without its CRD), which is not a verdict.
    warnings="$(kubectl apply --namespace="$ns" --dry-run=server --filename="$render" 2>&1 >/dev/null || true)"
    if grep -q 'no matches for kind\|failed to create typed patch object\|is invalid' <<<"$warnings"; then
      unevaluated="${unevaluated}${id}/${stage} "
      continue
    fi
    names="$(grep -oP "ValidatingAdmissionPolicy '\K[^']+" <<<"$warnings" | sort -u | paste -sd' ' - || true)"
    printf "  '%s/%s': [" "$id" "$stage" >> "${work}/entries"
    first=true
    for policy in $names; do
      $first || printf ', ' >> "${work}/entries"
      printf "'%s'" "$policy" >> "${work}/entries"
      first=false
    done
    printf '],\n' >> "${work}/entries"
    judged=$((judged + 1))
  done
done
# Sorted here rather than left in the order the glob happened to produce: a
# locale that ignores punctuation walks `calibre-web` and `calibre` the other way
# round, and the file would differ between a contributor's machine and CI while
# saying exactly the same thing. Sorting the ENTRIES, not the directories, is
# what makes the two agree — `thanos/query` and `thanos/query-frontend` order one
# way as paths and the other way as keys.
LC_ALL=C sort "${work}/entries" >> "${work}/out.libsonnet"
printf '}\n' >> "${work}/out.libsonnet"
mv "${work}/out.libsonnet" "$out"
jsonnetfmt --in-place "$out"

if [ "$judged" = 0 ]; then
  echo "::error::no stage could be judged at all — that is a broken run (an unusable vendor tree or an API server that never answered), not a catalogue with nothing to report" >&2
  exit 1
fi
echo "wrote ${out}: ${judged} stages judged against $(jq 'length' "${work}/names.json") policies"
[ -n "$unevaluated" ] && {
  echo "not judged (no CRD here, or no default render): $(printf '%s\n' "$unevaluated" | tr ' ' '\n' | grep -v '^$' | sort | paste -sd' ' -)"
}
exit 0
