#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# Generates the fast-check e2e scenario for every workload that boots from its own
# published image, driven entirely by the catalog: `hack/smoke/scenario-<id>.sh`
# provisions any declared dependency, mints the Secret the app reads, boots every
# stage, and waits for health. `gen-maturity` lifts each covered workload to the
# `e2e` tier from the scenario's existence.
#
# There are NO per-workload workflows — a single `.github/workflows/e2e.yml`
# pipeline detects which workloads a PR changed and runs their fast check (this
# scenario) then their deep check, so CI is one run, never hundreds.
#
# It touches ONLY generated files: a scenario carrying the marker below is
# regenerated in place, one lacking it (a hand-authored scenario like tik's) is
# left untouched. Standalone workloads (empty `requires`) just boot; dependency-
# backed ones first stand up a throwaway postgres/valkey at the service names the
# app defaults to, so it connects with no param override, and get a Secret minted
# from the catalog's per-stage `secretKeys`.
set -euo pipefail
# Run from the repository root (as the flake's `gen-smoke` command does), matching
# the sibling gen-* scripts — paths below are repo-relative.

# Assemble the SPDX tag names from parts so the literal tokens never appear whole
# in this generator's source — otherwise REUSE reads the header lines this script
# PRINTS as (invalid, duplicated) license expressions of the script itself.
spdx_copy='SPDX-File''CopyrightText'
spdx_lic='SPDX-License''-Identifier'

marker='# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke'
catalog=catalog/catalog.json
[ -f "$catalog" ] || { echo "::error::$catalog missing — run gen-catalog first"; exit 1; }

generated=0 generated_dep=0 skipped_hand=0

# Extracts a stage parameter's simple quoted default (dbHost='x' -> x); empty when
# the default is a computed expression rather than a literal.
param() { grep -oE "^[[:space:]]*$2='[^']*'" "$1" 2>/dev/null | head -1 | sed -E "s/.*='([^']*)'.*/\1/" || true; }

# A generated scenario is regenerated in place; a hand-written one is left alone.
is_hand_written() {
  local scenario="hack/smoke/scenario-$1.sh"
  [ -f "$scenario" ] && ! grep -qF "$marker" "$scenario"
}

emit_header() {
  printf '#!/usr/bin/env bash\n'
  printf '# %s: The kurly Authors\n' "$spdx_copy"
  printf '# %s: 0BSD\n\n' "$spdx_lic"
  printf '%s\n' "$marker"
}

# --- standalone workloads: empty `requires`, at least one real image ----------
while IFS=$'\t' read -r id stages; do
  [ -n "$id" ] || continue
  if is_hand_written "$id"; then skipped_hand=$((skipped_hand + 1)); continue; fi
  scenario="hack/smoke/scenario-${id}.sh"

  # Boot each stage in its own namespace; a single-stage workload gets the bare
  # kurly-<id> namespace, multi-stage workloads suffix the stage.
  boot_lines=""
  IFS=',' read -ra arr <<<"$stages"
  for stage in "${arr[@]}"; do
    file="workloads/${id}/${stage}.libsonnet"
    [ -f "$file" ] || { echo "::error::${file} referenced by the catalog does not exist"; exit 1; }
    if [ "${#arr[@]}" -eq 1 ]; then ns="kurly-${id}"; else ns="kurly-${id}-${stage}"; fi
    # A stage that reads a Secret (envFromSecret) declares secretKeys in the
    # catalog even without a database/cache dependency; mint that Secret before
    # booting or the container fails with "secret not found".
    if [ "$(jq -r --arg ip "github.com/metio/kurly/${file}" '[.workloads[].stages[] | select(.importPath==$ip) | .secretKeys // []] | add | length' "$catalog")" != 0 ]; then
      secretName="$(param "$file" secretName)"; [ -n "$secretName" ] || secretName="$id"
      # The namespace must exist before the Secret is applied; kurly::boot also
      # ensures it (idempotent), so creating it here first is safe.
      boot_lines+="kurly::namespace ${ns}"$'\n'
      boot_lines+="kurly::secret ${ns} ${secretName} ${file}"$'\n'
    fi
    boot_lines+="kurly::boot ${file} ${ns}"$'\n'
  done

  {
    emit_header
    printf '# e2e for the %s workload: boot every stage on a live kind cluster from its\n' "$id"
    printf '# own published image and wait for it to become healthy. No external dependency.\n'
    printf 'cd "$(dirname "$0")/../.."\n'
    printf '# shellcheck source=hack/smoke/lib.sh\n'
    printf 'source hack/smoke/lib.sh\n'
    printf 'kurly::vendor\n\n'
    printf '%s' "$boot_lines"
  } >"$scenario"
  chmod +x "$scenario"
  generated=$((generated + 1))
done < <(jq -r '
  .workloads[]
  | select((.requires // {} | length) == 0)
  | select([.stages[].architectures] | any(. != null))
  | "\(.id)\t\([.stages[].id] | join(","))"
' "$catalog")

# --- dependency-backed workloads ----------------------------------------------
# Provision each declared dependency at the service name the app defaults to (so
# it connects with no param override), mint the Secret it reads, then boot every
# stage in the shared namespace. The connection defaults follow kurly's naming
# convention (<name>-db-rw, <name>-cache-headless); the throwaway postgres/valkey
# are created under exactly those names.
while IFS=$'\t' read -r id stages db cache; do
  [ -n "$id" ] || continue
  if is_hand_written "$id"; then skipped_hand=$((skipped_hand + 1)); continue; fi
  scenario="hack/smoke/scenario-${id}.sh"
  IFS=',' read -ra arr <<<"$stages"
  primary="workloads/${id}/${arr[0]}.libsonnet"

  prov=""
  if [ "$db" = "1" ]; then
    dbName="$(param "$primary" dbName)"; [ -n "$dbName" ] || dbName="$(param "$primary" database)"; [ -n "$dbName" ] || dbName="$id"
    dbUser="$(param "$primary" dbUser)"; [ -n "$dbUser" ] || dbUser="$id"
    # MySQL/MariaDB apps read port 3306 (postgres apps 5432); provision the engine
    # the app connects to, at the host it defaults to.
    if grep -qE "3306|mariadb|mysql" "$primary" 2>/dev/null; then
      dbHost="$(param "$primary" dbHost)"; [ -n "$dbHost" ] || dbHost="${id}-db"
      prov+="kurly::mysql \"\$ns\" ${dbHost} ${dbName} ${dbUser}"$'\n'
    else
      dbHost="$(param "$primary" dbHost)"; [ -n "$dbHost" ] || dbHost="${id}-db-rw"
      prov+="kurly::postgres \"\$ns\" ${dbHost} ${dbName} ${dbUser}"$'\n'
    fi
  fi
  if [ "$cache" = "1" ]; then
    redisHost="$(param "$primary" redisHost)"; [ -n "$redisHost" ] || redisHost="${id}-cache-headless"
    prov+="kurly::cache \"\$ns\" ${redisHost}"$'\n'
  fi

  boot_lines=""
  for stage in "${arr[@]}"; do
    file="workloads/${id}/${stage}.libsonnet"
    [ -f "$file" ] || { echo "::error::${file} referenced by the catalog does not exist"; exit 1; }
    secretName="$(param "$file" secretName)"; [ -n "$secretName" ] || secretName="$id"
    boot_lines+="kurly::secret \"\$ns\" ${secretName} ${file}"$'\n'
    boot_lines+="kurly::boot ${file} \"\$ns\""$'\n'
  done

  {
    emit_header
    printf '# e2e for the %s workload: provision its declared dependencies (a throwaway\n' "$id"
    printf '# postgres/valkey at the service names it defaults to), mint the Secret it reads\n'
    printf '# from the catalog secretKeys, then boot every stage and wait for health.\n'
    printf 'cd "$(dirname "$0")/../.."\n'
    printf '# shellcheck source=hack/smoke/lib.sh\n'
    printf 'source hack/smoke/lib.sh\n'
    printf 'kurly::vendor\n\n'
    printf 'ns=kurly-%s\n' "$id"
    printf 'kurly::namespace "$ns"\n\n'
    printf '%s\n' "$prov"
    printf '%s' "$boot_lines"
  } >"$scenario"
  chmod +x "$scenario"
  generated_dep=$((generated_dep + 1))
done < <(jq -r '
  .workloads[]
  | select((.requires // {} | length) > 0)
  | select([.stages[].architectures] | any(. != null))
  | "\(.id)\t\([.stages[].id] | join(","))\t\(if .requires.database then 1 else 0 end)\t\(if .requires.cache then 1 else 0 end)"
' "$catalog")

# A durable coverage ledger, regenerated every run so it never drifts and stays
# readable across working sessions.
{
  printf '<!-- %s: The kurly Authors -->\n' "$spdx_copy"
  printf '<!-- %s: 0BSD -->\n\n' "$spdx_lic"
  printf '<!-- generated by scripts/gen-smoke.sh — do not edit -->\n\n'
  printf '# e2e coverage\n\n'
  printf 'An e2e scenario boots every workload on a live kind cluster — standalone\n'
  printf 'workloads directly, dependency-backed ones after provisioning a throwaway\n'
  printf 'postgres/valkey and minting their Secret. All are generated by `gen-smoke`.\n\n'
  total=$(jq '.workloads | length' "$catalog")
  cov=$(jq '[.workloads[] | select(.maturity.tier == "e2e")] | length' "$catalog")
  printf '**%s / %s workloads have an e2e scenario.**\n' "$cov" "$total"
  remaining="$(jq -r '.workloads[] | select(.maturity.tier != "e2e") | "- \(.id)"' "$catalog" | sort)"
  if [ -n "$remaining" ]; then
    printf '\nWorkloads still awaiting a scenario:\n\n%s\n' "$remaining"
  else
    printf '\nEvery workload has an e2e scenario.\n'
  fi
} >hack/smoke/COVERAGE.md

echo "gen-smoke: generated ${generated} standalone + ${generated_dep} dependency-backed scenarios"
echo "gen-smoke: left ${skipped_hand} hand-written scenarios untouched"
echo "gen-smoke: wrote hack/smoke/COVERAGE.md"
