#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# Folds what the e2e scenarios measured into catalog/measurements.gen.libsonnet:
# how long each stage took to become Ready, and how much memory it needed to get
# there versus to keep running. The scenarios write one file per stage under
# .build/measurements as they go (so a fleet walk that is killed keeps what it
# measured); this reads them and merges them over what previous runs recorded.
#
# MERGED, NEVER REPLACED: a full fleet walk takes hours, and re-running one
# workload must not retract the measurements for the other four hundred. A stage
# measured today wins over the same stage measured last month; a stage not
# measured this run keeps what it had.
#
# WHAT THESE NUMBERS ARE. They come from a kind cluster on a developer machine,
# so they are not a production sizing guide and the file says so where a reader
# will see it. What survives the move to real hardware is the SHAPE: which
# workloads need far more memory to start than to run, which take minutes rather
# than seconds before they serve, and how they compare with each other.
set -euo pipefail

out=catalog/measurements.gen.libsonnet
in=.build/measurements

previous="$(mktemp)"
merged="$(mktemp)"
trap 'rm -f "$previous" "$merged"' EXIT

if [ -f "$out" ]; then jsonnet "$out" 2>/dev/null >"$previous" || echo '{}' >"$previous"; else echo '{}' >"$previous"; fi

if [ -d "$in" ] && [ -n "$(find "$in" -name '*.json' -print -quit 2>/dev/null)" ]; then
  jq -s 'map({(.key): {digest: .digest, secondsToReady: .secondsToReady,
                       peakStartupBytes: .peakStartupBytes, steadyBytes: .steadyBytes}})
         | add // {}' "$in"/*.json >"$merged"
else
  echo '{}' >"$merged"
fi

# Assemble the SPDX tags from parts so this generator does not itself read as
# carrying a second license declaration (REUSE scans it for SPDX tags).
spdx_copyright='SPDX-FileCopyrightText'
spdx_license='SPDX-License-Identifier'

{
  printf '// %s: The kurly Authors\n' "$spdx_copyright"
  printf '// %s: 0BSD\n' "$spdx_license"
  echo "//"
  echo "// Generated by gen-measurements — DO NOT EDIT. What each stage actually cost"
  echo "// to start, measured while the e2e scenario booted it: seconds from apply to"
  echo "// Ready, the highest memory reading seen on the way there, and the reading"
  echo "// after it settled."
  echo "//"
  echo "// MEASURED ON A KIND CLUSTER ON A DEVELOPER MACHINE. These are not production"
  echo "// sizing numbers and must not be published as though they were. What carries"
  echo "// over to real hardware is the shape: which workloads need far more memory to"
  echo "// start than to run, which take minutes rather than seconds before they serve,"
  echo "// and how they compare with one another."
  echo "//"
  echo "// Each entry names the image digest it was measured on, and catalog.jsonnet"
  echo "// drops the claim when the pin moves past it — a figure carried forward onto"
  echo "// bits nobody ran is a guess in a field whose whole point is that it is not."
  echo "{"
  # An absent digest is a jsonnet null, never the STRING "null": the value is read
  # by catalog.jsonnet to decide whether the measurement still describes the
  # image that is pinned now, and a string always compares unequal, which would
  # silently drop every measurement taken before digests were recorded rather
  # than saying they are unanchored.
  jq -s '.[0] * .[1] | to_entries | sort_by(.key) | .[]
         | "  \"\(.key)\": { digest: \(if (.value.digest // "") == "" then "null" else "'"'"'\(.value.digest)'"'"'" end), secondsToReady: \(.value.secondsToReady), peakStartupBytes: \(.value.peakStartupBytes), steadyBytes: \(.value.steadyBytes) },"' \
    --raw-output "$previous" "$merged"
  echo "}"
} >"$out"

jsonnetfmt --in-place "$out"
echo "wrote $out ($(grep -c ': {' "$out") stages)"
