# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# Derive each workload's maturity tier from what the repository actually proves,
# and write it to catalog/maturity.gen.libsonnet (imported by catalog.jsonnet).
# The point is that the tier cannot lie: it is recomputed from the real signals
# every run, and check-catalog fails if the committed file is stale.
#
#   e2e     — a hack/smoke/scenario-*.sh deploys the workload to a live (kind)
#             cluster and waits for it to become ready
#   tested  — tests/*.jsonnet carries workload-specific assertions beyond the
#             library-wide structural sweep
#   rendered— everything else: renders and validates (kubeconform) with defaults,
#             which every catalogued workload does by construction
#
# The `rendered` floor is implicit (the absence of the other two), so only e2e and
# tested are listed here. production maturity is operator-attested, not derived —
# it lives in the hand-edited catalog/production.libsonnet.

set -euo pipefail

out=catalog/maturity.gen.libsonnet

# A workload is a directory under workloads/; a signal counts only when it names a
# real workload directory (a scenario or test may reference something that is not
# a catalogued workload).
workloads="$(find workloads -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort)"

# e2e: workloads a smoke scenario deploys. tested: workloads a test asserts on.
e2e="$(grep -rhoE 'workloads/[a-z0-9-]+' hack/smoke/scenario-*.sh 2>/dev/null | sed 's#workloads/##' | sort -u)"
tested="$(grep -rhoE 'workloads/[a-z0-9-]+' tests/*.jsonnet 2>/dev/null | sed 's#workloads/##' | sort -u)"

# Keep only names that are real workload directories.
e2e="$(comm -12 <(printf '%s\n' "$e2e") <(printf '%s\n' "$workloads"))"
tested="$(comm -12 <(printf '%s\n' "$tested") <(printf '%s\n' "$workloads"))"

emit_array() {
  # Emit a sorted jsonnet string array, two-space indented, one entry per line —
  # the layout jsonnetfmt produces, so the generated file passes check-fmt.
  local names="$1"
  if [ -z "$names" ]; then
    printf '[]'
    return
  fi
  printf '[\n'
  while IFS= read -r n; do
    [ -n "$n" ] || continue
    printf "    '%s',\n" "$n"
  done <<<"$names"
  printf '  ]'
}

# Assemble the SPDX tags from parts so this generator script does not itself read
# as carrying a second license declaration (REUSE scans it for SPDX tags).
spdx_copyright='SPDX-FileCopyrightText'
spdx_license='SPDX-License-Identifier'

{
  printf '// %s: The kurly Authors\n' "$spdx_copyright"
  printf '// %s: 0BSD\n\n' "$spdx_license"
  printf '// GENERATED by scripts/gen-maturity.sh — do not edit. Regenerate with: gen-maturity\n'
  printf '//\n'
  printf '// The derived maturity signals. e2e names the workloads a hack/smoke scenario\n'
  printf '// deploys to a live cluster; tested names the workloads a test asserts on. Every\n'
  printf '// other catalogued workload sits at the rendered floor. check-catalog recomputes\n'
  printf '// this file and fails if it drifts, so the tiers stay honest.\n'
  printf '{\n'
  printf '  e2e: '
  emit_array "$e2e"
  printf ',\n'
  printf '  tested: '
  emit_array "$tested"
  printf ',\n'
  printf '}\n'
} >"$out"

echo "wrote $out"
