#!/usr/bin/env bash
# SPDX-FileCopyrightText: The kurly Authors
# SPDX-License-Identifier: 0BSD

# Generates a live-cluster e2e for every workload that boots from its own
# published image, driven entirely by the catalog. For each workload it emits a
# `hack/smoke/scenario-<id>.sh` (provision any declared dependency, mint the
# Secret the app reads, boot every stage, wait for health) and a thin
# `.github/workflows/e2e-<id>.yml` (self-gated on the workload's paths, delegating
# to the reusable e2e workflow) — the same shape the hand-written scenarios use,
# so `gen-maturity` lifts each covered workload to the `e2e` tier automatically.
#
# It touches ONLY generated files: a scenario carrying the marker below is
# regenerated in place, one lacking it (a hand-authored scenario like tik's) is
# left untouched. Standalone workloads (empty `requires`) just boot; dependency-
# backed ones first stand up a throwaway postgres/valkey at the service names the
# app defaults to, so it connects with no param override, and get a Secret minted
# from the catalog's per-stage `secretKeys`.
set -euo pipefail
# Run from the repository root (as the flake's `gen-smoke` command does), matching
# the sibling gen-* scripts — paths below are repo-relative.

# Assemble the SPDX tag names from parts so the literal tokens never appear whole
# in this generator's source — otherwise REUSE reads the header lines this script
# PRINTS as (invalid, duplicated) license expressions of the script itself.
spdx_copy='SPDX-File''CopyrightText'
spdx_lic='SPDX-License''-Identifier'

marker='# generated by scripts/gen-smoke.sh — do not edit; regenerate with: gen-smoke'
catalog=catalog/catalog.json
[ -f "$catalog" ] || { echo "::error::$catalog missing — run gen-catalog first"; exit 1; }

generated=0 generated_dep=0 skipped_hand=0

# Extracts a stage parameter's simple quoted default (dbHost='x' -> x); empty when
# the default is a computed expression rather than a literal.
param() { grep -oE "^[[:space:]]*$2='[^']*'" "$1" 2>/dev/null | head -1 | sed -E "s/.*='([^']*)'.*/\1/" || true; }

# A generated scenario is regenerated in place; a hand-written one is left alone.
is_hand_written() {
  local scenario="hack/smoke/scenario-$1.sh"
  [ -f "$scenario" ] && ! grep -qF "$marker" "$scenario"
}

# Emits the thin per-workload e2e workflow (shared by both scenario kinds). A
# constant job id `e2e` keeps it valid for names starting with a digit (2fauth);
# the paths regex can exceed yamllint's line length, so it is a single line with
# the one rule silenced.
gen_workflow() {
  local id="$1" workflow=".github/workflows/e2e-${id}.yml"
  {
    printf '# %s: The kurly Authors\n' "$spdx_copy"
    printf '# %s: 0BSD\n\n' "$spdx_lic"
    printf '%s\n' "$marker"
    printf '# Per-workload e2e for %s. Self-gates on a diff scoped to this workload (plus the\n' "$id"
    printf '# shared library and the e2e machinery), delegating the matrix + run to the\n'
    printf '# reusable e2e workflow.\n'
    printf 'name: E2E %s\n' "$id"
    # Workflow-level path filter: GitHub does not even START this workflow unless
    # the PR touches this workload'\''s directory. A Renovate image bump runs exactly
    # one e2e; a shared change queues NONE — no per-workload runner is spun up just
    # to self-skip, which is what fans ~300 jobs out and blows the CI budget.
    printf 'on:\n  pull_request:\n    branches: [main]\n    paths:\n      - '\''workloads/%s/**'\''\n  workflow_dispatch:\n' "$id"
    printf 'permissions:\n  contents: read\n'
    # A new push to the same ref cancels this workload'\''s superseded in-flight run,
    # so a rapid series of commits never stacks up kind clusters.
    printf 'concurrency:\n  group: e2e-%s-${{ github.ref }}\n  cancel-in-progress: true\n' "$id"
    printf 'jobs:\n  e2e:\n'
    printf '    uses: ./.github/workflows/e2e.yml\n'
    printf '    with:\n'
    printf '      workload: %s\n' "$id"
    # Scope the trigger to the workload'\''s OWN directory only. A Renovate image
    # bump touches workloads/<id>/ and runs exactly this one e2e; a shared change
    # (lib/, main.libsonnet, the smoke harness) must NOT fan out to all ~300
    # workloads — the full sweep is dispatch/scheduled, not per-PR.
    printf "      paths: '^workloads/%s/'\n" "$id"
    printf '      scenario: hack/smoke/scenario-%s.sh\n' "$id"
    # Fast feedback: one k8s minor, so a Renovate image bump gets a quick
    # broken/not-broken verdict. Deeper multi-version + traffic tests come later.
    printf "      max_versions: '1'\n"
  } >"$workflow"
}

emit_header() {
  printf '#!/usr/bin/env bash\n'
  printf '# %s: The kurly Authors\n' "$spdx_copy"
  printf '# %s: 0BSD\n\n' "$spdx_lic"
  printf '%s\n' "$marker"
}

# --- standalone workloads: empty `requires`, at least one real image ----------
while IFS=$'\t' read -r id stages; do
  [ -n "$id" ] || continue
  if is_hand_written "$id"; then skipped_hand=$((skipped_hand + 1)); continue; fi
  scenario="hack/smoke/scenario-${id}.sh"

  # Boot each stage in its own namespace; a single-stage workload gets the bare
  # kurly-<id> namespace, multi-stage workloads suffix the stage.
  boot_lines=""
  IFS=',' read -ra arr <<<"$stages"
  for stage in "${arr[@]}"; do
    file="workloads/${id}/${stage}.libsonnet"
    [ -f "$file" ] || { echo "::error::${file} referenced by the catalog does not exist"; exit 1; }
    if [ "${#arr[@]}" -eq 1 ]; then ns="kurly-${id}"; else ns="kurly-${id}-${stage}"; fi
    boot_lines+="kurly::boot ${file} ${ns}"$'\n'
  done

  {
    emit_header
    printf '# e2e for the %s workload: boot every stage on a live kind cluster from its\n' "$id"
    printf '# own published image and wait for it to become healthy. No external dependency.\n'
    printf 'cd "$(dirname "$0")/../.."\n'
    printf '# shellcheck source=hack/smoke/lib.sh\n'
    printf 'source hack/smoke/lib.sh\n'
    printf 'kurly::vendor\n\n'
    printf '%s' "$boot_lines"
  } >"$scenario"
  chmod +x "$scenario"
  gen_workflow "$id"
  generated=$((generated + 1))
done < <(jq -r '
  .workloads[]
  | select((.requires // {} | length) == 0)
  | select([.stages[].architectures] | any(. != null))
  | "\(.id)\t\([.stages[].id] | join(","))"
' "$catalog")

# --- dependency-backed workloads ----------------------------------------------
# Provision each declared dependency at the service name the app defaults to (so
# it connects with no param override), mint the Secret it reads, then boot every
# stage in the shared namespace. The connection defaults follow kurly's naming
# convention (<name>-db-rw, <name>-cache-headless); the throwaway postgres/valkey
# are created under exactly those names.
while IFS=$'\t' read -r id stages db cache; do
  [ -n "$id" ] || continue
  if is_hand_written "$id"; then skipped_hand=$((skipped_hand + 1)); continue; fi
  scenario="hack/smoke/scenario-${id}.sh"
  IFS=',' read -ra arr <<<"$stages"
  primary="workloads/${id}/${arr[0]}.libsonnet"

  prov=""
  if [ "$db" = "1" ]; then
    dbHost="$(param "$primary" dbHost)"; [ -n "$dbHost" ] || dbHost="${id}-db-rw"
    dbName="$(param "$primary" dbName)"; [ -n "$dbName" ] || dbName="$(param "$primary" database)"; [ -n "$dbName" ] || dbName="$id"
    dbUser="$(param "$primary" dbUser)"; [ -n "$dbUser" ] || dbUser="$id"
    prov+="kurly::postgres \"\$ns\" ${dbHost} ${dbName} ${dbUser}"$'\n'
  fi
  if [ "$cache" = "1" ]; then
    redisHost="$(param "$primary" redisHost)"; [ -n "$redisHost" ] || redisHost="${id}-cache-headless"
    prov+="kurly::cache \"\$ns\" ${redisHost}"$'\n'
  fi

  boot_lines=""
  for stage in "${arr[@]}"; do
    file="workloads/${id}/${stage}.libsonnet"
    [ -f "$file" ] || { echo "::error::${file} referenced by the catalog does not exist"; exit 1; }
    secretName="$(param "$file" secretName)"; [ -n "$secretName" ] || secretName="$id"
    boot_lines+="kurly::secret \"\$ns\" ${secretName} ${file}"$'\n'
    boot_lines+="kurly::boot ${file} \"\$ns\""$'\n'
  done

  {
    emit_header
    printf '# e2e for the %s workload: provision its declared dependencies (a throwaway\n' "$id"
    printf '# postgres/valkey at the service names it defaults to), mint the Secret it reads\n'
    printf '# from the catalog secretKeys, then boot every stage and wait for health.\n'
    printf 'cd "$(dirname "$0")/../.."\n'
    printf '# shellcheck source=hack/smoke/lib.sh\n'
    printf 'source hack/smoke/lib.sh\n'
    printf 'kurly::vendor\n\n'
    printf 'ns=kurly-%s\n' "$id"
    printf 'kurly::namespace "$ns"\n\n'
    printf '%s\n' "$prov"
    printf '%s' "$boot_lines"
  } >"$scenario"
  chmod +x "$scenario"
  gen_workflow "$id"
  generated_dep=$((generated_dep + 1))
done < <(jq -r '
  .workloads[]
  | select((.requires // {} | length) > 0)
  | select([.stages[].architectures] | any(. != null))
  | "\(.id)\t\([.stages[].id] | join(","))\t\(if .requires.database then 1 else 0 end)\t\(if .requires.cache then 1 else 0 end)"
' "$catalog")

# A durable coverage ledger, regenerated every run so it never drifts and stays
# readable across working sessions.
{
  printf '<!-- %s: The kurly Authors -->\n' "$spdx_copy"
  printf '<!-- %s: 0BSD -->\n\n' "$spdx_lic"
  printf '<!-- generated by scripts/gen-smoke.sh — do not edit -->\n\n'
  printf '# e2e coverage\n\n'
  printf 'An e2e scenario boots every workload on a live kind cluster — standalone\n'
  printf 'workloads directly, dependency-backed ones after provisioning a throwaway\n'
  printf 'postgres/valkey and minting their Secret. All are generated by `gen-smoke`.\n\n'
  total=$(jq '.workloads | length' "$catalog")
  cov=$(jq '[.workloads[] | select(.maturity.tier == "e2e")] | length' "$catalog")
  printf '**%s / %s workloads have an e2e scenario.**\n' "$cov" "$total"
  remaining="$(jq -r '.workloads[] | select(.maturity.tier != "e2e") | "- \(.id)"' "$catalog" | sort)"
  if [ -n "$remaining" ]; then
    printf '\nWorkloads still awaiting a scenario:\n\n%s\n' "$remaining"
  else
    printf '\nEvery workload has an e2e scenario.\n'
  fi
} >hack/smoke/COVERAGE.md

echo "gen-smoke: generated ${generated} standalone + ${generated_dep} dependency-backed scenarios"
echo "gen-smoke: left ${skipped_hand} hand-written scenarios untouched"
echo "gen-smoke: wrote hack/smoke/COVERAGE.md"
